# -*- coding: utf-8 -*-
"""Lote 24 -- varridas dos bancos 40-4c: TEAM ROCKET, RADIO TOWER,
SPROUT TOWER, VICTORY ROAD, pescadores e treinadores de passagem.

Ficam no original: TEAM ROCKET, GRUNT, EXECUTIVE, RADIO TOWER, HIDEOUT,
UNDERGROUND, GOLDENROD, MAHOGANY, SPRout TOWER, ELDER, BIRD KEEPERS,
TM08, TM24, FALKNER, BELLSPROUT, MARILL, WOOSTER, MOON STONE,
GOLDENROD, OLIVINE, GYARADOS, BUTTERFREE, VICTORY ROAD, LEAGUE, ELITE,
CHAMP, CAMPEAO, BADGES, BADGE, BOX, HM, ROCKET.
"""
from pt.estrutura import linhas as L

DIALOGO = {
    # ---------------- banco 40 ----------------
    "40:5f99": L("40:5f99",
                 "{STRBUF}",
                 "de seu inimigo!"),

    # ---------------- banco 41 ----------------
    "41:5fa4": L("41:5fa4",
                 "{PLAYER}, você",
                 "sabia?",
                 "Ouvi dizer que",
                 "RADIO TOWER foi",
                 "tomada pela TEAM",
                 "ROCKET.",
                 "Mas o que é",
                 "a TEAM ROCKET?"),
    "41:6014": L("41:6014",
                 "{PLAYER}, você",
                 "ouviu a notícia?",
                 "A TEAM ROCKET",
                 "tomou a RADIO",
                 "TOWER de",
                 "GOLDENROD CITY.",
                 "Estarão bem os",
                 "funcionários?"),
    "41:608d": L("41:608d",
                 "Oi, {PLAYER}!",
                 "Nossas vendas de",
                 "BICYCLE foram",
                 "às nuvens!",
                 "Tudo graças à",
                 "sua propaganda,",
                 "andando por aí",
                 "na nossa BICYCLE.",
                 "Como forma de",
                 "agradecer, fique",
                 "com essa BICYCLE.",
                 "Valeu de novo!"),

    # ---------------- banco 42 ----------------
    "42:4087": L("42:4087",
                 "Todos os seres",
                 "vivos coexistem",
                 "em cooperação.",
                 "Devemos sempre ser",
                 "gratos por isso."),
    "42:42e3": L("42:42e3",
                 "Lutei duro, mas",
                 "sou fraco demais."),
    "42:4303": L("42:4303",
                 "A coluna flexível",
                 "protege a TOWER",
                 "mesmo contra",
                 "terremotos."),
    "42:4345": L("42:4345",
                 "…Balance como",
                 "folhas ao vento…"),
    "42:4373": L("42:4373",
                 "Tentei copiar os",
                 "movimentos gentis",
                 "do BELLSPROUT",
                 "para a batalha…",
                 "Mas não treinei",
                 "bem o bastante."),
    "42:48ba": L("42:48ba",
                 "Treino para achar",
                 "iluminação nos",
                 "POKéMON!"),
    "42:48e2": L("42:48e2",
                 "Derrotado por",
                 "uma mera criança!"),
    "42:48fb": L("42:48fb",
                 "Quando os POKéMON",
                 "ficam fortes, o",
                 "treinador também.",
                 "Espera. Quando o",
                 "treinador fica",
                 "forte, os POKéMON",
                 "também."),
    "42:4961": L("42:4961",
                 "Deixe-me ver o",
                 "quanto você confia",
                 "nos seus POKéMON."),
    "42:498b": L("42:498b",
                 "Sim, a sua",
                 "confiança é real!"),
    "42:49a5": L("42:49a5",
                 "Não é longe até",
                 "o ELDER."),
    "42:49c2": L("42:49c2",
                 "O HM do ELDER",
                 "ilumina até a",
                 "escuridão total."),
    "42:49f4": L("42:49f4",
                 "É a minha cabeça",
                 "que é brilhante!"),
    "42:4a13": L("42:4a13",
                 "Que haja luz",
                 "na sua jornada."),
    "42:5202": L("42:5202",
                 "Minha alma está",
                 "em chamas. Vou",
                 "mostrar como isso",
                 "queima!"),
    "42:5236": L("42:5236",
                 "Ainda não esquenta",
                 "o bastante…"),
    "42:524d": L("42:524d",
                 "Antigamente,",
                 "havia POKéMON",
                 "que corriam pela",
                 "grama em super",
                 "alta velocidade.",
                 "Dizem que correm",
                 "como o vento.",
                 "Se você esbarrar",
                 "em um na grama,",
                 "ele vai fugir."),

    # ---------------- banco 43 ----------------
    "43:4441": L("43:4441",
                 "O mundo POKéMON",
                 "é profundo.",
                 "Ainda existem",
                 "muitas coisas que",
                 "não sabemos.",
                 "Mas eu sei mais",
                 "do que você!"),
    "43:44b6": L("43:44b6",
                 "Há muito",
                 "o que aprender.",
                 "Por exemplo…",
                 "Existem 50 tipos",
                 "de TM.",
                 "POKéMON trocados",
                 "sobem mais rápido"),
    "43:4514": L("43:4514",
                 "Meus POKéMON são",
                 "tão fofos. Vou",
                 "mostrar a você."),
    "43:4547": L("43:4547",
                 "Talvez eu não",
                 "te vença na luta…",
                 "Mas os meus são",
                 "bem mais bonitos."),
    "43:4584": L("43:4584",
                 "Minha amiga tem um",
                 "MARILL. É tão",
                 "fofo! Queria ter",
                 "um MARILL."),
    "43:45c1": L("43:45c1",
                 "Adoramos nossos",
                 "POKéMON, mesmo que",
                 "eles não gostem.",
                 "É isso que é",
                 "ser um FAN."),
    "43:461d": L("43:461d",
                 "Perdi a batalha,",
                 "mas meus POKéMON",
                 "ganham o prêmio",
                 "por serem fofos."),
    "43:4662": L("43:4662",
                 "Olá? Por que você",
                 "fica me olhando?",
                 "Ah, uma batalha?"),
    "43:469b": L("43:469b",
                 "Pelo seu olhar,",
                 "pensei que você",
                 "gostava de mim.",
                 "Afinal, eu sou",
                 "fofa!"),
    "43:5481": L("43:5481",
                 "Finalmente",
                 "assumimos a",
                 "RADIO TOWER!",
                 "Agora todos vão",
                 "conhecer o terror",
                 "de verdade da",
                 "TEAM ROCKET!",
                 "Vamos mostrar",
                 "como assustamos!"),
    "43:550f": L("43:550f",
                 "Muito forte! Nós",
                 "temos que vigiar…"),
    "43:552f": L("43:552f",
                 "É forte demais.",
                 "Nosso plano pode",
                 "ruir. Preciso",
                 "avisar os outros…"),
    "43:5885": L("43:5885",
                 "Há três anos, a",
                 "TEAM ROCKET foi",
                 "obrigada a parar.",
                 "Mas agora a volta",
                 "vem com tudo!"),
    "43:58db": L("43:58db",
                 "Ugh! Não fica",
                 "engraçadinho!"),
    "43:58f1": L("43:58f1",
                 "Não vamos deixar",
                 "você arruinar os",
                 "nossos planos!"),
    "43:5923": L("43:5923",
                 "Somos TEAM ROCKET,",
                 "os que exploram",
                 "os POKéMON!",
                 "Amamos ser",
                 "malvados! Medo?"),
    "43:596a": L("43:596a",
                 "Você acha que é",
                 "um herói?"),
    "43:5983": L("43:5983",
                 "Não somos sempre",
                 "malvados. Fazemos",
                 "o que gostamos."),
    "43:59b7": L("43:59b7",
                 "Ei, ei! Sai do",
                 "nosso caminho!"),
    "43:59d7": L("43:59d7",
                 "Argh. Desisto."),
    "43:59ea": L("43:59ea",
                 "Nossos EXECUTIVOS",
                 "estão tentando",
                 "tomar este lugar.",
                 "Eles têm um plano",
                 "grande. Queria",
                 "saber o que é."),
    "43:5a4e": L("43:5a4e",
                 "Hahaha!",
                 "Que tédio.",
                 "Foi fácil",
                 "demais tomar",
                 "este lugar!",
                 "Vamos, me",
                 "divirta!"),
    "43:5aba": L("43:5aba",
                 "Você me venceu e",
                 "não vou esquecer!"),
    "43:5f16": L("43:5f16",
                 "Recebi ordens",
                 "rígidas.",
                 "Vou esmagar quem",
                 "desafiar a TEAM",
                 "ROCKET!"),
    "43:5f6e": L("43:5f6e",
                 "Falhei no meu",
                 "trabalho…",
                 "Vou ter desconto",
                 "no meu salário…"),
    "43:5fa2": L("43:5fa2",
                 "É ótimo mandar",
                 "os POKéMON",
                 "cometer crimes."),
    "43:5fd2": L("43:5fd2",
                 "Tá brincando!"),
    "43:5fe2": L("43:5fe2",
                 "Estou péssimo por",
                 "ter perdido!",
                 "Droga! Odeio",
                 "POKéMON inúteis!"),
    "43:601b": L("43:601b",
                 "Por que a persiana",
                 "abriu? Você tem",
                 "algo a ver com",
                 "isso?"),
    "43:606e": L("43:606e",
                 "O quê?! Passou",
                 "pelos nossos,",
                 "no UNDERGROUND?",
                 "Como conseguiu?"),
    "43:60b2": L("43:60b2",
                 "Uma criança",
                 "perdida por aqui?",
                 "Quem é você?"),
    "43:60e1": L("43:60e1",
                 "Tsk! Eu te",
                 "subestimei!"),
    "43:60ff": L("43:60ff",
                 "Bwahahaha…",
                 "Posso transmitir",
                 "um sinal tão forte",
                 "como eu precisar."),
    "43:6415": L("43:6415",
                 "Pretende salvar",
                 "o DIRECTOR?",
                 "Isso não será",
                 "possível, pois vou",
                 "te derrotar!"),
"43:646d": L("43:646d",
                  "Não pode ser!"),
    "43:6480": L("43:6480",
                 "Não acredito!",
                 "Fui derrotado!"),
    "43:64a2": L("43:64a2",
                 "Pare! Sou",
                 "conhecido como a",
                 "fortaleza da TEAM",
                 "ROCKET! Você",
                 "não vai passar!"),
    "43:64ee": L("43:64ee",
                 "A fortaleza",
                 "caiu!"),
    "43:6507": L("43:6507",
                 "Você ganhou meu",
                 "respeito, então",
                 "vai um conselho.",
                 "Não é tarde.",
                 "Você ainda pode",
                 "voltar."),
"43:6562": L("43:6562",
                  "Não acho os",
                  "POKéMON fofos?",
                  "Vou achar os meus",
                 "fofos, depois que",
                 "derrotarem os",
                 "seus!"),
    "43:65b3": L("43:65b3",
                 "Ah, não! Eles são",
                 "tão inúteis!"),
    "43:65cf": L("43:65cf",
                 "Eu amo a minha",
                 "beleza!",
                 "Quem liga para",
                 "os POKéMON?"),
    "43:6641": L("43:6641",
                 "Hmmm…",
                 "Os grandes planos",
                 "têm percalços."),
    "43:6669": L("43:6669",
                 "Você acredita",
                 "mesmo que pode",
                 "parar a TEAM?"),
    "43:6a0d": L("43:6a0d",
                 "Oi, garoto.",
                 "Lembra de mim do",
                 "HIDEOUT em",
                 "MAHOGANY TOWN?",
                 "Eu perdi lá, mas",
                 "agora não perco."),
    "43:6a70": L("43:6a70",
                 "Isso não pode",
                 "ser verdade!",
                 "Lutei duro, mas",
                 "ainda perdi…"),
    "43:6aaa": L("43:6aaa",
                 "{PLAYER}, não é?",
                 "Um pirralho como",
                 "você não vai",
                 "apreciar a",
                 "magnificência da",
                 "TEAM ROCKET.",
                 "Que pena. Eu",
                 "admiro seu poder."),

    # ---------------- banco 46 ----------------
    "46:5af0": L("46:5af0",
                 "Hyuck-hyuck-hyuck!",
                 "Lembro de você!",
                 "Você me pegou",
                 "no esconderijo!"),
    "46:5b34": L("46:5b34",
                 "Hyuck-hyuck-hyuck!",
                 "Então é assim?"),
    "46:5b57": L("46:5b57",
                 "Hyuck-hyuck-hyuck!",
                 "Foi demais!",
                 "Vou me lembrar!"),

    # ---------------- banco 47 ----------------
    "47:46c4": L("47:46c4", "{PLAYER} recebeu", "TM24."),

    # ---------------- banco 48 ----------------
    "48:486a": L("48:486a",
                 "Oh… É algo que",
                 "gosto de fazer…",
                 "Tudo bem. Venha",
                 "quando quiser."),
    "48:5667": L("48:5667",
                 "WOOSTER: Gugyoo…"),
    "48:5c11": L("48:5c11",
                 "Existem várias",
                 "ilhas entre",
                 "aqui e OLIVINE.",
                 "Uma criatura",
                 "mítica do mar",
                 "vive lá."),

    # ---------------- banco 49 ----------------
    "49:542e": L("49:542e",
                 "Deixe-me batalhar",
                 "com o POKéMON que",
                 "acabei de pegar!"),
    "49:545a": L("49:545a",
                 "Sou bom pescador,",
                 "mas péssimo como",
                 "treinador de",
                 "POKéMON…"),
"49:549b": L("49:549b",
                  "Não perco como",
                  "pescador! Pesco",
                  "POKéMON todo dia"),
    "49:54cc": L("49:54cc",
                 "Não importa o que",
                 "faça, só pego os",
                 "mesmos POKé-",
                 "MON…"),
    "49:5503": L("49:5503",
                 "Minha linha está",
                 "toda embaraçada…"),
"49:551d": L("49:551d",
                  "Por que não pego",
                  "bons POKéMON?"),
    "49:553e": L("49:553e",
                 "Se um treinador vê",
                 "outro, ele tem",
                 "que fazer um",
                 "desafio. Esse",
                 "é o nosso",
                 "destino."),
    "49:5594": L("49:5594",
                 "Ufa…",
                 "Boa batalha."),
    "49:55a8": L("49:55a8",
                 "POKéMON e o dono",
                 "ficam fortes",
                 "com batalha",
                 "constante."),
    "49:55eb": L("49:55eb",
                 "O que aconteceu",
                 "com o GYARADOS",
                 "vermelho? Sumiu?",
                 "Droga. Vim",
                 "à toa?",
                 "Já sei, vamos",
                 "batalhar!"),
    "49:565e": L("49:565e",
                 "Pensando bem,",
                 "vi um BUTTERFREE",
                 "rosa."),

    # ---------------- banco 4a ----------------
    "4a:41b7": L("4a:41b7",
                 "Vai ser difícil",
                 "vencer na LEAGUE.",
                 "Preciso treinar",
                 "mais.",
                 "Ouvi dizer que a",
                 "ELITE FOUR é",
                 "mais difícil que",
                 "os LÍDERES de",
                 "GINÁSIO."),
    "4a:4246": L("4a:4246",
                 "Passando por",
                 "batalhas duras,",
                 "você ganha poder."),
    "4a:4276": L("4a:4276",
                 "Aaah! A vida é",
                 "tão difícil!"),
    "4a:4293": L("4a:4293",
                 "Para chegar à",
                 "LEAGUE POKéMON,",
                 "tem que atravessar",
                 "a VICTORY ROAD.",
                 "Mas a VICTORY ROAD",
                 "é difícil.",
                 "Quase ninguém",
                 "vai lá!"),
    "4a:430b": L("4a:430b",
                 "Já que você chegou",
                 "até aqui, deve ser",
                 "bom.",
                 "Vou dar nessa",
                 "batalha tudo o",
                 "que tenho!"),
    "4a:436c": L("4a:436c",
                 "Não! Eu não",
                 "acredito nisso!"),
    "4a:4386": L("4a:4386",
                 "Eu derrotei",
                 "oito LÍDERES,",
                 "então estava",
                 "confiante.",
                 "Vou ter que",
                 "me esforçar mais."),
    "4a:43e5": L("4a:43e5",
                 "Perdi para o",
                 "{RIVAL}.",
                 "Ele era muito",
                 "forte, mas…",
                 "Era como se ele",
                 "quisesse vencer",
                 "a qualquer custo.",
                 "Senti pena dos",
                 "POKéMON dele."),
    "4a:446e": L("4a:446e",
                 "POKéMON não são",
                 "armas de guerra."),
    "4a:4488": L("4a:4488",
                 "POKéMON são",
                 "valiosos parceiros",
                 "para a vida toda."),
    "4a:44b3": L("4a:44b3",
                 "Uau, olha todas",
                 "essas BADGES!",
                 "Impressionado.",
                 "Mas você não",
                 "se satisfaz só",
                 "coletando elas,",
                 "né?"),
    "4a:4527": L("4a:4527",
                 "Pessoas e POKéMON",
                 "crescem com suas",
                 "experiências.",
                 "Não fique parado",
                 "e acomodado."),
    "4a:4573": L("4a:4573",
                 "Estou me sentindo",
                 "ótimo hoje!",
                 "Sinto que poderia",
                 "vencer até",
                 "o CAMPEÃO!"),
    "4a:45bc": L("4a:45bc",
                 "Não! Não nesta",
                 "batalha!"),
    "4a:45d5": L("4a:45d5",
                 "Como na pesca,",
                 "em POKéMON está",
                 "tudo perdido se",
                 "você desistir."),
    "4a:48d8": L("4a:48d8",
                 "Você parece",
                 "bem forte.",
                 "Vamos batalhar!"),
    "4a:490a": L("4a:490a",
                 "Se você vencer",
                 "esta trilha dura,",
                 "a verdade será",
                 "revelada!",
                 "Heh, desculpa, só",
                 "queria dizer",
                 "algo legal."),
    "4a:497b": L("4a:497b",
                 "Hm? Você é bom,",
                 "não é?"),
    "4a:4997": L("4a:4997",
                 "Como eu pensei!"),
    "4a:49ab": L("4a:49ab",
                 "Um bom treinador",
                 "reconhece outros",
                 "bons treinadores."),
    "4a:49de": L("4a:49de",
                 "Você não deveria",
                 "subestimar os",
                 "POKéMON selvagens",
                 "destas bandas."),
    "4a:4a18": L("4a:4a18",
                 "Ah! Você é",
                 "forte demais!"),
    "4a:4a34": L("4a:4a34",
                 "Você é um garoto,",
                 "mas não dá para",
                 "te subestimar.",
                 "Nem de longe."),
    "4a:4a72": L("4a:4a72",
                 "É raro ver",
                 "alguém por aqui.",
                 "Você treina",
                 "sozinho?"),
    "4a:4ab3": L("4a:4ab3",
                 "Ah! Você é",
                 "realmente forte!"),
    "4a:4acd": L("4a:4acd",
                 "Analiso os POKéMON",
                 "antes e depois da",
                 "evolução.",
                 "Evoluir de verdade",
                 "deixa os POKéMON",
                 "mais fortes.",
                 "Mas as formas",
                 "evoluídas também",
                 "aprendem depois."),
    "4a:4b54": L("4a:4b54",
                 "Não diga nada!",
                 "Deixe-me adivinhar",
                 "o que você pensa.",
                 "Mmmmmmm…",
                 "Achei! Você está",
                 "no desafio da",
                 "LEAGUE POKéMON!"),
    "4a:4bc0": L("4a:4bc0",
                 "Você é demais!"),
    "4a:4bd1": L("4a:4bd1",
                 "Com sua força,",
                 "você vai bem na",
                 "LEAGUE.",
                 "É o que diz minha",
                 "premonição."),
    "4a:4c21": L("4a:4c21",
                 "Tweet! Tweet!",
                 "Tetweet!"),
    "4a:4c41": L("4a:4c41",
                 "BIRD KEEPERS, nós",
                 "imitamos assobios",
                 "para comandar",
                 "os POKéMON."),
    "4a:5141": L("4a:5141",
                 "Estou esperando",
                 "os POKéMON que",
                 "só aparecem de",
                 "dia."),
    "4a:55f0": L("4a:55f0",
                 "Acabei de perder,",
                 "vou procurar",
                 "mais POKéMON.",
                 "Espera! Você",
                 "parece fraco!",
                 "Vamos batalhar!"),
    "4a:5649": L("4a:5649",
                 "Ugh. Não tenho",
                 "mais POKéMON."),
    "4a:566a": L("4a:566a",
                 "Preciso ter",
                 "mais POKéMON para",
                 "batalhas.",
                 "Vou pegar mais",
                 "um pouco!"),
    "4a:56ae": L("4a:56ae",
                 "Você é um",
                 "treinador, certo?",
                 "Então você tem que",
                 "batalhar!"),
    "4a:56e5": L("4a:56e5",
                 "Estranho.",
                 "Eu venci antes."),
    "4a:5703": L("4a:5703",
                 "Virar um bom",
                 "treinador é",
                 "difícil.",
                 "Vou batalhar",
                 "com outras pessoas",
                 "para melhorar."),
    "4a:575e": L("4a:575e",
                 "Em vez de um",
                 "POKéMON, achei",
                 "um treinador!"),
    "4a:5789": L("4a:5789",
                 "Argh! Você é",
                 "forte demais!"),
    "4a:57a2": L("4a:57a2",
                 "Fiquei sem POKé",
                 "BALLS enquanto",
                 "capturava POKéMON",
                 "Devia ter trazido",
                 "mais…"),
    "4a:5b54": L("4a:5b54",
                 "Peguei um monte",
                 "de POKéMON. Vamos",
                 "batalhar com você"),
    "4a:5b90": L("4a:5b90",
                 "Você pode pegar",
                 "POKéMON mesmo se",
                 "você tiver seis.",
                 "Se pegar um, ele",
                 "vai para a sua",
                 "BOX",
                 "automaticamente."),

    # ---------------- banco 4b ----------------
    "4b:5fc3": L("4b:5fc3",
                 "Estou treinando",
                 "meu sopro de fogo"),
    "4b:5fe5": L("4b:5fe5",
                 "Ai! Queimei a",
                 "ponta do nariz!"),
    "4b:6009": L("4b:6009",
                 "A POKéMON March",
                 "no rádio atrai",
                 "POKéMON do mato."),
    "4b:6452": L("4b:6452", "{PLAYER} recebeu", "TM08."),
    "4b:65b7": L("4b:65b7",
                 "Vou ler os",
                 "seus pensamentos!"),
    "4b:65e8": L("4b:65e8",
                 "Eu seria forte",
                 "se pudesse saber",
                 "o que meu oponente",
                 "está pensando."),
    "4b:662a": L("4b:662a",
                 "Graças aos meus",
                 "estudos, encaro",
                 "qualquer POKéMON!"),
    "4b:665a": L("4b:665a",
                 "Ops! Erro de",
                 "cálculo?"),
    "4b:6674": L("4b:6674",
                 "Droga. Estudo 5",
                 "horas/dia também.",
                 "Há muita coisa",
                 "que não se aprende",
                 "só lendo livros."),

    # ---------------- banco 4c ----------------
    "4c:5d6a": L("4c:5d6a",
                 "Devia ter usado",
                 "a MOON STONE…"),
    "4c:5d8d": L("4c:5d8d",
                 "Você está fazendo",
                 "uma POKéDEX?",
                 "Uau, deve conhecer",
                 "alguns POKéMON",
                 "bem raros!",
                 "Posso ver?",
                 "Por favor?"),
}
