# -*- coding: utf-8 -*-
"""Lote 22 -- banco 44: as RUINS, o SLOWPOKE WELL, o LIGHTHOUSE e a JASMINE.

Junta quatro lugares que dividem o banco: as RUINS OF ALPH e o RESEARCH
CENTER, a caverna do MT.MORTAR, o poço dos SLOWPOKE com os ROCKET
GRUNTS, e o OLIVINE LIGHTHOUSE com o POKéMON doente.

Ficam no original: KURT, JASMINE, PROF.ELM, PROF.SILKTREE, TEAM ROCKET,
ROCKET GRUNT, SLOWPOKE, SLOWPOKETAILS, TAILS, ZUBAT, SUPERSONIC, ONIX,
FLY, LIGHTHOUSE, OLIVINE, CIANWOOD.
"""
from pt.estrutura import linhas as L

DIALOGO = {
    # ---------------- RUINS OF ALPH e o RESEARCH CENTER ----------------
    "44:41bd": L("44:41bd",
                 "O que você quer?",
                 "Estou estudando,",
                 "não me atrapalhe!"),
    "44:41ef": L("44:41ef",
                 "Desculpe…",
                 "Estou frustrado",
                 "pela nossa falta",
                 "de entendimento…"),
    "44:4228": L("44:4228",
                 "As RUÍNAS são de",
                 "uns 1500 anos",
                 "atrás.",
                 "Ninguém sabe quem",
                 "construiu.",
                 "Também não se sabe",
                 "se as estátuas de",
                 "POKéMON têm algum",
                 "significado.",
                 "É tudo um grande",
                 "mistério…"),
    "44:42c3": L("44:42c3", "Hmmm… Este é um", "lugar estranho."),
    "44:42e6": L("44:42e6", "Gosto de pensar", "aqui."),
    "44:4f1d": L("44:4f1d",
                 "É uma foto do",
                 "fundador do",
                 "CENTRO DE PESQUISA",
                 "PROF.SILKTREE."),

    # ---------------- a caverna ----------------
    "44:50bd": L("44:50bd",
                 "Muito bem, então!",
                 "Eu decidi.",
                 "Não vou sair daqui",
                 "até meus POKéMON",
                 "ficarem fortes!"),
    "44:5106": L("44:5106",
                 "Eu ando por toda",
                 "parte procurando",
                 "POKéMON.",
                 "Você também está",
                 "procurando?",
                 "Então você é meu",
                 "rival de coleção!"),
    "44:516c": L("44:516c", "Ugh. Meus pobres", "POKéMON…"),
    "44:5182": L("44:5182",
                 "Toda sexta dá para",
                 "ouvir rugidos de",
                 "POKéMON lá do",
                 "fundo da caverna."),
    "44:51c4": L("44:51c4",
                 "Uau! Que",
                 "surpresa!",
                 "Não esperava ver",
                 "ninguém aqui!"),
    "44:51ff": L("44:51ff", "Uau! Fui derrotado", "feio!"),
    "44:521a": L("44:521a",
                 "Fui enganado e",
                 "comprei uma SLOW-",
                 "POKETAIL.",
                 "Tenho pena do",
                 "pobre POKéMON."),
    "44:5266": L("44:5266",
                 "O SUPERSONIC dos",
                 "ZUBAT vive dei-",
                 "xando eu confuso.",
                 "Isso me irrita",
                 "muito mesmo!"),
    "44:52c0": L("44:52c0",
                 "No fim de semana",
                 "dá para ouvir",
                 "rugidos estranhos",
                 "lá no fundo."),
    "44:5300": L("44:5300",
                 "Com luz, caverna",
                 "não assusta.",
                 "Se você é forte,",
                 "POKéMON também",
                 "não assustam."),
    "44:534d": L("44:534d",
                 "É o fogo do meu",
                 "POKéMON que acende",
                 "esta caverna."),
    "44:54c4": L("44:54c4",
                 "Estou perdido faz",
                 "muito tempo…",
                 "Não me importo de",
                 "ficar aqui, mas",
                 "que fome!"),
    "44:5510": L("44:5510", "Veja só!", "Uma visita!"),
    "44:552e": L("44:552e", "Uahahah! Você é", "danado!"),
    "44:554c": L("44:554c",
                 "Eu moro aqui.",
                 "Você também pode,",
                 "se quiser.",
                 "Tem espaço de",
                 "sobra, sabe."),
    "44:559b": L("44:559b",
                 "Quem está aí?",
                 "Deixe eu e meus",
                 "POKéMON em paz!"),
    "44:55d2": L("44:55d2",
                 "Só eu e os meus",
                 "POKéMON. Estou",
                 "louco de alegria."),
    "44:5601": L("44:5601",
                 "Vim de tão longe",
                 "para fazer minha",
                 "pesquisa POKéMON.",
                 "Deixe eu mostrar",
                 "o que descobri",
                 "numa luta real!"),
    "44:5668": L("44:5668", "Você demonstrou", "em mim!"),
    "44:5681": L("44:5681",
                 "Devo reunir e",
                 "divulgar o que",
                 "descobri.",
                 "Quem sabe eu fique",
                 "famoso como o",
                 "PROF.ELM."),
    "44:5826": L("44:5826", "Você tem um", "estilo brilhante!"),
    "44:5841": L("44:5841",
                 "Seu estilo POKéMON",
                 "é impressionante",
                 "e colorido, sim.",
                 "Você só vai",
                 "melhorar!"),
    "44:5895": L("44:5895", "Estou treinando.", "Topa uma partida?"),
    "44:58b8": L("44:58b8", "Aah, não! Você é", "bom demais."),
    "44:58d9": L("44:58d9",
                 "Vou treinar",
                 "sozinho até eu",
                 "melhorar."),
    "44:5907": L("44:5907",
                 "Se o POKéMON que",
                 "eu gosto estivesse",
                 "lá, eu iria.",
                 "É o que um treina-",
                 "dor faz."),
    "44:5958": L("44:5958", "Prefiro fazer", "carinho neles!"),
    "44:597c": L("44:597c",
                 "Uma vez por semana",
                 "um POKéMON vem",
                 "até a beira.",
                 "Eu queria ver",
                 "esse POKéMON…"),

    # ---------------- o SLOWPOKE WELL ----------------
    "44:5c1d": L("44:5c1d",
                 "KURT: Muito bem,",
                 "{PLAYER}!",
                 "A TEAM ROCKET",
                 "foi embora.",
                 "Minhas costas",
                 "melhoraram. Vamos",
                 "sair daqui."),
    "44:5c78": L("44:5c78",
                 "Droga! Eu estava",
                 "de guarda lá em",
                 "cima quando um",
                 "velho gritou.",
                 "Me assustou tanto",
                 "que eu caí aqui",
                 "embaixo.",
                 "Acho que vou",
                 "descontar a raiva",
                 "em você!"),
    "44:5d1f": L("44:5d1f", "Arrgh! Hoje NÃO é", "o meu dia!"),
    "44:5d3b": L("44:5d3b",
                 "Sim, a gente vem",
                 "cortando o rabo",
                 "dos SLOWPOKE e",
                 "vendendo elas.",
                 "Tudo o que fazemos",
                 "é por lucro.",
                 "Isso mesmo!",
                 "Somos a TEAM",
                 "ROCKET, e fazemos",
                 "tudo por grana!"),
    "44:5dde": L("44:5dde",
                 "O que você quer?",
                 "Se atrapalhar o",
                 "nosso trabalho,",
                 "não terá piedade!"),
    "44:5e23": L("44:5e23",
                 "Você foi bem hoje",
                 "pirralho, mas es-",
                 "pere a próxima!"),
    "44:5e54": L("44:5e54",
                 "É, a TEAM ROCKET",
                 "foi desfeita",
                 "há três anos.",
                 "Mas continuamos",
                 "com as atividades",
                 "escondidos.",
                 "Agora divirta-se",
                 "vendo a gente",
                 "aprontar!"),
    "44:5ee5": L("44:5ee5",
                 "Parar de tirar",
                 "SLOWPOKETAILS?",
                 "Se obedecêssemos,",
                 "a fama da TEAM",
                 "ROCKET acabava!"),
    "44:5f37": L("44:5f37", "Simplesmente…", "Forte demais…"),
    "44:5f4a": L("44:5f4a",
                 "A gente precisa da",
                 "grana, mas vender",
                 "SLOWPOKETAILS?",
                 "É duro ser um",
                 "ROCKET GRUNT!"),
    "44:5f9b": L("44:5f9b",
                 "Parar as TAILS?",
                 "É, tente vencer",
                 "todos nós então!"),
    "44:5fd3": L("44:5fd3", "Seu pirralho!"),
    "44:5fe5": L("44:5fe5",
                 "SLOWPOKETAILS",
                 "crescem rápido!",
                 "Qual o problema",
                 "de vender elas?"),

    # ---------------- o OLIVINE LIGHTHOUSE ----------------
    "44:64af": L("44:64af",
                 "Que força!",
                 "Que tal você",
                 "navegar os mares",
                 "comigo?"),
    "44:64e9": L("44:64e9", "Hm? Aqui não é", "lugar de brincar."),
    "44:650c": L("44:650c", "Ah! Dá para ver", "que você é sério."),
    "44:652f": L("44:652f",
                 "Lá em cima tem um",
                 "POKéMON que mantém",
                 "o farol aceso.",
                 "Mas ouvi que ele",
                 "está doente e",
                 "não sara com",
                 "remédio comum."),
    "44:666e": L("44:666e", "Você se importa", "de verdade…"),
    "44:6689": L("44:6689",
                 "Como diabos se",
                 "sobe aqui?",
                 "Quero visitar o",
                 "POKéMON doente,",
                 "mas não consigo",
                 "chegar lá…"),
    "44:66dd": L("44:66dd",
                 "Marinheiros são",
                 "bons e fortes.",
                 "E você?"),
    "44:670f": L("44:670f", "Você é bom e", "forte também…"),
    "44:672e": L("44:672e",
                 "Toda vez que volto",
                 "a OLIVINE, eu",
                 "visito o GINÁSIO.",
                 "O tipo de POKéMON",
                 "da LÍDER mudou",
                 "sem que eu",
                 "percebesse."),
    "44:679e": L("44:679e",
                 "Viajo o mundo",
                 "para treinar meus",
                 "POKéMON. Quero",
                 "batalhar com você"),
    "44:67e1": L("44:67e1", "…suspiro… Preciso", "treinar mais…"),
    "44:6801": L("44:6801",
                 "A JASMINE usava",
                 "POKéMON de pedra",
                 "como o ONIX."),
    "44:690f": L("44:690f", "Eu também não", "consigo sorrir…"),
    "44:692e": L("44:692e",
                 "Falando em doente,",
                 "ouvi que tem",
                 "uma boa farmácia",
                 "em CIANWOOD."),
    "44:696f": L("44:696f",
                 "A JASMINE é a",
                 "LÍDER daqui.",
                 "Pretendo trazer",
                 "ela de volta.",
                 "É melhor ninguém",
                 "atrapalhar!"),
    "44:69d5": L("44:69d5", "Aaai! POKéMON!"),
    "44:69e6": L("44:69e6",
                 "Certo. Qualquer um",
                 "ficaria preocupado",
                 "se o POKéMON dele",
                 "estivesse ferido.",
                 "Vou rezar pelo",
                 "POKéMON daqui,",
                 "para a JASMINE",
                 "voltar ao GINÁSIO"),
    "44:6b3a": L("44:6b3a", "Uau, uau. Você é", "arrasador!"),
    "44:6b5b": L("44:6b5b",
                 "Um LÍDER não é só",
                 "questão de ser",
                 "forte. Um LÍDER",
                 "também precisa ter",
                 "compaixão."),
    "44:6bb0": L("44:6bb0",
                 "Estamos bem alto",
                 "aqui. Meus",
                 "POKéMON pássaro",
                 "em plena forma."),
    "44:6beb": L("44:6beb", "Opa…Eles caíram…"),
    "44:6bff": L("44:6bff",
                 "Meu POKéMON apren-",
                 "deu a usar FLY em",
                 "CIANWOOD.",
                 "Bom, como eu perdi",
                 "vou usar FLY para",
                 "cruzar o mar…"),
}
