# -*- coding: utf-8 -*-
"""Lote 8b -- LAKE OF RAGE, o encontro com o LANCE e a casa do MAGIKARP.

Traduzido a partir do ingles original.  Chave = ponteiro da ROM USA.
Escrito com `linhas()` -- ver pt/estrutura.py.

Ficam no original: LANCE, WESLEY, GYARADOS, MAGIKARP, RED SCALE,
BLACKBELT, ROD, LAKE OF RAGE, GYARADOS LAKE, FISHING GURU.
"""
from pt.estrutura import linhas as L

DIALOGO = {
    # ---------------- Lake of Rage ----------------
    "49:5063": L("49:5063",
                 "Este lago está",
                 "cheio de GYARADOS",
                 "e mais nada…",
                 "Então os MAGIKARP",
                 "estão sendo força-",
                 "dos a evoluir…"),
    "49:50c0": L("49:50c0",
                 "Você veio aqui",
                 "por causa dos",
                 "boatos?",
                 "Você é {PLAYER}?",
                 "Sou LANCE, um",
                 "treinador igual.",
                 "Ouvi uns boatos",
                 "e vim aqui para",
                 "investigar…",
                 "Vi o jeito que",
                 "você batalhou,",
                 "{PLAYER}.",
                 "Dá para ver que",
                 "você é treinador",
                 "de bastante",
                 "habilidade.",
                 "Se não se importa,",
                 "quer me ajudar a",
                 "investigar?"),
    "49:51d2": L("49:51d2",
                 "LANCE: Excelente!",
                 "Parece que estão",
                 "forçando os",
                 "MAGIKARP do LAKE",
                 "a evoluir.",
                 "Uma transmissão de",
                 "rádio misteriosa",
                 "vinda de MAHOGANY",
                 "é a causa.",
                 "Espero por você,",
                 "{PLAYER}."),
    "49:527d": L("49:527d",
                 "Ah… Bem, se você",
                 "mudar de ideia,",
                 "me ajude."),
    "49:52b1": L("49:52b1",
                 "LANCE: Hm? Você",
                 "vai me ajudar?"),
    "49:52d7": L("49:52d7", "GYARADOS: Gyasha!"),
    "49:52eb": L("49:52eb",
                 "{PLAYER} conseguiu",
                 "uma RED SCALE."),
    "49:5304": L("49:5304",
                 "Os GYARADOS estão",
                 "furiosos!",
                 "É mau agouro!"),
    "49:532d": L("49:532d",
                 "Hahah! Os MAGIKARP",
                 "estão mordendo!"),
    "49:5350": L("49:5350",
                 "Ouvi que este lago",
                 "foi feito por",
                 "GYARADOS em fúria",
                 "Será que tem",
                 "alguma ligação",
                 "com esse surto",
                 "todo de agora?"),
    "49:53c7": L("49:53c7",
                 "Meus olhos me",
                 "enganaram? Eu vi",
                 "um GYARADOS ver-",
                 "melho no LAKE…",
                 "Mas eu achava que",
                 "GYARADOS eram",
                 "azuis, não?"),

    # ---------------- WESLEY, o irmao de quarta-feira ----------------
    "49:5690": L("49:5690",
                 "WESLEY: Olá, como",
                 "vai você?",
                 "Já que hoje é",
                 "quarta-feira,",
                 "sou o WESLEY da",
                 "quarta."),
    "49:56e9": L("49:56e9",
                 "Prazer em te",
                 "conhecer. Aceite",
                 "uma lembrança."),
    "49:5717": L("49:5717",
                 "WESLEY: BLACKBELT",
                 "aumenta a força",
                 "de golpes lutador"),
    "49:5750": L("49:5750",
                 "WESLEY: Se me",
                 "achou, deve ter",
                 "conhecido meus",
                 "irmãos e irmãs.",
                 "Ou foi só",
                 "sorte sua?"),
    "49:57b5": L("49:57b5",
                 "WESLEY: Hoje não",
                 "é quarta-feira.",
                 "Que pena."),

    # ---------------- Placas ----------------
    "49:57e3": L("49:57e3",
                 "LAKE OF RAGE,",
                 "também chamado de",
                 "GYARADOS LAKE."),
    "49:580f": L("49:580f",
                 "CASA DO",
                 "FISHING GURU"),

    # ---------------- Casa do MAGIKARP ----------------
    "53:5704": L("53:5704",
                 "O LAKE OF RAGE é",
                 "na verdade uma",
                 "cratera feita por",
                 "GYARADOS em fúria",
                 "A cratera encheu",
                 "de água de chuva",
                 "e assim nasceu",
                 "o LAKE.",
                 "É a história que",
                 "veio do tataravô",
                 "do tataravô do",
                 "meu vovô.",
                 "Antigamente dava",
                 "para pescar",
                 "MAGIKARP animados",
                 "ali, mas…",
                 "Eu não entendo o",
                 "que está havendo."),
    "53:5823": L("53:5823",
                 "O LAKE não está",
                 "normal desde que",
                 "aqueles homens de",
                 "preto chegaram."),
    "53:5866": L("53:5866",
                 "O LAKE OF RAGE",
                 "voltou ao normal.",
                 "Os MAGIKARP",
                 "voltaram.",
                 "Ainda posso ver",
                 "meu sonho de achar",
                 "o maior MAGIKARP",
                 "do mundo.",
                 "Você tem uma ROD?",
                 "Se tiver, por",
                 "favor me ajude."),
    "53:5914": L("53:5914",
                 "Ah, você tem um",
                 "MAGIKARP! Vamos",
                 "ver o tamanho",
                 "desse bichinho."),
    "53:594d": L("53:594d",
                 "Uau! Este aqui é",
                 "excepcional!",
                 "Tiro o chapéu",
                 "para você!",
                 "Leve isto de",
                 "lembrança!"),
    "53:5999": L("53:5999",
                 "O recorde é o que",
                 "importa.",
                 "Considere isso",
                 "um bônus!"),
    "53:59d7": L("53:59d7",
                 "Uau! Este aqui é",
                 "excepcional!",
                 "…Eu queria poder",
                 "dizer isso, mas",
                 "já vi um maior",
                 "antes."),
    "53:5a32": L("53:5a32",
                 "O quê? Isso não é",
                 "um MAGIKARP!"),
    "53:5a4f": L("53:5a4f",
                 "Ah… Então você não",
                 "pegou um bom",
                 "o bastante?",
                 "Fica pra próxima."),
}
