# -*- coding: utf-8 -*-
"""Lote 15a -- treinadores das rotas: pescadores, gemeos e o telefone.

Banco 4b, achado pela varredura.  Sao as falas de ver/vencer/perder dos
treinadores que ficam pelas rotas -- o texto que o jogador le em cada
batalha aleatoria do caminho.

Ficam no original: SPROUT TOWER, VIOLET CITY, FALKNER, BADGE, ROD.
"""
from pt.estrutura import linhas as L

DIALOGO = {
    "4b:4335": L("4b:4335",
                 "Você já foi à",
                 "SPROUT TOWER?",
                 "Se você visitar",
                 "VIOLET CITY,",
                 "vão esperar que",
                 "treine lá.",
                 "É o básico para",
                 "treinadores. Vá à",
                 "SPROUT TOWER!"),

    # ---------------- os pescadores ----------------
    "4b:4636": L("4b:4636",
                 "Uau!",
                 "Você me fez perder",
                 "aquele peixe!"),
    "4b:4663": L("4b:4663",
                 "Calmo, concentrado",
                 "A essência da",
                 "pesca e dos POKé-",
                 "MON é a mesma."),
    "4b:46a4": L("4b:46a4",
                 "Sou um bom pesca-",
                 "dor, mas um",
                 "treinador melhor!"),
    "4b:46d3": L("4b:46d3",
                 "Tch! Quis apressar",
                 "as coisas…"),
    "4b:46f1": L("4b:46f1",
                 "Pescar é paixão",
                 "de uma vida.",
                 "POKéMON são amigos",
                 "de uma vida!"),
    "4b:4730": L("4b:4730",
                 "Só pego o mesmo",
                 "POKéMON sempre…",
                 "Talvez uma batalha",
                 "vire o jogo",
                 "para mim."),
    "4b:477f": L("4b:477f",
                 "Nada dá certo",
                 "para mim agora…"),
    "4b:47a4": L("4b:47a4",
                 "Como o cara do",
                 "meu lado pega",
                 "POKéMON bons?"),
    "4b:47d4": L("4b:47d4",
                 "Heh, estou com",
                 "sorte hoje. Que",
                 "tal lutar, moço?"),
    "4b:4807": L("4b:4807",
                 "Ufa. Não tive",
                 "sorte dessa vez."),
    "4b:4826": L("4b:4826",
                 "Você precisa de",
                 "uma ROD boa se",
                 "quiser pegar",
                 "POKéMON bons."),
    "4b:4863": L("4b:4863",
                 "Meus POKéMON?",
                 "Recém-pescados!"),
    "4b:4886": L("4b:4886",
                 "POKéMON recém-",
                 "pegos não são",
                 "páreo para os bem",
                 "criados."),

    # ---------------- treinadores do mato ----------------
    "4b:48c2": L("4b:48c2",
                 "Nunca vi você",
                 "por aqui antes.",
                 "Então você se acha",
                 "bem durão?"),
    "4b:4916": L("4b:4916",
                 "Vou tentar ser o",
                 "melhor com os",
                 "meus favoritos.",
                 "Não uso os mesmos",
                 "POKéMON fortes que",
                 "todo mundo usa."),
    "4b:497c": L("4b:497c",
                 "Achei uns POKéMON",
                 "bons ali no",
                 "mato!",
                 "Acho que eles vão",
                 "dar conta!"),
    "4b:49bf": L("4b:49bf",
                 "Droga. Achei que",
                 "ia ganhar."),
    "4b:49dd": L("4b:49dd",
                 "O mato está cheio",
                 "de coisa grudenta"),
    "4b:4a02": L("4b:4a02",
                 "Aquele olhar…",
                 "É intrigante."),
    "4b:4a20": L("4b:4a20",
                 "Hmmm. Que",
                 "decepção."),
    "4b:4a3e": L("4b:4a3e",
                 "Se não quiser",
                 "batalhar, evite",
                 "olhar nos olhos."),

    # ---------------- a moca no telefone ----------------
    "4b:4a73": L("4b:4a73",
                 "Aham. É, e",
                 "sabe como é…",
                 "Como? Batalhar?",
                 "Estou ao telefone",
                 "Ah, tá bom. Mas",
                 "seja rápido."),
    "4b:4ad2": L("4b:4ad2",
                 "Vai com calma!",
                 "Que maldade!"),
    "4b:4aed": L("4b:4aed",
                 "E eu estava numa",
                 "boa conversa."),

    # ---------------- quem reconhece a BADGE ----------------
    "4b:4b0c": L("4b:4b0c",
                 "Essa BADGE! É de",
                 "VIOLET CITY!",
                 "Venceu o FALKNER?"),
    "4b:4b41": L("4b:4b41",
                 "Eu sei quais são",
                 "minhas fraquezas."),
}
