# -*- coding: utf-8 -*-
"""Lote 15b -- mais treinadores de rota: HIKERS, colegiais e as irmas.

Banco 4b.  Primeiro lote gerado por `tools/pendentes.py`, que compara as
caudas contra o `dialogo.json` inteiro em vez de so contra o que falta --
o filtro anterior deixava passar a cauda assim que a fala-mae era
traduzida.

Ficam no original: HIKERS, DAY-CARE, GYM/GINÁSIO conforme o glossario,
VIOLET CITY, e os nomes IRENE, JENN, KATE.
"""
from pt.estrutura import linhas as L

DIALOGO = {
    "4b:4b61": L("4b:4b61",
                 "Eu devia treinar",
                 "de novo no GINÁSIO",
                 "de VIOLET CITY."),
    "4b:4b92": L("4b:4b92",
                 "Os pescadores",
                 "gritaram comigo",
                 "por amolar eles…"),

    # ---------------- os HIKERS ----------------
    "4b:4fab": L("4b:4fab",
                 "(Eu vim pelo",
                 "túnel, mas ainda",
                 "tenho energia",
                 "de sobra."),
    "4b:4ff1": L("4b:4ff1",
                 "Uau, garoto! Você",
                 "tem mais gás."),
    "4b:5011": L("4b:5011",
                 "Nós HIKERS somos",
                 "melhores nas",
                 "montanhas."),

    # ---------------- os colegiais ----------------
    "4b:530f": L("4b:530f", "O que aconteceu?"),
    "4b:531f": L("4b:531f",
                 "Vou treinar ainda",
                 "mais forte.",
                 "Afinal, quero",
                 "virar LÍDER de",
                 "GINÁSIO."),
    "4b:536c": L("4b:536c",
                 "Sou o melhor da",
                 "turma em POKéMON."),
    "4b:538e": L("4b:538e",
                 "Não! Tem treina-",
                 "dores melhores…"),
    "4b:53b0": L("4b:53b0",
                 "Me esforço para",
                 "ser o destaque",
                 "da minha turma."),

    # ---------------- o DAY-CARE ----------------
    "4b:53e2": L("4b:53e2",
                 "Tenho confiança",
                 "na minha forma",
                 "de criar POKéMON.",
                 "Quer ver?"),
    "4b:541a": L("4b:541a",
                 "Eu não fiz um",
                 "trabalho bom?"),
    "4b:5439": L("4b:5439",
                 "Talvez eu devesse",
                 "deixar um no DAY-",
                 "CARE.",
                 "O que eu faço?"),
    "4b:5473": L("4b:5473",
                 "Você é treinador?",
                 "Vamos fazer uma",
                 "batalha de treino"),
    "4b:54a4": L("4b:54a4",
                 "Ah, não! Eu não",
                 "consigo ganhar…"),
    "4b:54be": L("4b:54be",
                 "Você é forte",
                 "demais para ser",
                 "meu parceiro."),
    "4b:559c": L("4b:559c",
                 "Acabei de pegar",
                 "meu POKéMON de",
                 "volta no DAY-CARE",
                 "Vamos ver o quanto",
                 "ele ficou forte!"),
    "4b:55e7": L("4b:55e7",
                 "Por que termina",
                 "assim?"),
    "4b:5602": L("4b:5602",
                 "Meu POKéMON sabia",
                 "golpes que eu nem",
                 "sabia que tinha.",
                 "Isso me confundiu",
                 "demais!"),

    # ---------------- as irmas da praia ----------------
    "4b:5649": L("4b:5649",
                 "IRENE: Aaaai!",
                 "Um menino achou!"),
    "4b:5669": L("4b:5669",
                 "IRENE: Ooooh!",
                 "Ele é forte!"),
    "4b:5688": L("4b:5688",
                 "IRENE: Minha irmã",
                 "KATE vai te pegar",
                 "por isso!"),
    "4b:56b6": L("4b:56b6",
                 "IRENE: Esta praia",
                 "não é ótima?",
                 "É o nosso refúgio",
                 "secreto!"),
    "4b:56f4": L("4b:56f4",
                 "JENN: Não dá para",
                 "vencer a IRENE e",
                 "ficar impune!"),
    "4b:5722": L("4b:5722",
                 "JENN: Me desculpe,",
                 "IRENE! Maninha!"),
    "4b:573f": L("4b:573f",
                 "JENN: Não se ache",
                 "demais! Minha irmã",
                 "KATE é durona!"),
}
