# -*- coding: utf-8 -*-
"""Lote 19 -- banco 4f: rotas de Kanto, os colegiais e os videntes.

Ficam no original: SQUIRTLE, CHARMANDER, BULBASAUR, PIKACHU, ONIX, FLY,
HM, ROD, ROCK TUNNEL, POWER PLANT, KANTO, LAVENDER RADIO TOWER, BADGES.
"""
from pt.estrutura import linhas as L

DIALOGO = {
    # ---------------- os professores ----------------
    "4f:40a6": L("4f:40a6",
                 "Antes de virar",
                 "professor, eu",
                 "esquecia muita",
                 "coisa."),
    "4f:40e4": L("4f:40e4",
                 "Nos dias de sol,",
                 "acho que as cri-",
                 "anças prefeririam",
                 "brincar no pátio",
                 "a estudar na",
                 "sala de aula."),
    "4f:414c": L("4f:414c", "Eu não queria", "perder…"),
    "4f:4163": L("4f:4163",
                 "Estudar é impor-",
                 "tante, mas se",
                 "exercitar também."),

    # ---------------- os colegiais ----------------
    "4f:419c": L("4f:419c",
                 "Espera. Preciso",
                 "ligar pra mamãe"),
    "4f:41be": L("4f:41be", "Desculpe, mãe!", "Eu apanhei!"),
    "4f:41d9": L("4f:41d9",
                 "Minha mãe se",
                 "preocupa demais",
                 "eu tenho que ligar",
                 "toda hora."),
    "4f:421d": L("4f:421d", "Vamos batalhar.", "Não vou perder!"),
    "4f:4238": L("4f:4238", "Esqueci de fazer", "a lição!"),
    "4f:4255": L("4f:4255",
                 "Sayonara! Acabei",
                 "de aprender isso",
                 "na aula japonesa"),
    "4f:428a": L("4f:428a",
                 "Estamos em excur-",
                 "são na LAVENDER",
                 "RADIO TOWER para",
                 "estudos sociais."),
    "4f:42cc": L("4f:42cc", "Você é forte", "demais!"),
    "4f:42e3": L("4f:42e3",
                 "Cansei de andar.",
                 "Preciso de uma",
                 "pausa."),
    "4f:4313": L("4f:4313", "Aula favorita?", "Educação física!"),
    "4f:432e": L("4f:432e", "Ah, não!", "Como eu perdi?"),
    "4f:4349": L("4f:4349",
                 "Se POKéMON fosse",
                 "matéria na escola,",
                 "eu era o melhor!"),

    # ---------------- os treinadores de passaro ----------------
    "4f:449e": L("4f:449e",
                 "SQUIRTLE, CHARMAN-",
                 "DER e BULBASAUR…",
                 "Acho que é uma boa",
                 "mistura."),
    "4f:44e8": L("4f:44e8",
                 "Meu sonho é voar",
                 "com meu amado",
                 "POKéMON pássaro."),
    "4f:4517": L("4f:4517",
                 "Posso sonhar, mas",
                 "nunca vou voar…"),
    "4f:453a": L("4f:453a",
                 "Você tem POKéMON",
                 "que sabem o golpe",
                 "FLY, não tem? Que",
                 "inveja."),
    "4f:457a": L("4f:457a",
                 "Você batalhou com",
                 "todos do GINÁSIO?"),
    "4f:45a0": L("4f:45a0", "Nossa! Forte", "demais para mim!"),
    "4f:45bd": L("4f:45bd",
                 "Se você tem BADGES",
                 "de KANTO, elas",
                 "ajudam nas lutas",
                 "por link."),

    # ---------------- o rei e a gangue do PIKACHU ----------------
    "4f:46c7": L("4f:46c7",
                 "Como… Como ousa",
                 "zombar da realeza"),
    "4f:46e8": L("4f:46e8",
                 "Todo mundo não",
                 "sonha um dia ser",
                 "um rei?"),
    "4f:4714": L("4f:4714",
                 "Nihihi! Quer",
                 "batalhar com a",
                 "minha gangue?"),
    "4f:4754": L("4f:4754",
                 "Você parece ter",
                 "muitos POKéMON,",
                 "mas PIKACHU ainda",
                 "é o melhor."),
    "4f:4796": L("4f:4796",
                 "Agilidade é o",
                 "ponto forte dos",
                 "POKéMON pássaro."),
    "4f:47c2": L("4f:47c2",
                 "Você me venceu na",
                 "velocidade…"),
    "4f:47e0": L("4f:47e0",
                 "Seus POKéMON são",
                 "muito bem",
                 "treinados."),
    "4f:4809": L("4f:4809",
                 "Olhe os meus POKé-",
                 "MON. Veja a cor",
                 "e a plumagem",
                 "deles."),
    "4f:484e": L("4f:484e", "Droga!", "Não foi bastante!"),
    "4f:4867": L("4f:4867",
                 "Se escovar eles,",
                 "POKéMON ficam bem"),

    # ---------------- os geologos ----------------
    "4f:488b": L("4f:488b",
                 "Eu devia ir ao",
                 "ROCK TUNNEL pegar",
                 "um ONIX."),
    "4f:48c7": L("4f:48c7",
                 "O relevo parece",
                 "que não muda",
                 "nunca.",
                 "Mas ele muda sim,",
                 "aos pouquinhos,",
                 "com o tempo."),

    # ---------------- os pescadores de KANTO ----------------
    "4f:4aa3": L("4f:4aa3",
                 "Não tenho paciên-",
                 "cia para pescar…"),
    "4f:4ac2": L("4f:4ac2",
                 "Fico tão à vontade",
                 "pescando e ouvindo",
                 "uma música no",
                 "meu rádio."),
    "4f:4b0b": L("4f:4b0b",
                 "Meu rádio idiota",
                 "me distraiu!"),
    "4f:4b2b": L("4f:4b2b",
                 "Você já ouviu as",
                 "rádios de KANTO?",
                 "A variedade aqui",
                 "é boa."),
    "4f:4b74": L("4f:4b74",
                 "O que é mais",
                 "importante no",
                 "nosso dia a dia?"),
    "4f:4ba5": L("4f:4ba5", "A resposta vem", "logo depois!"),
    "4f:4bc4": L("4f:4bc4",
                 "Eu acho que a",
                 "eletricidade é o",
                 "mais importante",
                 "do nosso dia.",
                 "Se não fosse,",
                 "ninguém teria",
                 "feito tanto",
                 "alarde quando a",
                 "POWER PLANT",
                 "parou de vez."),
    "4f:4c6b": L("4f:4c6b", "Você lembra?"),
    "4f:4c7d": L("4f:4c7d", "Lembra mesmo?"),
    "4f:4c8f": L("4f:4c8f",
                 "O puxão que você",
                 "sente na ROD",
                 "quando fisga um",
                 "POKéMON…",
                 "É a melhor",
                 "sensação para um",
                 "pescador como eu."),

    # ---------------- o resto ----------------
    "4f:4e25": L("4f:4e25", "Hã? Como isso", "aconteceu?"),
    "4f:4e40": L("4f:4e40",
                 "Lutei limpo e com",
                 "honra.",
                 "Não me arrependo",
                 "de nada."),
    "4f:4e81": L("4f:4e81",
                 "Coça e faz cócega",
                 "um pouco quando",
                 "ando de shorts",
                 "no mato."),
    "4f:4ebf": L("4f:4ebf", "Aiaaai!", "Fui pisoteado!"),
    "4f:4ed8": L("4f:4ed8",
                 "Vou pegar mais",
                 "POKéMON ali",
                 "no mato."),

    # ---------------- os videntes ----------------
    "4f:4f09": L("4f:4f09",
                 "…",
                 "Perdi de olhos",
                 "fechados…"),
    "4f:4f2f": L("4f:4f2f",
                 "Eu consigo ver…",
                 "Tudo o que há",
                 "para ver em você…"),
    "4f:4f5b": L("4f:4f5b",
                 "Não previ a sua",
                 "força…"),
    "4f:4f7a": L("4f:4f7a",
                 "Força na convic-",
                 "ção…",
                 "Você é forte por-",
                 "que acredita nos",
                 "seus POKéMON."),
}
