# -*- coding: utf-8 -*-
"""Lote 32: falas de KANTO (MISTY, POWER PLANT, EARL e o Bug-Catching Contest).

Bancos 50, 53, 54, 55 e 56: o trecho extraido em trans32.json, em ingles
original do jogo.  Ficam no original os nomes proprios (cidades, rotas,
cavernas, itens e golpes), os sinais de rua e as falas do CONCURSO de
POKéMON com {STRBUF}.  Os "fragmentos" (caudas) preservam a contagem de
linhas e os separadores do ingles para continuarem o texto da fala-mae.
"""
from pt.estrutura import linhas as L

DIALOGO = {
    "50:437d": L("50:437d",
        "ROUTE 9",
        "CERULEAN CITY -",
        "ROCK TUNNEL"),
    "50:443b": L("50:443b",
        "Ei, menino! Eu",
        "da TEAM ROCKET",
        "sou tipo cara!",
        "De outro país",
        "vim, treinador",
        "número um, eu!",
        "Pensei eu, se",
        "a energia parar,",
        "pânico grande",
        "para daqui gente!",
        "Segredo meu",
        "missão é, então",
        "não falo!",
        "Mas! Se batalha",
        "ganhar de mim,",
        "sou homem e meu",
        "segredo conto.",
        "Ei, garoto!",
        "Batalha começar!"),
    "50:4574": L("50:4574",
        "Aiii! Não, não,",
        "não, não acredito",
        "em mim!",
        "Muito forte",
        "você é! Eu não",
        "te aguento!"),
    "50:45cd": L("50:45cd",
        "OK. Contar meu",
        "segredo vou.",
        "MACHINE PART",
        "eu roubei,",
        "no GYM de",
        "CERULEAN escondi.",
        "Na água pus.",
        "Procure no",
        "meio da água",
        "do GYM.",
        "Garoto, mas",
        "não me esqueça!",
        "Ganhar de você",
        "a TEAM ROCKET",
        "vai. De JOHTO",
        "virão meus",
        "amigos. E a",
        "vingança virá!"),
    "50:46f3": L("50:46f3",
        "…",
        "O quê? A TEAM",
        "ROCKET tchau",
        "tchau? Acabou,",
        "disse você?",
        "Oh, não! O que",
        "faço agora",
        "comigo?"),
    "50:48e7": L("50:48e7",
        "MISTY: Aii!",
        "Por que você",
        "tinha de vir",
        "agora?",
        "Sabe como",
        "chamam gente",
        "como você?",
        "Praga! Ouviu",
        "direito? Praga!",
        "…",
        "…Oh? Essas BADGES",
        "você tem… São",
        "BADGES de JOHTO?",
        "Se tem oito,",
        "deve ser bom.",
        "Certo, então.",
        "Vem ao GYM.",
        "Vou adorar",
        "batalhar contigo!",
        "Sou a MISTY, a",
        "LÍDER do GYM",
        "de CERULEAN."),
    "50:4d1c": L("50:4d1c",
        "Você enfrentou",
        "mais uma batalha",
        "do que esperava,",
        "mas venceu.",
        "Como prometido,",
        "ganhou um prêmio."),
    "50:4d7e": L("50:4d7e",
        "Mas depois de ver",
        "como você luta,",
        "quero ver como",
        "vou me sair.",
        "Que tal? Deixa eu",
        "lutar com você!"),
    "50:4dde": L("50:4dde",
        "Nunca tive uma",
        "batalha tão boa!"),
    "50:4e01": L("50:4e01",
        "Foi uma ótima",
        "batalha!",
        "Você e seu POKé-",
        "MON são mesmo",
        "fantásticos!"),
    "50:4e48": L("50:4e48",
        "SEA COTTAGE",
        "BILL'S HOUSE"),
    "50:5124": L("50:5124",
        "MT.MOON SQUARE",
        "É só subir as",
        "escadas."),
    "50:5311": L("50:5311",
        "MT.MOON SQUARE",
        "É só subir as",
        "escadas."),
    "50:5675": L("50:5675",
        "Está trancado…"),
    "50:5682": L("50:5682",
        "O cartaz rasgado…",
        "Impossível",
        "ler…"),
    "50:571c": L("50:571c",
        "KANTO POWER PLANT"),
    "50:5831": L("50:5831",
        "ROUTE 10",
        "CERULEAN CITY -",
        "LAVENDER TOWN"),
    "50:8057": L("50:8057",
        "e",
        "rochas gigantes."),
    "50:8500": L("50:8500",
        "ssivo."),
    "50:9c4f": L("50:9c4f",
        "veio",
        "de volta?",
        "Eu vi uns caras de",
        "preto no LAKE OF",
        "RAGE…"),
    "50:9d00": L("50:9d00",
        " quando eles",
        "evoluem, mas",
        "aprendem golpes",
        "mais devagar."),
    "50:c500": L("50:c500",
        "es.",
        "Amanhã, as TIME",
        "CAPSULES vão",
        "funcionar nos",
        "POKéMON CENTERS.",
        "Preciso voltar",
        "pra GOLDENROD já,",
        "ver meus pais.",
        "Tchau!"),
    "50:cb00": L("50:cb00",
        "sou bom",
        "em POKéMON também"),
    "53:5ce1": L("53:5ce1",
        "Obrigado, senhor!"),
    "54:4005": L("54:4005",
        "Você está juntando",
        "BADGES de KANTO?"),
    "54:405a": L("54:405a",
        "Ouvi dizer que um",
        "sujeito esquisito",
        "está rondando.",
        "Não vou tolerar",
        "se ele acabar",
        "sendo ladrão."),
    "54:40c3": L("54:40c3",
        "Já fomos vítimas",
        "de assaltantes."),
    "54:414d": L("54:414d",
        "Meu marido vive",
        "feliz com o POKé-",
        "MON que ele ganhou",
        "em trocas."),
    "54:418a": L("54:418a",
        "Ah… Que alegria…"),
    "54:4218": L("54:4218",
        "A ROUTE 9 vai",
        "para o leste. A",
        "POWER PLANT fica",
        "no fim."),
    "54:4257": L("54:4257",
        "O MAGNET TRAIN",
        "anda a mais de",
        "540 km/h. Ele vai",
        "de KANTO a JOHTO",
        "em quase nenhum",
        "tempo.",
        "Isso aproxima",
        "JOHTO de você."),
    "54:4453": L("54:4453",
        "Upa! Eu desculpa!",
        "Você não machucou,",
        "tá?",
        "Eu muito ocupado.",
        "Sem tempo pra",
        "papear com você.",
        "Ruim pra mim se",
        "alguém me vê."),
    "54:44cc": L("54:44cc",
        "Ah não! Já viu",
        "me! Eu fiz um",
        "grande erro!"),
    "54:44fd": L("54:44fd",
        "Ei, você! Esquece",
        "que me viu, tá?",
        "Você não viu,",
        "nem ouviu nada,",
        "tá?",
        "Bye-bye, garoto!",
        "Tchau, tchau!"),
    "54:4568": L("54:4568",
        "Desculpe, saí",
        "por um tempo.",
        "MISTY, GYM LEADER"),
    "54:459a": L("54:459a",
        "Como a MISTY saiu,",
        "nós também.",
        "GYM TRAINERS"),
    "54:45cc": L("54:45cc",
        "MISTY: Eu já te",
        "esperava, praga!",
        "Pode ter muitas",
        "GYM BADGES de",
        "JOHTO, mas não",
        "vai me levar de",
        "bobeira!",
        "Meus POKéMON de",
        "água são",
        "durões!"),
    "54:4664": L("54:4664",
        "MISTY: Você é",
        "muito bom…",
        "Admito que você",
        "é habilidoso…",
        "Toma. É a",
        "CASCADEBADGE."),
    "54:46c0": L("54:46c0",
        "{PLAYER} recebeu",
        "a CASCADEBADGE."),
    "54:46da": L("54:46da",
        "MISTY: Existem",
        "muitos treinadores",
        "fortes em JOHTO?",
        "Como você, aliás?",
        "Vou viajar",
        "um dia e quero",
        "batalhar com",
        "treinadores bons."),
    "54:48ff": L("54:48ff",
        "E aí, futuro",
        "campeão!",
        "Como a MISTY",
        "saiu, fui me",
        "divertir também!",
        "He-he-he."),
    "54:4952": L("54:4952",
        "Uau, você mostrou",
        "como é durão.",
        "Como sempre, foi",
        "uma baita",
        "batalha!"),
    "54:4a25": L("54:4a25",
        "Você vai ver",
        "muitos por aí no",
        "caminho pro CAPE",
        "de CERULEAN.",
        "Eles querem ver",
        "como se saem",
        "contra outros",
        "treinadores."),
    "54:4a9e": L("54:4a9e",
        "A MISTY é a única",
        "na cidade que",
        "vence os caras",
        "do CAPE de",
        "CERULEAN."),
    "54:4b49": L("54:4b49",
        "Um CENTRO POKéMON",
        "perto de caverna?",
        "Isso é muito",
        "conveniente!"),
    "54:4b7e": L("54:4b7e",
        "O MANAGER da",
        "POWER PLANT quer",
        "achar um homem",
        "com POKéMON bom.",
        "Ele precisa de",
        "ajuda pra pegar",
        "de volta algo que",
        "foi roubado."),
    "54:4bf6": L("54:4bf6",
        "Ouvi que a TEAM",
        "ROCKET se reuniu",
        "de novo em JOHTO,",
        "mas se desfez.",
        "Eu não sabia",
        "de nada disso."),
    "54:4c64": L("54:4c64",
        "Quando você sai,",
        "dá pra ver o",
        "telhado de um",
        "prédio grande.",
        "Essa é a POWER",
        "PLANT."),
    "54:4e31": L("54:4e31",
        "Um ladrão invadiu",
        "a POWER PLANT…",
        "O que o mundo",
        "está virando?"),
    "54:4e73": L("54:4e73",
        "Acabei de saber",
        "de CERULEAN.",
        "Ao que parece,",
        "um sujeito",
        "estranho anda",
        "rondando por aí."),
    "54:4ed0": L("54:4ed0",
        "Posso pedir sua",
        "cooperação?"),
    "54:4ef3": L("54:4ef3",
        "Vamos ter que",
        "reforçar nossa",
        "segurança."),
    "54:4f20": L("54:4f20",
        "Alguém levou",
        "uma peça que é",
        "essencial para",
        "o gerador.",
        "Sem ela, o",
        "gerador novo",
        "não serve!"),
    "54:4f89": L("54:4f89",
        "O gerador está",
        "ligado e no ar.",
        "Está gerando",
        "eletricidade!"),
    "54:4fca": L("54:4fca",
        "Esta POWER PLANT",
        "tinha sido",
        "abandonada.",
        "Nós reativamos",
        "ela pra dar",
        "energia pro",
        "MAGNET TRAIN."),
    "54:5040": L("54:5040",
        "O gerador está",
        "rodando de novo!"),
    "54:505f": L("54:505f",
        "O MANAGER da",
        "POWER PLANT está",
        "logo à frente.",
        "Mas como alguém",
        "quebrou o gerador,",
        "ele ficou",
        "triste e",
        "furioso…"),
    "54:50d0": L("54:50d0",
        "Como o gerador",
        "foi consertado,",
        "o MANAGER está",
        "bem animado."),
    "54:5113": L("54:5113",
        "O MAGNET TRAIN",
        "gasta muita",
        "eletricidade.",
        "Não anda se o",
        "novo gerador",
        "não funciona."),
    "54:5176": L("54:5176",
        "Legal! Podemos",
        "finalmente pôr o",
        "MAGNET TRAIN",
        "de novo no ar!"),
    "54:51b5": L("54:51b5",
        "MANAGER: Eu vou",
        "explodir alguém!",
        "Quem se atreve",
        "a estragar meu",
        "gerador?",
        "Gastei tanto",
        "tempo nele!",
        "Se eu pegar,",
        "ele vai ver o que",
        "é um ZAP",
        "CANNON!"),
    "54:5259": L("54:5259",
        "MANAGER: Não vou",
        "perdoar não!",
        "O culpado pode",
        "chorar, pedindo",
        "perdão, mas ainda",
        "vou moer ele!",
        "Hahahahaha!"),
    "54:52bf": L("54:52bf",
        "MANAGER: Ah! Sim!",
        "É a PART que",
        "faltava do meu",
        "querido gerador!",
        "Você achou?"),
    "54:5315": L("54:5315",
        "Uau! Valeu!",
        "Tome este TM",
        "como recompensa!"),
    "54:5345": L("54:5345",
        "MANAGER: TM07 é",
        "meu ZAP CANNON.",
        "É uma técnica",
        "poderosa!",
        "Não é bem",
        "precisa, mas",
        "acerta em cheio!",
        "Bate forte!"),
    "54:53c6": L("54:53c6",
        "MANAGER: Meu",
        "amado gerador!",
        "Continua soltando",
        "eletricidade!"),
    "54:5676": L("54:5676",
        "Se você tem esse",
        "POKéMON, me mostra",
        "ele, por favor?"),
    "54:56a4": L("54:56a4",
        "Você vai mostrar?",
        "Que gentil!"),
    "54:56c8": L("54:56c8",
        "Não tem ele?",
        "Que pena…"),
    "54:56ea": L("54:56ea",
        "Ah, então é",
        "o {STRBUF}?",
        "Que fofo!",
        "Muito gentil da",
        "sua parte!"),
    "54:5725": L("54:5725",
        "Obrigado!",
        "Isto é uma marca",
        "de gratidão!"),
    "54:5752": L("54:5752",
        "Venha me visitar",
        "outra hora!"),
    "54:576e": L("54:576e",
        "Obrigada por me",
        "mostrar tantos",
        "POKéMON fofos.",
        "Gostei muito",
        "mesmo. Fico feliz",
        "de ter vivido uma",
        "vida tão longa."),
    "54:57d5": L("54:57d5",
        "Hm?",
        "Não é o POKéMON",
        "de que me",
        "falaram."),
    "54:5804": L("54:5804",
        "Meu neto BILL me",
        "contou de um",
        "POKéMON que tem",
        "língua longa."),
    "54:5843": L("54:5843",
        "Ah, meu neto",
        "falou de um",
        "POKéMON verde e",
        "redondo, com",
        "folhas na cabeça."),
    "54:5897": L("54:5897",
        "Conhece o",
        "POKéMON que tem",
        "esfera vermelha",
        "no corpo?",
        "Sabe, aquele",
        "que parece uma",
        "estrela?",
        "Eu ouvi que",
        "surge à noite.",
        "Eu adoraria",
        "ver ele."),
    "54:5942": L("54:5942",
        "BILL me contou",
        "de um POKéMON",
        "muito fiel ao",
        "seu treinador.",
        "Dizem que sabe",
        "rugir muito bem!"),
    "54:599b": L("54:599b",
        "Ouvi falar de um",
        "POKéMON fofo que",
        "tem seis rabos.",
        "Eu adoraria",
        "abraçar esse",
        "POKéMON fofinho!"),
    "54:59f5": L("54:59f5",
        "Conhece aquele",
        "POKéMON muito",
        "famoso?",
        "O POKéMON de",
        "corpo amarelo e",
        "bochechas rubras?",
        "Eu adoraria ver",
        "como ele fica",
        "antes de",
        "evoluir!"),
    "54:8c48": L("54:8c48",
        "",
        "Papai me deu o",
        "que voltou! A TAIL",
        "dele cresce!"),
    "54:ca00": L("54:ca00",
        "!",
        "Se POKéMON entrar",
        "em batalha, mesmo",
        "por pouco tempo,",
        "ganha EXP.",
        "No topo da lista",
        "põe o fraco.",
        "Troque na batalha",
        "rápido!",
        "Assim, o fraco",
        "POKéMON fica",
        "forte!"),
    "54:f200": L("54:f200",
        "Mas acho que eles",
        "também pensam em",
        "outros pontos."),
    "55:4276": L("55:4276",
        "Os SLOWPOKE",
        "voltaram…",
        "Mas meu APRENDIZ",
        "não voltou",
        "da ILEX FOREST.",
        "Onde será que",
        "está o folgado?"),
    "55:42ec": L("55:42ec",
        "Você espantou a",
        "TEAM ROCKET e foi",
        "sozinho pra ILEX",
        "FOREST?",
        "Que coragem!",
        "Gostei. Vem",
        "treinar conosco!"),
    "55:4359": L("55:4359",
        "Para onde foram",
        "os SLOWPOKE?",
        "Estão brincando",
        "em algum lugar?"),
    "55:439e": L("55:439e",
        "Desculpe, esqueci",
        "de agradecer.",
        "Isto é CHARCOAL",
        "que eu fiz.",
        "POKéMON de fogo",
        "vai adorar",
        "segurar isso."),
    "55:440c": L("55:440c",
        "Os SLOWPOKE",
        "voltaram, e você",
        "achou FARFETCH'D.",
        "Você é o cara!",
        "Bacana, hein!"),
    "55:9d51": L("55:9d51",
        "no rádio."),
    "55:ae53": L("55:ae53",
        "quer usar,",
        "e vem me ver."),
    "55:da52": L("55:da52",
        "PT.STORE."),
    "56:48a8": L("56:48a8",
        "EARL sou eu!",
        "Maravilhosos",
        "são os POKéMON,",
        "sim!",
        "Ensinar você",
        "eu vou!",
        "O que quer",
        "saber? Vencedor",
        "ser você quer?"),
    "56:492a": L("56:492a",
        "Bom! Ensinar",
        "eu vou!",
        "Em batalha, o",
        "POKéMON do topo",
        "da lista sai!",
        "Mude a ordem",
        "na lista, fácil",
        "a luta fica!",
        "Mais de mim",
        "quer ouvir?"),
    "56:49be": L("56:49be",
        "Então, quer saber",
        "como criar bem",
        "os POKéMON?"),
    "56:49e8": L("56:49e8",
        "Tá bom! Eu vou",
        "ensinar!",
        "Se POKéMON entrar",
        "em batalha, mesmo",
        "por pouco tempo,",
        "ganha EXP.",
        "No topo da lista",
        "põe o fraco.",
        "Troque na batalha",
        "rápido!",
        "Assim, o fraco",
        "POKéMON fica",
        "forte!"),
    "56:4a9e": L("56:4a9e",
        "Oh! Aluno esperto",
        "você é! Nada mais",
        "eu ensino!",
        "Bom com POKéMON",
        "deve ser você!"),
    "56:4aed": L("56:4aed",
        "Estou anotando",
        "a aula do",
        "professor.",
        "Melhor copiar",
        "o que está no",
        "quadro também."),
    "56:4b47": L("56:4b47",
        "Troquei meu melhor",
        "POKéMON com o",
        "cara do meu lado."),
    "56:4b74": L("56:4b74",
        "Hã? O POKéMON que",
        "acabei de pegar",
        "segurando algo!"),
    "56:4ba6": L("56:4ba6",
        "POKéMON com uma",
        "BERRY se cura",
        "na batalha.",
        "Outros itens",
        "também podem ser",
        "segurados…",
        "É difícil",
        "anotar tudo…"),
    "56:4c1f": L("56:4c1f",
        "O quadro fala",
        "sobre mudanças",
        "de status em",
        "batalha."),
    "56:4c6b": L("56:4c6b",
        "Envenenado, o",
        "POKéMON perde",
        "HP aos poucos.",
        "O veneno",
        "persiste após a",
        "batalha, e o HP",
        "cai ao andar.",
        "Pra curar, use",
        "um ANTIDOTE."),
    "56:4ced": L("56:4ced",
        "A paralisia",
        "diminui a velo-",
        "cidade e impede",
        "de andar.",
        "Fica após a luta,",
        "use PARLYZ HEAL."),
    "56:4d4f": L("56:4d4f",
        "Adormecido, seu",
        "POKéMON não pode",
        "se mexer.",
        "POKéMON dormindo",
        "não acorda após",
        "a batalha.",
        "Acorde com um",
        "AWAKENING."),
    "56:4dc2": L("56:4dc2",
        "Uma queimadura",
        "consome HP.",
        "Ela reduz",
        "o ataque.",
        "Queimadura",
        "fica após a luta.",
        "Use um BURN HEAL",
        "pra curar."),
    "56:4e38": L("56:4e38",
        "Congelado, o",
        "POKéMON não pode",
        "fazer nada.",
        "Fica congelado",
        "após a batalha.",
        "Descongele com",
        "um ICE HEAL."),
    "56:4ea3": L("56:4ea3",
        "É o caderno",
        "deste garoto…",
        "Pegue POKéMON",
        "com POKé BALLS.",
        "Até seis podem",
        "na sua equipe.",
        "Continuar lendo?"),
    "56:4f04": L("56:4f04",
        "Antes da POKé",
        "BALL, enfraqueça",
        "o alvo primeiro.",
        "Envenenado ou",
        "queimado, o",
        "POKéMON é fácil",
        "de pegar."),
    "56:4f74": L("56:4f74",
        "Alguns golpes",
        "causam confusão.",
        "Na confusão,",
        "o POKéMON pode",
        "se atacar.",
        "Sair da batalha",
        "cura qualquer",
        "confusão.",
        "Continuar lendo?"),
    "56:4ff4": L("56:4ff4",
        "Quem pega e usa",
        "POKéMON em",
        "batalhas são os",
        "treinadores.",
        "Eles devem ir",
        "aos GINÁSIOS e",
        "vencer outros",
        "treinadores.",
        "A próxima página",
        "está em branco!",
        "Garoto: E-he-he…",
        "Não escrevi",
        "mais nada…"),
    "56:5167": L("56:5167",
        "Ela usa os nomes",
        "das suas comidas",
        "preferidas.",
        "Nos apelidos",
        "que ela dá aos",
        "POKéMON, digo."),
    "56:51cb": L("56:51cb",
        "Chamo meu PIDGEY",
        "de STRAWBERRY!"),
    "56:51e9": L("56:51e9",
        "STRAWBERRY:Pijji!"),
    "56:52c2": L("56:52c2",
        "{PLAYER}, faz",
        "tempo, hein!",
        "PROF.ELM pediu",
        "pra te achar.",
        "Ele quer pedir",
        "outro favor.",
        "Aceita levar o",
        "POKéMON EGG?"),
    "56:5332": L("56:5332",
        "Descobrimos que",
        "um POKéMON não",
        "choca até",
        "crescer no EGG.",
        "Ele também tem",
        "de ficar com",
        "outros POKéMON.",
        "{PLAYER}, você",
        "é o único em",
        "quem confiamos.",
        "Ligue pro PROF.",
        "ELM quando o EGG",
        "chocar!"),
    "56:5400": L("56:5400",
        "Ah, não. Você",
        "não pode levar",
        "mais POKéMON.",
        "Vou esperar",
        "enquanto você",
        "arruma espaço."),
    "56:545f": L("56:545f",
        "M-mas… O PROF.ELM",
        "pediu por você…"),
    "56:547f": L("56:547f",
        "{PLAYER}, você",
        "leva o EGG?"),
    "56:549a": L("56:549a",
        "Um cara chamado",
        "BILL fez o sistema",
        "de POKéMON do PC."),
    "56:54cd": L("56:54cd",
        "Foi há mais ou",
        "menos três anos.",
        "A TEAM ROCKET",
        "fazia maldades",
        "com POKéMON.",
        "Mas a justiça",
        "venceu: um garoto",
        "acabou com eles."),
    "56:5549": L("56:5549",
        "POKéMON são",
        "espertos.",
        "Não obedecem a",
        "um treinador que",
        "não respeitam.",
        "Sem as GYM BADGES",
        "certas, eles só",
        "agem como querem."),
    "56:5628": L("56:5628",
        "POKéMON trocado",
        "cresce",
        "rápido.",
        "Mas sem a GYM",
        "BADGE certa,",
        "eles podem",
        "desobedecer você."),
    "56:574e": L("56:574e",
        "Há desenhos",
        "nas pedras.",
        "Tentei mover",
        "eles. Será que",
        "são o quê?"),
    "56:5814": L("56:5814",
        "Este é um ótimo",
        "lugar pra pescar.",
        "Você viu gente",
        "pescando? Que tal",
        "você?",
        "Quer uma das",
        "minhas RODS?"),
    "56:5879": L("56:5879",
        "Heh, que bom",
        "ouvir isso.",
        "Agora você é",
        "pescador também!"),
    "56:58ac": L("56:58ac",
        "Pescar é ótimo!",
        "Se há água,",
        "seja no mar ou",
        "em um riacho,",
        "use sua ROD."),
    "56:58fd": L("56:58fd",
        "Oh. Que",
        "decepção…"),
    "56:591e": L("56:591e",
        "Ei, garoto. Como",
        "estão mordendo?"),
    "56:5943": L("56:5943",
        "O que devo dar",
        "ao meu POKéMON?",
        "Talvez um item",
        "que aumente o",
        "ATAQUE…"),
    "56:5a70": L("56:5a70",
        "Ei, moço!",
        "Pode fazer um",
        "favor?",
        "Pode levar este",
        "POKéMON com MAIL",
        "pro meu amigo?",
        "Na ROUTE 31."),
    "56:5adb": L("56:5adb",
        "Vai? Perfeito!",
        "Valeu, moço!",
        "Meu amigo é",
        "um cara gordinho",
        "que só cochila.",
        "Você vai",
        "reconhecer fácil!"),
    "56:5b4b": L("56:5b4b",
        "{PLAYER} recebeu",
        "POKéMON com MAIL."),
    "56:5b69": L("56:5b69",
        "Pode ler,",
        "mas não perca!",
        "ROUTE 31!",
        "Ah, sim. Tinha",
        "uma árvore",
        "esquisita na",
        "estrada. Será",
        "que tiraram?"),
    "56:5be9": L("56:5be9",
        "Não pode levar",
        "outro POKéMON…"),
    "56:5c07": L("56:5c07",
        "Oh… Deixa pra",
        "lá…"),
    "56:5c1e": L("56:5c1e",
        "Valeu, moço! Você",
        "fez a entrega",
        "por mim!",
        "Tome algo",
        "pela ajuda!"),
    "56:5c6c": L("56:5c6c",
        "Meu amigo estava",
        "cochilando, né?",
        "O que eu disse?"),
    "56:5c9d": L("56:5c9d",
        "Uma árvore",
        "estranha bloqueia",
        "a estrada.",
        "Ela se mexe",
        "se você falar.",
        "Dizem que ela",
        "ficou selvagem",
        "com SQUIRTBOTTLE."),
    "56:5d2d": L("56:5d2d",
        "Gosto do POKéMON",
        "Lullaby que toca",
        "no rádio."),
    "56:5ef2": L("56:5ef2",
        "Hoje é {STRBUF}.",
        "Isso quer dizer",
        "que o Concurso de",
        "Insetos é hoje.",
        "As regras são",
        "simples.",
        "Use um dos seus",
        "POKéMON pra pegar",
        "um inseto que",
        "será avaliado.",
        "Quer dar uma",
        "chance?"),
    "56:5fa4": L("56:5fa4",
        "Aqui estão as",
        "PARK BALLS pro",
        "Concurso."),
    "56:5fce": L("56:5fce",
        "{PLAYER} recebeu",
        "20 PARK BALLS."),
    "56:5fe9": L("56:5fe9",
        "Quem pegar o",
        "inseto mais",
        "forte vence",
        "o jogo.",
        "Você tem 20",
        "minutos.",
        "Se ficar sem",
        "PARK BALLS, já",
        "era.",
        "Pode ficar com",
        "o último inseto",
        "que pegar.",
        "Vai lá e pega",
        "o inseto mais",
        "forte que",
        "puder!"),
    "56:60cd": L("56:60cd",
        "Opa…",
        "Você tem mais",
        "de um POKéMON.",
        "Vai ter que",
        "usar {STRBUF},",
        "o primeiro POKéMON",
        "da sua equipe.",
        "Tudo bem",
        "com você?"),
    "56:613e": L("56:613e",
        "Certo, seguramos",
        "seus outros",
        "POKéMON."),
    "56:619e": L("56:619e",
        "Escolha o",
        "POKéMON que vai",
        "usar no Contest,",
        "e vem me ver."),
    "56:61e3": L("56:61e3",
        "Certo. Esperamos",
        "que participe",
        "no futuro."),
    "56:620f": L("56:620f",
        "Opa…",
        "O primeiro POKé-",
        "MON da equipe",
        "não pode lutar.",
        "Troque com o",
        "POKéMON que você",
        "quer usar,",
        "e vem me ver."),
    "56:6283": L("56:6283",
        "Opa…",
        "Sua equipe e a",
        "PC BOX estão",
        "cheias.",
        "Não tem espaço",
        "pra pôr o inseto",
        "que você pegar.",
        "Faça um espaço",
        "na equipe ou na",
        "PC BOX e",
        "vem me ver."),
    "56:6326": L("56:6326",
        "Opa…",
        "Você tem um EGG",
        "como primeiro",
        "POKéMON inicial.",
        "Troque com o",
        "POKéMON que você",
        "quer usar,",
        "e vem me ver."),
    "56:63a1": L("56:63a1",
        "Restam {STRBUF}",
        "minuto(s) ainda.",
        "Quer terminar",
        "agora?"),
    "56:63e2": L("56:63e2",
        "Certo. Espere no",
        "Portão Norte",
        "pelo anúncio",
        "dos vencedores."),
    "56:642a": L("56:642a",
        "Certo. Volte",
        "pra fora e",
        "termine."),
    "56:6456": L("56:6456",
        "O Concurso de",
        "hoje acabou.",
        "Esperamos que",
        "participe depois."),
    "56:649b": L("56:649b",
        "Fazemos Concursos",
        "no PARK toda",
        "hora. Deveria",
        "tentar."),
    "56:64df": L("56:64df",
        "Quando é o",
        "próximo Concurso",
        "de Insetos?"),
    "56:9c45": L("56:9c45",
        "de graça.",
        "Presente. Dê pro",
        "POKéMON segurar."),
    "56:a000": L("56:a000",
        "DEFENSE."),
}
