# -*- coding: utf-8 -*-
"""Lote 20 -- banco 50: Kanto, os seis desafiantes e a POWER PLANT.

Ficam no original: ROCK TUNNEL, POWER PLANT, MAGNET TRAIN, MT.SILVER,
MT.MOON, CLEFAIRY, KANTO, JOHTO, LAVENDER, UNDERGROUND PATH, e a KANTO
POKéMON FEDERATION.
"""
from pt.estrutura import linhas as L

DIALOGO = {
    # ---------------- caminho do ROCK TUNNEL ----------------
    "50:40a0": L("50:40a0", "Opa! Perigo, cara"),
    "50:40b4": L("50:40b4",
                 "Meus POKéMON se",
                 "machucaram antes",
                 "de entrar no ROCK",
                 "TUNNEL.",
                 "É melhor levar",
                 "eles ao CENTRO",
                 "POKéMON já."),
    "50:411a": L("50:411a",
                 "Você já foi a um",
                 "piquenique?",
                 "É muito",
                 "divertido!"),
    "50:4157": L("50:4157",
                 "A gente assa um",
                 "monte de doces",
                 "e divide com todo",
                 "mundo. É delícia!"),

    # ---------------- os ecologistas ----------------
    "50:419d": L("50:419d", "Ei, você!", "Não jogue lixo!"),
    "50:41b5": L("50:41b5", "Eu só estava", "avisando…"),
    "50:41d1": L("50:41d1",
                 "Desculpe. Você não",
                 "jogou lixo. Foi",
                 "engano meu."),
    "50:4202": L("50:4202",
                 "As pessoas não",
                 "deviam deixar",
                 "lixo por aí."),
    "50:423a": L("50:423a",
                 "Economizar energia",
                 "é importante, mas",
                 "o meio ambiente é",
                 "ainda mais."),

    # ---------------- a cantora ----------------
    "50:4283": L("50:4283",
                 "Ela vem descendo a",
                 "MT.SILVER quando",
                 "ela vier…",
                 "A MT.SILVER fica",
                 "em JOHTO, né?"),
    "50:42d2": L("50:42d2", "Eu estava ocupada", "cantando…"),
    "50:42eb": L("50:42eb", "Batalha é uma", "questão de foco."),
    "50:430d": L("50:430d",
                 "Vou te contar um",
                 "segredo.",
                 "Mas primeiro a",
                 "gente luta!"),
    "50:433b": L("50:433b", "Ah, droga!", "Perdi essa…"),
    "50:4353": L("50:4353",
                 "A POWER PLANT fica",
                 "do outro lado de",
                 "um riacho."),

    # ---------------- os seis desafiantes em fila ----------------
    "50:4a2e": L("50:4a2e",
                 "Vença nós seis",
                 "treinadores e leve",
                 "um belo prêmio!",
                 "Acha que dá",
                 "conta do recado?"),
    "50:4a83": L("50:4a83", "Uhu! Muito bom."),
    "50:4a96": L("50:4a96",
                 "Dei o meu melhor.",
                 "Nada a lamentar."),
    "50:4ab9": L("50:4ab9", "Sou o segundo.", "Agora é sério!"),
    "50:4ad6": L("50:4ad6", "Como eu perdi?"),
    "50:4ae9": L("50:4ae9",
                 "Dei o meu melhor.",
                 "Nada a lamentar."),
    "50:4b0c": L("50:4b0c", "Chegou o Nº 3!", "Não vou facilitar"),
    "50:4b2a": L("50:4b2a", "Ai! Fui esmagado!"),
    "50:4b3d": L("50:4b3d",
                 "Dei o meu melhor.",
                 "Nada a lamentar."),
    "50:4b60": L("50:4b60", "Eu sou o Nº 4!", "Já está cansado?"),
    "50:4b87": L("50:4b87",
                 "Dei o meu melhor.",
                 "Nada a lamentar."),
    "50:4baa": L("50:4baa", "Certo! Sou o Nº 5.", "Vou te esmagar!"),
    "50:4bd9": L("50:4bd9",
                 "Dei o meu melhor.",
                 "Nada a lamentar."),
    "50:4bfc": L("50:4bfc",
                 "Sou o último da",
                 "fila, mas eu digo:",
                 "sou durão!"),
    "50:4c2c": L("50:4c2c", "Só pode ser piada"),
    "50:4c3c": L("50:4c3c",
                 "Dei o meu melhor.",
                 "Nada a lamentar."),
    "50:4c5f": L("50:4c5f",
                 "Mufufufu…",
                 "Eu não tenho nada",
                 "a ver com os seis",
                 "treinadores.",
                 "Esperei aqui para",
                 "te vencer quando",
                 "estivesse cansado",
                 "de tanta batalha."),
    "50:4ce2": L("50:4ce2", "Você não está", "cansado nada?"),
    "50:4cfb": L("50:4cfb",
                 "Desculpe… Não vou",
                 "trapacear mais…"),

    # ---------------- os motoqueiros e o resto ----------------
    "50:4f9c": L("50:4f9c", "Está sol, mas eu", "estou encharcado…"),
    "50:4fb8": L("50:4fb8",
                 "Quando chove, é",
                 "difícil dar a",
                 "partida…"),
    "50:4fe2": L("50:4fe2", "Hmmm… Não sei o", "que fazer…"),
    "50:5012": L("50:5012",
                 "Você parecia bom.",
                 "Fiquei com medo de",
                 "te encarar…"),
    "50:5043": L("50:5043", "Eu corro como o", "vento!"),
    "50:506a": L("50:506a",
                 "Eu uso shorts o",
                 "ano inteiro.",
                 "É a minha regra",
                 "de moda."),
    "50:50a8": L("50:50a8", "Chegue mais perto", "e dê uma olhada!"),
    "50:50d9": L("50:50d9",
                 "O maior cuspidor",
                 "de fogo de KANTO",
                 "sou eu.",
                 "Mas não o melhor",
                 "treinador…"),
    "50:520a": L("50:520a", "Perdi? Isso é", "novidade também…"),
    "50:5223": L("50:5223",
                 "Eu talvez vá à",
                 "POWER PLANT. É",
                 "perto do TUNNEL?"),
    "50:525b": L("50:525b",
                 "Tenho a impressão",
                 "de que vou ganhar",
                 "Vamos ver se eu",
                 "estou certo!"),
    "50:5293": L("50:5293", "Aah, você é forte", "demais."),
    "50:52ad": L("50:52ad",
                 "Ouvi que CLEFAIRY",
                 "vêm na MT.MOON.",
                 "Mas onde será",
                 "que eles estão?"),
    "50:52f6": L("50:52f6", "……Vou treinar", "mais um pouco…"),

    # ---------------- a KANTO POKéMON FEDERATION ----------------
    "50:5449": L("50:5449",
                 "A KANTO POKéMON",
                 "FEDERATION nunca",
                 "vai cair!"),
    "50:5475": L("50:5475",
                 "A polícia fechou o",
                 "nosso UNDERGROUND",
                 "PATH! Isso me dá",
                 "muita raiva!"),
    "50:54c4": L("50:54c4",
                 "Arrasado por um",
                 "moleque de JOHTO…"),
    "50:54e8": L("50:54e8",
                 "Somos a KANTO",
                 "POKéMON FEDERA-",
                 "TION!",
                 "É isso aí, cara!"),
    "50:552a": L("50:552a",
                 "Vamos tentar não",
                 "incomodar ninguém",
                 "daqui pra frente"),

    # ---------------- o MAGNET TRAIN e a POWER PLANT ----------------
    "50:5557": L("50:5557",
                 "Como o MAGNET",
                 "TRAIN funciona?"),
    "50:557a": L("50:557a",
                 "Eu só quero ver o",
                 "MAGNET TRAIN…"),
    "50:55a0": L("50:55a0",
                 "A força dos ímãs",
                 "é impressionante!"),
    "50:55c4": L("50:55c4",
                 "Não vivemos sem",
                 "eletricidade.",
                 "A POWER PLANT",
                 "fornece energia",
                 "para a gente."),
    "50:5615": L("50:5615", "Não desperdice", "energia!"),
    "50:562e": L("50:562e",
                 "A POWER PLANT ao",
                 "norte de LAVENDER",
                 "fornece energia",
                 "ao MAGNET TRAIN."),
    "50:5719": L("50:5719", "POWER PLANT KANTO"),

    # ---------------- o resto ----------------
    "50:5790": L("50:5790",
                 "A alergia está me",
                 "fazendo espirrar!",
                 "Atchiiim!"),
    "50:57bd": L("50:57bd",
                 "Você gosta de",
                 "POKéMON, né?",
                 "Eu também!"),
    "50:57df": L("50:57df", "Eu diria que essa", "foi derrota minha"),
    "50:57fe": L("50:57fe",
                 "Olha o que você",
                 "fez com o POKéMON",
                 "Eu não vou",
                 "esquecer disso…"),
}
