# -*- coding: utf-8 -*-
"""Lote 13 -- o resto do banco 40, achado pela varredura.

O lote 7 traduziu 32 falas do banco 40, as que o percurso de scripts
tinha alcancado.  A varredura da 0.16.0 achou mais 52 no mesmo banco:
telefone, GAME CORNER, felicidade do POKéMON, placas, e mensagens de
batalha.

## O que fica de fora, e por que

As chaves com marcador `<TARGET>`, `<USER>`, `<ENEMY>` nao entram.  Esses
marcadores nao sao texto: sao bytes que o motor troca em tempo de
execucao pelo nome do POKéMON.  O texto do mod e publicado como esta, so
que o override nao passa por essa substituicao -- entao "<TARGET> can't
receive the gift!" traduzido apareceria com o "<TARGET>" literal na tela.
E o mesmo motivo pelo qual `build_mod.py` descarta essas chaves na
traducao derivada.

Ficam no original: GAME CORNER, COIN CASE, POKéMON RADIO, POKéMON
JOURNAL, TEAM ROCKET, DISABLED.
"""
from pt.estrutura import linhas as L

DIALOGO = {
    # ---------------- placas e cenario ----------------
    "40:474b": L("40:474b",
                 "Esperamos ver você",
                 "de novo."),
    "40:481f": L("40:481f",
                 "Uma coleção",
                 "inteira de livros",
                 "de POKéMON!"),
    "40:4880": L("40:4880",
                 "JURAMENTO ROCKET",
                 "Roubar POKéMON",
                 "por lucro!",
                 "Explorar POKéMON",
                 "por lucro!",
                 "POKéMON existem",
                 "para a glória da",
                 "TEAM ROCKET!"),
    "40:4919": L("40:4919",
                 "Um monte de produ-",
                 "tos de POKéMON!"),
    "40:4947": L("40:4947",
                 "Meu reflexo!",
                 "Tô bonito!"),
    "40:4970": L("40:4970",
                 "POKéMON JOURNAL",
                 "PÁGINA INICIAL…",
                 "Não foi",
                 "atualizada…"),
    "40:49a0": L("40:49a0",
                 "POKéMON RADIO!",
                 "Ligue e peça a",
                 "sua música!"),
    "40:49e6": L("40:49e6",
                 "Um POKéMON talvez",
                 "consiga mover."),
    "40:4a08": L("40:4a08",
                 "Talvez um POKéMON",
                 "quebre isto."),
    "40:4a26": L("40:4a26",
                 "Cure Seus POKéMON!",
                 "CENTRO POKéMON"),

    # ---------------- telefone ----------------
    "40:4b1d": L("40:4b1d",
                 "Registrar o número",
                 "de telefone?"),
    "40:4b48": L("40:4b48", "{STRBUF}."),
    "40:4b56": L("40:4b56",
                 "Eu ligo se rolar",
                 "alguma coisa."),
    "40:4bb7": L("40:4bb7",
                 "O seu telefone não",
                 "tem memória para",
                 "mais números."),
    "40:4c14": L("40:4c14",
                 "Uau, você é bom",
                 "de batalha.",
                 "Quer me dar o seu",
                 "número?",
                 "Eu ligo para outra",
                 "batalha."),
    "40:4c93": L("40:4c93",
                 "{PLAYER} registrou",
                 "{STRBUF}."),
    "40:4cd0": L("40:4cd0",
                 "Ah, tudo bem…",
                 "Se quiser o meu",
                 "número, é só",
                 "me falar."),
    "40:4d4a": L("40:4d4a",
                 "Eu esperei você.",
                 "Vamos lutar!"),

    # ---------------- premios e ginasio ----------------
    "40:4d7b": L("40:4d7b",
                 "prêmio {STRBUF},",
                 "um {STRBUF}!"),
    "40:4ea4": L("40:4ea4",
                 "LÍDER: {STRBUF}",
                 "TREINADORES QUE",
                 "VENCERAM: {PLAYER}"),

    # ---------------- GAME CORNER ----------------
    "40:4ec7": L("40:4ec7",
                 "Bem-vindo ao",
                 "GAME CORNER."),
    "40:4ee4": L("40:4ee4",
                 "Precisa de fichas",
                 "de jogo?",
                 "Ah, você não tem",
                 "uma COIN CASE",
                 "para elas."),
    "40:4f2b": L("40:4f2b",
                 "Precisa de umas",
                 "fichas de jogo?",
                 "São ¥1000 por",
                 "50 fichas. Quer",
                 "comprar?"),
    "40:4f78": L("40:4f78",
                 "Obrigado!",
                 "Aqui, 50 fichas."),
    "40:4f97": L("40:4f97",
                 "Obrigado! Aqui",
                 "estão 500 fichas."),
    "40:4fb7": L("40:4fb7",
                 "Você não tem",
                 "dinheiro."),
    "40:4fd4": L("40:4fd4",
                 "Opa! Sua COIN",
                 "CASE está cheia."),
    "40:4ff5": L("40:4ff5",
                 "Sem fichas hoje?",
                 "Volte sempre!"),

    # ---------------- felicidade do POKéMON ----------------
    "40:5072": L("40:5072",
                 "Uau! Você e seu",
                 "POKéMON são muito",
                 "unidos!"),
    "40:509c": L("40:509c",
                 "POKéMON ficam mais",
                 "amigos se você",
                 "passar tempo",
                 "com eles."),
    "40:50d1": L("40:50d1",
                 "Você não domou",
                 "o seu POKéMON.",
                 "Se não for legal,",
                 "ele emburra."),

    # ---------------- dinheiro e batalha ----------------
    "40:510c": L("40:510c",
                 "{PLAYER} pegou",
                 "¥{NUM}!"),
    "40:538d": L("40:538d",
                 "{NUM}",
                 "por vencer!"),
    "40:53cb": L("40:53cb",
                 "{NUM}",
                 "por vencer!",
                 "Mandei para MÃE!"),
    "40:5459": L("40:5459",
                 "{RIVAL}: Isso!",
                 "Acho que escolhi",
                 "um bom POKéMON!"),
    "40:54a4": L("40:54a4",
                 "{STRBUF}.",
                 "{PLAYER} vai",
                 "trocar POKéMON?"),
    "40:54d1": L("40:54d1",
                 "Não há vontade de",
                 "lutar!"),
    "40:567f": L("40:567f",
                 "O {STRBUF}",
                 "selvagem come!"),
    "40:569d": L("40:569d",
                 "{STRBUF}",
                 "está furioso!"),
    "40:58bc": L("40:58bc",
                 "{STRBUF} está",
                 "DISABLED!"),
    "40:5b39": L("40:5b39",
                 "{STRBUF} caiu",
                 "em {NUM}!"),
    "40:5c2c": L("40:5c2c",
                 "{STRBUF} não",
                 "sobe mais!"),
    "40:5c49": L("40:5c49",
                 "{STRBUF} não",
                 "cai mais!"),
    "40:5dd7": L("40:5dd7",
                 "{STRBUF} ficou",
                 "DISABLED!"),
}
