# -*- coding: utf-8 -*-
"""Lote 25 -- interiores de Johto: o GINÁSIO de PRYCE com o piso de gelo
(51), a DANCE THEATER e o GINÁSIO dos fantasmas de ECRUTEAK (52), o
GINÁSIO de dragões e as varridas de CLAIR (53), e AZALEA com os bug
catchers, a AMY e a MAY (55).

Ficam no original: TM09, TM13, TM24, TM30, PRYCE, LANCE, CLAIR, AMY, MAY,
SLOWPOKE, GINÁSIO, LÍDER, POKéMON, BOX, RECORDE, RECORD, WHIRL.
"""
from pt.estrutura import linhas as L

DIALOGO = {

    # ---------------- banco 51 ----------------
    "51:4374": L("51:4374",
                 "{PLAYER} recebeu",
                 "TM09."),
    "51:518c": L("51:518c",
                 "{PLAYER} recebeu",
                 "TM13."),
    "51:57b1": L("51:57b1",
                 "Vou congelar",
                 "seus POKéMON, você",
                 "não fará nada!"),
    "51:57e0": L("51:57e0",
                 "Droga. Não pude",
                 "fazer nada."),
    "51:57fd": L("51:57fd",
                 "Acho que existe um",
                 "movimento que um",
                 "POKéMON pode usar",
                 "mesmo congelado."),
    "51:5835": L("51:5835",
                 "Este GINÁSIO",
                 "tem piso liso.",
                 "É divertido, não",
                 "é?",
                 "Mas ei, aqui nós",
                 "não estamos",
                 "brincando!"),
    "51:588d": L("51:588d",
                 "Você vê como",
                 "somos sérios?"),
    "51:58ad": L("51:58ad",
                 "Adoro patinar",
                 "com meus POKéMON",
                 "neste GINÁSIO!"),
    "51:58df": L("51:58df",
                 "Conheço o segredo",
                 "do PRYCE."),
    "51:58f6": L("51:58f6",
                 "Vou te contar o",
                 "segredo do PRYCE."),
    "51:5917": L("51:5917",
                 "O segredo do",
                 "poder de PRYCE…",
                 "Ele medita sob",
                 "uma cachoeira",
                 "para fortalecer",
                 "mente e corpo."),
    "51:597e": L("51:597e",
                 "Para chegar ao",
                 "PRYCE, você",
                 "precisa pensar",
                 "antes de patinar."),
    "51:59c4": L("51:59c4",
                 "Não perderia para",
                 "você no esqui!"),
    "51:59e6": L("51:59e6",
                 "Sem patinar com",
                 "precisão, você",
                 "não vai longe",
                 "neste GINÁSIO."),
    "51:5a27": L("51:5a27",
                 "Veja minha",
                 "virada paralela!"),
    "51:5a44": L("51:5a44",
                 "Não! Você me fez",
                 "cair!"),
    "51:5a5f": L("51:5a5f",
                 "Não devia ter",
                 "me gabado do meu",
                 "esqui…"),

    # ---------------- banco 52 ----------------
    "52:48e9": L("52:48e9",
                 "Oh, você é muito",
                 "forte."),
    "52:4903": L("52:4903",
                 "Eu gostei do",
                 "duelo. Queria",
                 "te ver de novo."),
    "52:4938": L("52:4938",
                 "Eu sempre danço",
                 "com meus POKéMON.",
                 "Claro, eu também",
                 "os treino."),
    "52:4974": L("52:4974",
                 "Oh, tão perto!",
                 "Quase te peguei!"),
    "52:4995": L("52:4995",
                 "O ritmo é",
                 "importante para",
                 "dançar e para",
                 "POKéMON."),
    "52:49c9": L("52:49c9",
                 "Minha presilha é",
                 "bonita, não?",
                 "Oh. Uma batalha",
                 "de POKéMON?"),
    "52:49f6": L("52:49f6",
                 "Não tenho mais",
                 "POKéMON…"),
    "52:4a12": L("52:4a12",
                 "Coloco uma flor",
                 "diferente no",
                 "grampo todo mês."),
    "52:4a4a": L("52:4a4a",
                 "Oh, você é um",
                 "treinador fofo.",
                 "Quer batalhar?"),
    "52:4a7f": L("52:4a7f",
                 "Você é mais forte",
                 "do que aparenta."),
    "52:4a9e": L("52:4a9e",
                 "Treinei muito e",
                 "me achava capaz",
                 "de batalhar. Mas",
                 "acho que não."),
    "52:4ae6": L("52:4ae6",
                 "Gosta da minha",
                 "dança? Também sou",
                 "boa com POKéMON."),
    "52:4b14": L("52:4b14",
                 "Ooh, você também",
                 "é bom em POKéMON."),
    "52:4b32": L("52:4b32",
                 "Continuo dançando",
                 "porque há gente",
                 "que gosta do",
                 "que eu faço.",
                 "Meus POKéMON",
                 "me animam."),
    "52:54a7": L("52:54a7",
                 "Passei a primavera",
                 "com meus POKéMON.",
                 "Depois o verão, o",
                 "outono, o inverno",
                 "Então a primavera",
                 "voltou. A gente",
                 "convive junta há",
                 "muito tempo."),
    "52:5527": L("52:5527",
                 "Já vivi a vitória",
                 "e a derrota."),
    "52:554d": L("52:554d",
                 "De onde vieram",
                 "os POKéMON?"),
    "52:5568": L("52:5568",
                 "Consegue causar",
                 "dano aos nossos",
                 "POKéMON?"),
    "52:55a1": L("52:55a1",
                 "Só usamos os",
                 "POKéMON fantasma",
                 "Nenhum ataque",
                 "normal consegue",
                 "feri-los!"),
    "52:5602": L("52:5602",
                 "Quem quiser vencer",
                 "mais, vencerá!"),
    "52:5628": L("52:5628",
                 "Confuso com nosso",
                 "piso invisível?",
                 "Vença-me se quiser",
                 "uma dica!"),
    "52:5674": L("52:5674",
                 "Tudo bem. Eu vou",
                 "contar o segredo",
                 "do piso",
                 "invisível.",
                 "O caminho está",
                 "na nossa frente!"),

    # ---------------- banco 53 ----------------
    "53:4495": L("53:4495",
                 "{PLAYER} recebeu",
                 "TM24."),
    "53:4651": L("53:4651",
                 "Primeira batalha",
                 "contra dragões?",
                 "Vou mostrar como",
                 "são durões!"),
    "53:4696": L("53:4696",
                 "Que decepção!"),
    "53:46a8": L("53:46a8",
                 "Você conhece o",
                 "LANCE, o mestre",
                 "dos dragões?",
                 "Não pode ser."),
    "53:46e5": L("53:46e5",
                 "Minha chance de",
                 "perder? Nem",
                 "um por cento!"),
    "53:471d": L("53:471d",
                 "Agora sei minhas",
                 "limitações.",
                 "Obrigado por me",
                 "mostrar!"),
    "53:4753": L("53:4753",
                 "Os dragões são",
                 "POKéMON sagrados.",
                 "Eles têm muita",
                 "energia vital.",
                 "Se você não levar",
                 "a sério, não vai",
                 "conseguir",
                 "derrotá-los."),
    "53:47cc": L("53:47cc",
                 "Dragões são fracos",
                 "contra movimentos",
                 "de dragão."),
    "53:4aa9": L("53:4aa9",
                 "Você é especial…"),
    "53:4abb": L("53:4abb",
                 "Mas espere só!",
                 "Meus POKéMON vão",
                 "ficar ainda mais",
                 "poderosos.",
                 "Como treinador",
                 "e POKéMON, seremos",
                 "mais fortes!"),
    "53:4b20": L("53:4b20",
                 "Treinamos firme",
                 "com a CLAIR.",
                 "Não posso perder",
                 "de jeito nenhum!"),
    "53:4b69": L("53:4b69",
                 "Argh! Estou tão",
                 "enojado!"),
    "53:4b83": L("53:4b83",
                 "Ufa…",
                 "Vou ter que",
                 "repensar o treino"),
    "53:4bad": L("53:4bad",
                 "O bloco caiu!",
                 "pelo buraco!"),
    "53:5a92": L("53:5a92",
                 "RECORDE ATUAL",
                 "{STRBUF} pego",
                 "por {STRBUF}"),
    "53:5ded": L("53:5ded",
                 "{PLAYER} recebeu",
                 "TM30."),

    # ---------------- banco 55 ----------------
    "55:515e": L("55:515e",
                 "POKéMON inseto",
                 "evoluem jovens.",
                 "E por isso ficam",
                 "mais fortes."),
    "55:519d": L("55:519d",
                 "Só evoluir não",
                 "basta!"),
    "55:51b9": L("55:51b9",
                 "POKéMON ficam",
                 "mais fortes se",
                 "evoluem. Sério!"),
    "55:51e7": L("55:51e7",
                 "Os insetos são",
                 "legais e fortes!",
                 "Vou provar para",
                 "você!"),
    "55:521a": L("55:521a",
                 "Você provou como é",
                 "durão…"),
    "55:5239": L("55:5239",
                 "São tão legais,",
                 "mas as meninas",
                 "não gostam de",
                 "POKéMON inseto.",
                 "Não sei por quê…"),
    "55:527e": L("55:527e",
                 "Você salvou todos",
                 "os SLOWPOKE?",
                 "Ufa! Você é fera!",
                 "Mas meus POKéMON",
                 "adultos são bem",
                 "durões também!"),
    "55:52e4": L("55:52e4",
                 "Deveria ensinar",
                 "a eles melhores",
                 "movimentos."),
    "55:530f": L("55:530f",
                 "AMY: Oi! Você vai",
                 "desafiar o LÍDER?",
                 "Nem pensar!"),
    "55:5341": L("55:5341",
                 "AMY & MAY: Oh,",
                 "duplamente bom!"),
    "55:5362": L("55:5362",
                 "AMY: Você é",
                 "muito forte!"),
    "55:537d": L("55:537d",
                 "MAY: Você quer",
                 "ver o LÍDER?",
                 "Nós primeiro!"),
    "55:53ae": L("55:53ae",
                 "AMY & MAY: Oh,",
                 "duplamente bom!"),
    "55:53cf": L("55:53cf",
                 "MAY: Meus insetos",
                 "perderam! Que",
                 "pena!"),
}