# -*- coding: utf-8 -*-
"""Lote 10a: Blackthorn City e arredores"""
from pt.estrutura import linhas as L

DIALOGO = {
    "49:5994": L("49:5994",  # 7
                 "Me desculpe.",
                 "Nosso LÍDER esta",
                 "treinando na",
                 "caverna lá atrás.",
                 "Não tenho ideia",
                 "quando nosso LÍDER",
                 "vai voltar."),
    "49:5a01": L("49:5a01",  # 6
                 "Nosso LÍDER esta",
                 "te esperando.",
                 "Porém, seria",
                 "impossível para",
                 "um treinador comum",
                 "vencer."),
    "49:5a6b": L("49:5a6b",  # 7
                 "Você derrotou",
                 "nosso LÍDER?",
                 "Isso e incrível!",
                 "Com seu poder,",
                 "você deve ter",
                 "sucesso na",
                 "LIGA POKéMON."),
    "49:5ad0": L("49:5ad0",  # 4
                 "Só usuarios de",
                 "dragão podem",
                 "treinar aqui.",
                 "Por favor, va."),
    "49:5b0e": L("49:5b0e",  # 4
                 "Como CLAIR, a",
                 "mestra do dragão,",
                 "permitiu, você",
                 "pode entrar."),
    "49:5b4e": L("49:5b4e",  # 3
                 "Meu radio esta",
                 "quebrado?",
                 "Só esse sinal."),
    "49:5b87": L("49:5b87",  # 4
                 "Arooo! Vocês na",
                 "minha cabeça!",
                 "Hae? Estou ouvindo",
                 "meu radio!"),
    "49:5bc1": L("49:5bc1",  # 3
                 "Você vai fazer",
                 "seu POKéMON",
                 "esquecer golpes?"),
    "49:5bf5": L("49:5bf5",  # 3
                 "Vou me tornar",
                 "um usuário de",
                 "dragão CLAIR."),
    "49:5c1f": L("49:5c1f",  # 4
                 "SANTOS: \u2026",
                 "E sabado\u2026",
                 "Sou SANTOS",
                 "do sabado\u2026"),
    "49:5c4f": L("49:5c4f",  # 1
                 "Fique com isso\u2026"),
    "49:5c63": L("49:5c63",  # 6
                 "SANTOS: \u2026",
                 "SPELL TAG\u2026",
                 "Golpes do tipo",
                 "fantasma ficam",
                 "mais fortes\u2026",
                 "Vai te assustar\u2026"),
    "49:5cae": L("49:5cae",  # 5
                 "SANTOS: \u2026",
                 "Até outro",
                 "sabado\u2026",
                 "Não vou ter",
                 "mais presentes\u2026"),
    "49:5cf8": L("49:5cf8",  # 2
                 "SANTOS: Hoje não",
                 "e sabado\u2026"),
    "49:5d16": L("49:5d16",  # 5
                 "Uau, você veio",
                 "pela ICE",
                 "PATH?",
                 "Você deve ser",
                 "um treinador!"),
    "49:5d5f": L("49:5d5f",  # 3
                 "BLACKTHORN CITY",
                 "Um Refugio",
                 "Montanhoso"),
    "49:5d89": L("49:5d89",  # 5
                 "BLACKTHORN CITY",
                 "POKéMON GYM",
                 "LÍDER: CLAIR",
                 "A Abencoadora",
                 "Dragão"),
    "49:5dd1": L("49:5dd1",  # 2
                 "CASA DO",
                 "APAGADOR GOLPES"),
    "49:5de7": L("49:5de7",  # 2
                 "DRAGON'S DEN",
                 "A FRENTE"),
    "49:5dfb": L("49:5dfb",  # 6
                 "TRAINER TIPS",
                 "Um POKéMON",
                 "segurando uma",
                 "MIRACLEBERRY",
                 "cura qualquer",
                 "problema status."),
    "53:40f3": L("53:40f3",  # 15
                 "Sou CLAIR. Eu sou",
                 "a melhor mestra",
                 "do dragão do",
                 "mundo.",
                 "Posso rivalizar",
                 "até com os QUATRO",
                 "GRANDES da LIGA",
                 "POKéMON.",
                 "Ainda quer",
                 "me desafiar?",
                 "\u2026Tudo bem.",
                 "Vamos lá!",
                 "Como treinadora,",
                 "vou usar o maximo",
                 "contra oponente!"),
    "53:41cf": L("53:41cf",  # 4
                 "Eu perdi?",
                 "Não acredito.",
                 "Deve haver algum",
                 "engano\u2026"),
    "53:4207": L("53:4207",  # 27
                 "Não vou admitir",
                 "isso.",
                 "Pode ter sido",
                 "derrotada, mas",
                 "você ainda não",
                 "esta pronta para",
                 "a LIGA POKéMON.",
                 "Sei. Você deveria",
                 "fazer o desafio",
                 "do usuário",
                 "dragão.",
                 "Atrás deste GYM",
                 "ha um lugar",
                 "chamado",
                 "DRAGON'S DEN.",
                 "Va e me traga o",
                 "DRAGON FANG",
                 "do fundo da DEN.",
                 "Esse e o teste",
                 "para ser aceito",
                 "como um",
                 "verdadeiro",
                 "usuário dragão.",
                 "Se conseguir,",
                  "vou aceita-lo",
                 "como treinador.",
                 "Até lá, INSÍGNIA!"),
    "53:4391": L("53:4391",  # 6
                 "CLAIR: O que",
                 "acontece?",
                 "Essa tarefa não",
                 "e difícil para",
                 "você, a menos que",
                 "tenha sido sorte."),
    "53:43f0": L("53:43f0",  # 7
                 "CLAIR: Você não",
                 "pegou isso no",
                 "DRAGON'S DEN.",
                 "Tentar trapacear",
                 "assim\u2026",
                 "Estou desapontada",
                 "com você."),
    "53:4451": L("53:4451",  # 5
                 "CLAIR: Você se",
                 "provou para mim.",
                 "Quero que você",
                 "fique com",
                 "esta MT."),
    "53:44a7": L("53:44a7",  # 8
                 "Contem",
                 "DRAGONBREATH.",
                 "Não, não tem nada",
                 "a ver com minha",
                 "respiração.",
                 "Se não quiser,",
                 "não precisa",
                 "pegar."),
    "53:4525": L("53:4525",  # 21
                 "Você já colecionou",
                 "todas as",
                 "INSIGNIAS.",
                 "Seu destino e a",
                 "LIGA POKéMON no",
                 "INDIGO PLATEAU.",
                 "Sabe como chegar",
                 "lá?",
                 "Daqui, va para",
                 "NEW BARK TOWN.",
                 "Depois SURF",
                 "para lê.",
                 "A rota lá e",
                 "muito difícil.",
                 "Não ouse",
                 "perder na",
                 "LIGA POKéMON!",
                 "Se perder, vou",
                 "me sentir ainda",
                 "pior por ter",
                 "perder para você!"),
    "53:47fa": L("53:47fa",  # 16
                 "Ei!",
                 "FUTURO",
                 "CAMPEÃO!",
                 "Já faz tempo que",
                 "comecamos, mas",
                 "já estamos quase",
                 "lá! Conta comigo!",
                 "CLAIR usa dragões",
                 "miticos e sagrados",
                 "do tipo dragão.",
                 "Você não consegue",
                 "machuca-los",
                 "facilmente.",
                 "Mas saiba que",
                 "eles são fracos",
                 "contra gelo."),
    "53:48e8": L("53:48e8",  # 8
                 "Você foi incrível",
                 "ao vencer CLAIR!",
                 "Só falta o desafio",
                 "da LIGA POKéMON.",
                 "Você esta no",
                 "caminho para se",
                 "tornar o",
                 "CAMPEÃO POKéMON!"),
    "53:4c64": L("53:4c64",  # 4
                 "CLAIR e LANCE",
                 "treinaram aqui",
                 "para aperfeicoar",
                 "suas habilidades."),
    "53:4ca4": L("53:4ca4",  # 1
                 "DRATINI: Draa!"),
    "53:4d20": L("53:4d20",  # 8
                 "Não pode comprar",
                 "MAX REVIVE, mas",
                 "restaura todo",
                 "POKéMON desmaiado",
                 "Cuidado -- não",
                 "restaura PP, os",
                 "PONTOS DE PODER",
                 "necessarios."),
    "53:4d9f": L("53:4d9f",  # 6
                 "MAX REPEL mantem",
                 "POKéMON fracos",
                 "longe de você.",
                 "E o mais duradouro",
                 "dos sprays",
                 "REPEL."),
    "53:4e3b": L("53:4e3b",  # 8
                 "No fundo do longe",
                 "INDIGO PLATEAU",
                 "e a LIGA POKéMON",
                 "Ouvi os melhores",
                 "treinadores vão",
                 "de todo o pais.",
                 "Quero ir lá",
                 "um dia."),
    "53:4eb3": L("53:4eb3",  # 7
                 "Havia um golpe",
                 "que eu tinha que",
                 "ensinar ao meu",
                 "POKéMON.",
                 "Então pedi ao",
                 "APAGADOR DE GOLPES",
                 "esquecer um HM."),
    "53:c047": L("53:c047",  # 3
                 "mesmo que seu",
                 "POKéMON tenha",
                 "desmaiado."),
}
