# -*- coding: utf-8 -*-
"""Lote 23 -- bancos 45 e 46: o esconderijo ninja, as senhas e o subterraneo.

O GINASIO de ECRUTEAK com os paineis de teleporte, os ROCKET GRUNTS que
guardam a sala do chefe e soltam as senhas quando perdem, e o
GOLDENROD UNDERGROUND com as persianas.

Ficam no original: TEAM ROCKET, GRUNT, GIOVANNI, SILPH, SLOWPOKETAIL,
RATICATE TAIL, HM06, ANTHONY, ROUTE 33, HIKER, POKéDEX, UNDERGROUND
WAREHOUSE.
"""
from pt.estrutura import linhas as L

DIALOGO = {
    # ---------------- o esconderijo ninja ----------------
    "45:4876": L("45:4876",
                 "Isto já foi um",
                 "esconderijo ninja",
                 "Tem armadilhas",
                 "para confundir",
                 "invasores."),
    "45:48d1": L("45:48d1",
                 "Está bem. Vou",
                 "contar um segredo",
                 "do esconderijo.",
                 "Aquilo no chão ali",
                 "na frente é um",
                 "painel de salto",
                 "Se você pisar,",
                 "vai ser mandado",
                 "de volta para a",
                 "entrada."),
    "45:4972": L("45:4972",
                 "Heheh. Está se",
                 "achando sortudo?",
                 "Vai lá, dê mais",
                 "um passo.",
                 "Temos armadilhas",
                 "postas no chão!"),
    "45:49d6": L("45:49d6",
                 "Eu nem sei onde",
                 "as armadilhas",
                 "estão.",
                 "Você vai ter que",
                 "juntar coragem",
                 "e caminhar."),
    "45:559e": L("45:559e", "{PLAYER} recebeu", "o HM06."),

    # ---------------- os GRUNTS e as senhas ----------------
    "45:57da": L("45:57da",
                 "A porta não",
                 "abre?",
                 "Ora, claro.",
                 "Precisa de uma",
                 "senha que só a",
                 "TEAM ROCKET sabe."),
    "45:5840": L("45:5840",
                 "Heh, eu sou só um",
                 "GRUNT.",
                 "Eu não sei a",
                 "senha. Azar",
                 "o seu."),
    "45:5882": L("45:5882",
                 "Ah, uma criança?",
                 "Não gosto disso,",
                 "mas tenho que",
                 "eliminar você."),
    "45:58d2": L("45:58d2",
                 "Eu apanhei de uma",
                 "criança na última",
                 "missão também.",
                 "Quando a gente",
                 "estava roubando",
                 "POKéMON, um garoto",
                 "ruivo de olhar",
                 "mau me",
                 "arrasou…"),
    "45:5968": L("45:5968", "Seu pestinha", "insuportável!"),
    "45:5989": L("45:5989",
                 "Heh, só o chefe",
                 "sabe a senha",
                 "daquela porta.",
                 "Onde está o chefe?",
                 "Sei lá. Vá",
                 "procurar você."),
    "45:6265": L("45:6265",
                 "Se eu sei a",
                 "senha?",
                 "Talvez.",
                 "Mas nenhum fracote",
                 "vai conseguir!"),
    "45:62a7": L("45:62a7", "Está bem. Pare.", "Eu conto."),
    "45:62c7": L("45:62c7",
                 "A senha da sala",
                 "do chefe é",
                 "SLOWPOKETAIL.",
                 "Mas não adianta",
                 "se você não tiver",
                 "as duas senhas."),
    "45:6327": L("45:6327",
                 "Ruarrr-rarr-rarr!",
                 "Você está me",
                 "desafiando?",
                 "Hah! Você é louco,",
                 "mas tem coragem!",
                 "Disso eu gosto!",
                 "Se me vencer, eu",
                 "conto para você",
                 "uma senha da sala",
                 "do chefe!"),
    "45:63cd": L("45:63cd", "Ruarrr-rarr-rarr!", "Você é bom!"),
    "45:63ed": L("45:63ed",
                 "Ruarrr-rarr-rarr!",
                 "A senha da sala",
                 "do chefe…",
                 "Ahn…, eu acho que",
                 "é RATICATE TAIL."),

    # ---------------- o cientista da TEAM ROCKET ----------------
    "45:6443": L("45:6443",
                 "Eu trabalhava na",
                 "SILPH, mas agora",
                 "chefio a pesquisa",
                 "da TEAM ROCKET.",
                 "Uma criança xereta",
                 "como você precisa",
                 "ser punida."),
    "45:64b8": L("45:64b8", "Um mero erro de", "tática me custou…"),
    "45:64d8": L("45:64d8",
                 "Um sinal de rádio",
                 "que enlouquece os",
                 "POKéMON…",
                 "Meu experimento é",
                 "um sucesso total.",
                 "Minha promoção",
                 "está garantida.",
                 "Esta derrota não",
                 "significa nada."),
    "45:6562": L("45:6562",
                 "Não ligo se os",
                 "POKéMON sofrem",
                 "com a experiência"),
    "45:6595": L("45:6595",
                 "Pensar é o meu",
                 "forte, não",
                 "batalhar."),
    "45:65c0": L("45:65c0",
                 "Se aumentarmos a",
                 "potência do sinal",
                 "de rádio para",
                 "transmitir longe…",
                 "Só de pensar já",
                 "me anima!"),

    # ---------------- treinadores diversos ----------------
    "46:4334": L("46:4334",
                 "Acho que tenho que",
                 "fazer as coisas",
                 "direito…"),
    "46:4362": L("46:4362",
                 "Você leva o tipo",
                 "em conta durante",
                 "a batalha?",
                 "Se souber as",
                 "vantagens do tipo",
                 "vai se sair melhor",
                 "na batalha."),
    "46:43d8": L("46:43d8",
                 "Eu sei as vanta-",
                 "gens de tipo.",
                 "Mas eu só uso um",
                 "tipo de POKéMON."),
    "46:441a": L("46:441a",
                 "Meus POKéMON",
                 "acabaram de tosar",
                 "Vou mostrar como",
                 "eles são fortes!"),
    "46:4462": L("46:4462",
                 "Seus POKéMON vão",
                 "gostar mais de",
                 "você se der um",
                 "trato no pelo."),
    "46:449b": L("46:449b",
                 "Acho que você tem",
                 "uns POKéMON raros",
                 "aí com você.",
                 "Deixe eu ver!"),
    "46:44d7": L("46:44d7", "Gaah! Eu perdi!", "Que raiva!"),
    "46:44f9": L("46:44f9",
                 "Está fazendo uma",
                 "POKéDEX? Aqui vai",
                 "uma dica boa.",
                 "O HIKER da ROUTE",
                 "33, o ANTHONY, é",
                 "gente boa.",
                 "Ele te liga se vir",
                 "algum POKéMON",
                 "raro."),

    # ---------------- as persianas do subterraneo ----------------
    "46:51f5": L("46:51f5",
                 "Abre uma persiana,",
                 "outra fecha.",
                 "Aposto que não",
                 "chega onde quer!"),
    "46:5239": L("46:5239", "Droga! Afundei", "por indecisão!"),
    "46:525a": L("46:525a",
                 "Eu também estou",
                 "confuso… O botão",
                 "da ponta é o que",
                 "se aperta antes…"),
    "46:52a2": L("46:52a2",
                 "Kwahaha!",
                 "Confuso com as",
                 "persianas, né?",
                 "Eu conto um",
                 "segredo se você",
                 "me vencer!"),
    "46:5311": L("46:5311",
                 "Certo. Uma dica!",
                 "Mude a ordem em",
                 "que você aperta.",
                 "Isso muda o jeito",
                 "que as persianas",
                 "abrem e fecham."),

    # ---------------- os ROCKET GRUNTS do subterraneo ----------------
    "46:5378": L("46:5378", "Passe as suas", "coisas para cá!"),
    "46:5399": L("46:5399",
                 "Roubar e vender!",
                 "É o básico do",
                 "crime, colega!"),
    "46:53c5": L("46:53c5",
                 "Abandonaram esta",
                 "obra antes de",
                 "terminar.",
                 "Estou procurando",
                 "o que sobrou."),
    "46:5425": L("46:5425",
                 "UNDERGROUND WARE-",
                 "HOUSE?",
                 "Para que você",
                 "quer ir lá?",
                 "Não tem nada",
                 "lá embaixo."),
    "46:547c": L("46:547c",
                 "Não ligo se você",
                 "está perdido.",
                 "Apareceu aqui,",
                 "virou vítima e",
                 "pronto!"),
    "46:54c6": L("46:54c6", "Urk! É, se acha", "esperto, hein?"),
    "46:54e9": L("46:54e9",
                 "Você tem sangue",
                 "de gelo para",
                 "peitar a ROCKET."),
    "46:5535": L("46:5535",
                 "Está perdido? Não,",
                 "não pode estar.",
                 "Você não tem",
                 "cara de assustado",
                 "Vou te dar",
                 "um motivo para",
                 "se assustar!"),
    "46:55b0": L("46:55b0",
                 "Vá para onde você",
                 "quiser! Some!",
                 "Não estou nem aí!"),
    "46:59fd": L("46:59fd", "Ele acabou comigo"),
    "46:5a11": L("46:5a11",
                 "A TEAM ROCKET vai",
                 "seguir em frente,",
                 "esperando a volta",
                 "do GIOVANNI.",
                 "Faremos o que for",
                 "preciso."),
    "46:5a70": L("46:5a70",
                 "Você não passa",
                 "daqui!",
                 "Não tenho piedade",
                 "dos inimigos, nem",
                 "dos pirralhos!"),
    "46:5aca": L("46:5aca",
                 "Eu perdi…",
                 "Por favor me",
                 "perdoe, GIOVANNI!"),
}
