# -*- coding: utf-8 -*-
"""Lote 8a -- MAHOGANY TOWN, o GINASIO do PRYCE, a loja da vovo e as
rotas 42 e 43.

Traduzido a partir do ingles original.  Chave = ponteiro da ROM USA.

Escrito com `linhas()`: eu ponho so o texto e os separadores vem do
ingles -- ver pt/estrutura.py.

Ficam de fora as placas que so tem nome proprio ("ROUTE 42 / ECRUTEAK
CITY - MAHOGANY TOWN"), que sairiam identicas, alem de kana e fragmentos.

Ficam no original: PRYCE, LANCE, DRAGONITE, HYPER BEAM, GYARADOS,
MAGIKARP, RAGECANDYBAR, GLACIERBADGE, WHIRLPOOL, ICY WIND, SPECIAL,
LAKE OF RAGE, MOUNT MORTAR, WATERFALL CAVE, POKéMON MUSIC.
"""
from pt.estrutura import linhas as L

DIALOGO = {
    # ---------------- A loja de fachada da TEAM ROCKET ----------------
    "45:4126": L("45:4126",
                 "Arrgh… Você achou",
                 "a escada",
                 "secreta…"),
    "45:414f": L("45:414f",
                 "Heheh! O experi-",
                 "mento funcionou",
                 "que é uma beleza.",
                 "MAGIKARP não valem",
                 "nada, mas",
                 "GYARADOS dão muito",
                 "dinheiro."),
    "45:41bc": L("45:41bc",
                 "Urrgh…",
                 "Os POKéMON dragão",
                 "dele são fortes…"),
    "45:41e5": L("45:41e5",
                 "LANCE: DRAGONITE,",
                 "HYPER BEAM."),
    "45:4204": L("45:4204",
                 "Por que demorou,",
                 "{PLAYER}?",
                 "Como eu pensei, o",
                 "sinal de rádio",
                 "estranho vem",
                 "daqui."),
    "45:4259": L("45:4259",
                 "A escada está",
                 "bem aqui."),
    "45:4275": L("45:4275",
                 "LANCE: {PLAYER},",
                 "vamos nos separar",
                 "para vasculhar.",
                 "Eu vou primeiro."),

    # ---------------- Mahogany Town ----------------
    "49:4b65": L("49:4b65",
                 "Oi, garotinho! Vi",
                 "que você é novo em",
                 "MAHOGANY TOWN.",
                 "Já que é novo aqui",
                 "tem que provar um",
                 "delicioso RAGE-",
                 "CANDYBAR!",
                 "Agora mesmo, é seu",
                 "por apenas",
                 "¥300! Quer um?"),
    "49:4c03": L("49:4c03", "Ótimo! Aproveite!"),
    "49:4c14": L("49:4c14",
                 "Você não tem",
                 "dinheiro."),
    "49:4c31": L("49:4c31", "Ah, tudo bem…"),
    "49:4c41": L("49:4c41",
                 "Você não tem",
                 "espaço para isto."),
    "49:4c5f": L("49:4c5f",
                 "O RAGECANDYBAR",
                 "esgotou.",
                 "Estou fechando.",
                 "Não me amole,",
                 "garotinho."),
    "49:4ca2": L("49:4ca2",
                 "Vai lá ver o",
                 "GYARADOS em fúria",
                 "no LAKE?"),
    "49:4cda": L("49:4cda",
                 "Os MAGIKARP",
                 "voltaram para o",
                 "LAKE OF RAGE.",
                 "Deve ser uma boa",
                 "notícia para os",
                 "pescadores de lá."),
    "49:4d33": L("49:4d33",
                 "Já que veio até",
                 "aqui, aproveite",
                 "para passear um",
                 "pouco.",
                 "Vá para o norte",
                 "e dê uma olhada",
                 "no LAKE OF RAGE",
                 "agora mesmo."),
    "49:4daf": L("49:4daf",
                 "Visite a loja da",
                 "Vovó. Ela vende",
                 "coisas que mais",
                 "ninguém tem."),
    "49:4deb": L("49:4deb",
                 "MAHOGANY TOWN",
                 "Bem-vindo ao Lar",
                 "dos Ninjas"),
    "49:4e1b": L("49:4e1b",
                 "Em MAHOGANY TOWN,",
                 "Prove um",
                 "RAGECANDYBAR!"),
    "49:4e4e": L("49:4e4e",
                 "MAHOGANY TOWN",
                 "GINÁSIO POKéMON",
                 "LÍDER: PRYCE",
                 "O Mestre da",
                 "Dureza do Inverno"),

    # ---------------- Rotas 42 e 43 ----------------
    "4c:5e16": L("4c:5e16",
                 "MOUNT MORTAR",
                 "WATERFALL CAVE",
                 "Interior"),
    "4c:5e3a": L("4c:5e3a",
                 "MOUNT MORTAR",
                 "WATERFALL CAVE",
                 "Interior"),
    "4d:45bd": L("4d:45bd",
                 "TRAINER TIPS",
                 "Todo POKéMON tem",
                 "prós e contras",
                 "conforme o tipo",
                 "dele.",
                 "Se os tipos são",
                 "diferentes, um de",
                 "nível mais alto",
                 "pode até perder.",
                 "Aprenda que tipos",
                 "são fortes e",
                 "fracos contra o",
                 "seu POKéMON."),

    # ---------------- Casa do GYARADOS vermelho ----------------
    "51:526c": L("51:526c",
                 "Ouvi que apareceu",
                 "um GYARADOS ver-",
                 "melho no LAKE.",
                 "É estranho, pois",
                 "até GYARADOS",
                 "comuns são raros",
                 "naquele lago…"),
    "51:52de": L("51:52de",
                 "Meu programa de",
                 "rádio favorito? O",
                 "POKéMON MUSIC."),
    "51:530d": L("51:530d",
                 "Ando ouvindo",
                 "risadas no",
                 "rádio…",
                 "É arrepiante."),

    # ---------------- Ginasio do PRYCE ----------------
    "51:445a": L("51:445a",
                 "Foi um encontro",
                 "imediato de tipo",
                 "desconhecido!"),
    "51:545d": L("51:545d",
                 "POKéMON vivem",
                 "muitas coisas na",
                 "vida deles, assim",
                 "como nós.",
                 "Eu também já vi",
                 "e sofri muito",
                 "na minha vida.",
                 "Como sou mais",
                 "velho, deixe eu",
                 "mostrar o que é.",
                 "Estou com POKéMON",
                 "desde antes",
                 "de você",
                 "nascer.",
                 "Eu não perco",
                 "fácil.",
                 "Eu, PRYCE, o",
                 "treinador do",
                 "inverno, vou",
                 "mostrar meu poder"),
    "51:5583": L("51:5583",
                 "Ah, estou impres-",
                 "sionado com você.",
                 "Com essa vontade",
                 "forte, você vai",
                 "superar todos os",
                 "obstáculos.",
                 "Você é digno",
                 "desta BADGE!"),
    "51:560b": L("51:560b",
                 "{PLAYER} recebeu",
                 "a GLACIERBADGE."),
    "51:5625": L("51:5625",
                 "Essa BADGE aumenta",
                 "os status SPECIAL",
                 "dos POKéMON.",
                 "Ela também deixa",
                 "seu POKéMON usar",
                 "WHIRLPOOL para",
                 "cruzar redemoinho",
                 "E isto… Isto é um",
                 "presente meu!"),
    "51:56bf": L("51:56bf",
                 "Essa TM contém o",
                 "ICY WIND.",
                 "Ele causa dano e",
                 "reduz VELOCIDADE.",
                 "Ele demonstra",
                 "a dureza do",
                 "inverno."),
    "51:5729": L("51:5729",
                 "Quando o gelo e a",
                 "neve derretem, a",
                 "primavera chega.",
                 "Você e seus POKé-",
                 "MON vão ficar",
                 "juntos por muitos",
                 "anos ainda.",
                 "Valorize o tempo",
                 "de vocês!"),
    "51:5a8f": L("51:5a8f",
                 "O PRYCE é veterano",
                 "e treina POKéMON",
                 "há uns",
                 "50 anos.",
                 "Dizem que ele é",
                 "bom em congelar",
                 "adversários com",
                 "golpes de gelo.",
                 "Ou seja, você tem",
                 "que derreter ele",
                 "com sua ambição",
                 "em chamas!"),
    "51:5b45": L("51:5b45",
                 "O PRYCE é bom,",
                 "mas você é de",
                 "outro nível!",
                 "Foi uma batalha",
                 "quente que",
                 "uniu duas",
                 "gerações!"),
}
