# -*- coding: utf-8 -*-
"""Lote 30 -- sobras dos bancos 00, 42, 43, 44, 46, 47, 49, 4a e 4b:
a SPROUT TOWER e o ELDER, o RIVAL no caminho, os caçadores de insetos
da rota 36, as RUINS DE ALPH e o UNOWN, o farol do AMPHY com a
JASMINE, o RADIO TOWER e o DIRECTOR, o KARATE KING e o TYROGUE, a
CLAIR e o RISINGBADGE, o SANTUÁRIO DRAGÃO e os sinais de KANTO/JOHTO.

Ficam no original: nomes próprios de lugares, pessoas, itens e a
palavra POKéMON; o resto da caixa é tradução minha, a partir do
inglês original do jogo.
"""
from pt.estrutura import linhas as L

DIALOGO = {
    '00:2815': L('00:2815',
                 'Evento de objeto.',
                 ),
    '42:43cc': L('42:43cc',
                 'Estátua de POKé-',
                 'MON… Ela parece',
                 'muito distinta.',
                 ),
    '42:452b': L('42:452b',
                 'ELDER: Você é',
                 'muito habilidoso',
                 'como treinador.',
                 'Como prometi,',
                 'aqui está a HM.',
                 'Mas quero dizer:',
                 'você deve cuidar',
                 'bem dos seus',
                 'POKéMON.',
                 'Seu jeito de',
                 'batalhar é duro',
                 'POKéMON não são',
                 'armas de guerra…',
                 ),
    '42:45f0': L('42:45f0',
                 '…',
                 '…Humf!',
                 'Ele se diz o',
                 'ELDER, mas é',
                 'fraco.',
                 'Faz sentido.',
                 'Jamais perderia',
                 'pra tolos que',
                 'falam de ser',
                 'legais com os',
                 'POKéMON.',
                 'Só me importam',
                 'POKéMON fortes,',
                 'que sabem vencer.',
                 'Não me importo',
                 'nem um pouco com',
                 'POKéMON fracos.',
                 ),
    '42:46cc': L('42:46cc',
                 '{RIVAL} usou uma',
                 'CORDA DE FUGA!',
                 ),
    '42:46e4': L('42:46e4',
                 'Que bom você',
                 'ter vindo!',
                 'A SPROUT TOWER,',
                 'lugar de treino.',
                 'Pessoas e POKéMON',
                 'testam seus laços',
                 'para construir',
                 'um futuro juntos.',
                 'Sou o teste',
                 'final.',
                 'Deixe-me ver',
                 'os laços entre',
                 'você e seus',
                 'POKéMON!',
                 ),
    '42:47b6': L('42:47b6',
                 'Ah, excelente!',
                 ),
    '42:47c6': L('42:47c6',
                 'Você e seus POKé-',
                 'MON não terão',
                 'problema em',
                 'usar esse golpe.',
                 'Leve esta HM de',
                 'FLASH.',
                 ),
    '42:4817': L('42:4817',
                 'FLASH ilumina',
                 'até os lugares',
                 'mais escuros.',
                 'Mas, para usar',
                 'fora de batalha,',
                 'precisa do BADGE',
                 'de VIOLET CITY.',
                 ),
    '42:488c': L('42:488c',
                 'Espero que você',
                 'aprenda e cresça',
                 'com a jornada.',
                 ),
    '42:4a38': L('42:4a38',
                 'É uma pintura',
                 'poderosa de um',
                 'BELLSPROUT.',
                 ),
    '42:4a62': L('42:4a62',
                 'Estátua de POKé-',
                 'MON… Ela parece',
                 'muito distinta.',
                 ),
    '42:552a': L('42:552a',
                 'Bando de DIGLETT',
                 'pulou do chão!',
                 'Isso foi',
                 'chocante!',
                 ),
    '42:562d': L('42:562d',
                 '…… …… ……',
                 'Faz tempo, hein,',
                 '{PLAYER}.',
                 '…Desde que perdi',
                 'pra você, pensei',
                 'no que faltava',
                 'aos meus',
                 'POKéMON…',
                 'E chegamos a',
                 'uma resposta.',
                 '{PLAYER}, agora',
                 'vamos te mostrar!',
                 ),
    '42:56c5': L('42:56c5',
                 '…… …… ……',
                 'Pensei que meus',
                 'POKéMON eram',
                 'os melhores que',
                 'podiam ser…',
                 '…Mas ainda',
                 'não bastou…',
                 ),
    '42:5722': L('42:5722',
                 '…… …… ……',
                 '…Você venceu,',
                 'de forma justa.',
                 'Admito. Mas',
                 'isto não é',
                 'o fim.',
                 'Vou me tornar o',
                 'maior treina-',
                 'dor de POKéMON.',
                 'Porque esses caras',
                 'estão comigo.',
                 '…Escute, {PLAYER}.',
                 'Um dia desses,',
                 'vou provar',
                 'o quanto sou bom',
                 'derrotando você.',
                 ),
    '42:5808': L('42:5808',
                 '…… …… ……',
                 'Quitei minha',
                 'dívida com você.',
                 'Com meus POKéMON,',
                 'vou derrotar o',
                 'CAMPEÃO e me',
                 'tornar o melhor',
                 'do mundo.',
                 ),
    '42:5a87': L('42:5a87',
                 'Espera aí.',
                 '…Vai encarar o',
                 'desafio da LIGA',
                 'POKéMON?',
                 '…Não me faça',
                 'rir.',
                 'Você é bem mais',
                 'fraco que eu.',
                 'Não sou como',
                 'antes.',
                 'Agora tenho os',
                 'melhores e mais',
                 'fortes POKéMON.',
                 'Sou invencível!',
                 '{PLAYER}!',
                 'Eu te desafio!',
                 ),
    '42:5b65': L('42:5b65',
                 '…Não venci…',
                 'Dei tudo o que',
                 'tinha…',
                 'O que você tem,',
                 'e o que me falta…',
                 'Começo a entender',
                 'o que aquele',
                 'mestre de dragões',
                 'me disse…',
                 ),
    '42:5bf6': L('42:5bf6',
                 '…Não desisti',
                 'de me tornar o',
                 'maior treinador…',
                 'Vou descobrir',
                 'por que não',
                 'consigo vencer',
                 'e ser mais forte…',
                 'Quando descobrir,',
                 'eu te desafio.',
                 'E vou te derrotar',
                 'com toda a minha',
                 'força.',
                 '…Humf! Continue',
                 'até lá.',
                 ),
    '42:5cd2': L('42:5cd2',
                 '…Humf!',
                 'No fim das',
                 'contas, nada',
                 'vence a força.',
                 'Não preciso de',
                 'mais nada.',
                 ),
    '42:e700': L('42:e700',
                 'E você?',
                 ),
    '43:48e0': L('43:48e0',
                 'DON: Vou',
                 'vencer! Não me',
                 'atrapalhe.',
                 ),
    '43:4907': L('43:4907',
                 'ED: Meu PARASECT',
                 'faz POKéMON',
                 'dormir com SPORE.',
                 ),
    '43:4937': L('43:4937',
                 'NICK: Crio',
                 'POKéMON rápidos',
                 'para batalhas.',
                 ),
    '43:4960': L('43:4960',
                 'WILLIAM: Não me',
                 'importo em',
                 'vencer.',
                 'Só procuro',
                 'POKéMON raros.',
                 ),
    '43:49a9': L('43:49a9',
                 'BENNY: Ssh!',
                 'Vai espantar o',
                 'SCYTHER. Falo',
                 'com você depois.',
                 ),
    '43:49e6': L('43:49e6',
                 'BARRY: Você',
                 'deve enfraquecer',
                 'POKéMON inseto,',
                 'jogue POKé BALL.',
                 ),
    '43:4a25': L('43:4a25',
                 'CINDY: O que foi?',
                 'Acha engraçado',
                 'uma garota',
                 'caçando POKéMON',
                 'inseto?',
                 ),
    '43:4a70': L('43:4a70',
                 'JOSH: Coleciono',
                 'POKéMON inseto',
                 'desde que era',
                 'bem criança.',
                 'Não tem jeito,',
                 'vou vencer!',
                 ),
    '43:4acd': L('43:4acd',
                 'SAMUEL: Se tem',
                 'tempo para',
                 'conversar, procure',
                 'POKéMON inseto.',
                 ),
    '43:4b0c': L('43:4b0c',
                 'KIPP: Estudei',
                 'muito sobre',
                 'POKéMON inseto.',
                 'Vou vencer',
                 'com certeza.',
                 ),
    '43:4b4f': L('43:4b4f',
                 'RELAXATION SQUARE',
                 'NATIONAL PARK',
                 ),
    '43:4b70': L('43:4b70',
                 'O que é este',
                 'aviso?',
                 'Batalhe apenas',
                 'na grama.',
                 'NATIONAL PARK',
                 "WARDEN'S OFFICE",
                 ),
    '43:4bc5': L('43:4bc5',
                 'DICAS DE TREINO',
                 'Imprima MAIL',
                 'abrindo-o e',
                 'apertando START.',
                 ),
    '43:9346': L('43:9346',
                 'FLASH!',
                 ),
    '44:409f': L('44:409f',
                 'Hm? Isso é uma',
                 'POKéDEX, não é?',
                 'Posso ver?',
                 'Há muitos',
                 'tipos de POKéMON.',
                 'Hm? O que é isto?',
                 'Que POKéMON',
                 'é este?',
                 'Parece a escrita',
                 'estranha nas',
                 'paredes das',
                 'RUINS.',
                 'Se esses desenhos',
                 'são mesmo POKé-',
                 'MON, deve haver',
                 'muitos mais.',
                 'Sei! Vou',
                 'atualizar sua',
                 'POKéDEX. Siga-me.',
                 ),
    '44:42fd': L('44:42fd',
                 'MYSTERY STONE',
                 'PANEL CHAMBER',
                 ),
    '44:443c': L('44:443c',
                 'É uma réplica',
                 'de um POKéMON',
                 'antigo.',
                 ),
    '44:4461': L('44:4461',
                 'Um POKéMON que',
                 'voava com',
                 'elegância em',
                 'asas coloridas.',
                 ),
    '44:4516': L('44:4516',
                 'Bem-vindo a esta',
                 'câmara.',
                 'Há painéis',
                 'deslizantes que',
                 'retratam um',
                 'POKéMON antigo.',
                 'Deslize os',
                 'painéis para',
                 'formar a figura.',
                 'À direita, a',
                 'descrição do',
                 'POKéMON.',
                 ),
    '44:45cb': L('44:45cb',
                 'É uma réplica',
                 'de um POKéMON',
                 'antigo.',
                 ),
    '44:45f0': L('44:45f0',
                 'Um POKéMON que',
                 'se escondia no',
                 'fundo do mar.',
                 'olhos nas costas.',
                 ),
    '44:46bb': L('44:46bb',
                 'É uma réplica',
                 'de um POKéMON',
                 'antigo.',
                 ),
    '44:46e0': L('44:46e0',
                 'Este POKéMON',
                 'flutuava no mar,',
                 'girando seus',
                 'dez tentáculos.',
                 ),
    '44:4795': L('44:4795',
                 'É uma réplica',
                 'de um POKéMON',
                 'antigo.',
                 ),
    '44:47ba': L('44:47ba',
                 'Este POKéMON',
                 'voador atacava',
                 'a presa com',
                 'dentes de serra.',
                 ),
    '44:484a': L('44:484a',
                 'Há uma presença',
                 'estranha aqui…',
                 ),
    '44:486d': L('44:486d',
                 'Esta sala é',
                 'grande, mas não',
                 'há nada aqui.',
                 ),
    '44:489b': L('44:489b',
                 'Este lugar tem',
                 'uma qualidade',
                 'mística.',
                 'Parece até',
                 'etéreo.',
                 ),
    '44:48e5': L('44:48e5',
                 'Prédios antigos',
                 'são túmulos de',
                 'reis.',
                 'Como as',
                 'pirâmides.',
                 ),
    '44:4933': L('44:4933',
                 'É uma réplica',
                 'de um POKéMON',
                 'antigo.',
                 ),
    '44:4b1e': L('44:4b1e',
                 'Pronto!',
                 'Modifiquei sua',
                 'POKéDEX.',
                 'Adicionei uma',
                 'POKéDEX opcional',
                 'para guardar',
                 'dados de UNOWN.',
                 'Ela registra',
                 'na ordem em',
                 'que os pegou.',
                 ),
    '44:4bb7': L('44:4bb7',
                 'Os UNOWN que',
                 'você pegar serão',
                 'todos registrados',
                 'Verifique quantos',
                 'tipos existem.',
                 ),
    '44:4c05': L('44:4c05',
                 'Você pegou todos',
                 'os UNOWN?',
                 'Que grande',
                 'conquista!',
                 'Preparei a',
                 'impressora para',
                 'lidar com UNOWN.',
                 'Use quando',
                 'quiser.',
                 ),
    '44:4eae': L('44:4eae',
                 'POKéMON misterioso',
                 'Nome: UNOWN',
                 'Um total de 26',
                 'tipos achados.',
                 ),
    '44:4ee3': L('44:4ee3',
                 'Parece que ainda',
                 'não funciona.',
                 ),
    '44:4f02': L('44:4f02',
                 'UNOWN podem',
                 'ser impressos.',
                 ),
    '44:6182': L('44:6182',
                 'Espero o momento',
                 'de evolução do',
                 'SLOWPOKE.',
                 'Pelas minhas',
                 'observações,',
                 'descobri algo.',
                 'Um SLOWPOKE com',
                 "uma KING'S ROCK",
                 'é mordido por',
                 'um SHELLDER.',
                 'Aqui, vou te',
                 "dar uma KING'S",
                 'ROCK.',
                 ),
    '44:624a': L('44:624a',
                 'Vou ser como',
                 'o SLOWPOKE.',
                 'Esperarei com',
                 'paciência para',
                 'ver um evoluir.',
                 ),
    '44:6dbd': L('44:6dbd',
                 'JASMINE: … Este',
                 'POKéMON sempre',
                 'manteve o mar',
                 'aceso à noite.',
                 '…Mas ele',
                 'adoeceu… Está',
                 'ofegando…',
                 '…Sei que há',
                 'uma ótima',
                 'PHARMACY em',
                 'CIANWOOD…',
                 'Mas isso fica',
                 'além do mar…',
                 'E não posso',
                 'deixar o AMPHY…',
                 ),
    '44:6ea0': L('44:6ea0',
                 '…Pode buscar',
                 'um remédio para',
                 'mim? Por favor?',
                 ),
    '44:6ed5': L('44:6ed5',
                 'JASMINE: …Este',
                 'remédio curará',
                 'o AMPHY?',
                 ),
    '44:6eff': L('44:6eff',
                 '{PLAYER} entregou',
                 'a SECRETPOTION',
                 'a JASMINE.',
                 ),
    '44:6f26': L('44:6f26',
                 'JASMINE: …Hum,',
                 'não se ofenda,',
                 'por favor…',
                 '…AMPHY não',
                 'aceitará nada',
                 'de mais ninguém…',
                 ),
    '44:6f80': L('44:6f80',
                 'JASMINE: …',
                 'AMPHY, como você',
                 'se sente?',
                 ),
    '44:6fa8': L('44:6fa8',
                 'JASMINE: …Oh,',
                 'que alívio…',
                 'É tão',
                 'maravilhoso…',
                 'Muito, muito',
                 'obrigada.',
                 '…Voltarei',
                 'ao GYM…',
                 ),
    '44:701b': L('44:701b',
                 'JASMINE: …Vejo…',
                 ),
    '44:702d': L('44:702d',
                 '…AMPHY, aguenta!',
                 ),
    '44:7055': L('44:7055',
                 'A respiração',
                 'está difícil…',
                 ),
    '46:4e67': L('46:4e67',
                 'Espera aí!',
                 'Te vi, então',
                 'te segui.',
                 'Não preciso de',
                 'você atrapalhando',
                 'enquanto cuido',
                 'da TEAM ROCKET.',
                 '…Espera aí.',
                 'Você me venceu',
                 'antes, não foi?',
                 'Aquilo foi',
                 'só sorte.',
                 'Mas eu pago',
                 'minhas dívidas!',
                 ),
    '46:4f27': L('46:4f27',
                 '…Por quê…',
                 'Por que perco?',
                 'Juntei os POKéMON',
                 'mais fortes.',
                 'Não aliviei',
                 'no ritmo.',
                 'Por que perco?',
                 ),
    '46:4f8c': L('46:4f8c',
                 '…Não enten-',
                 'do…',
                 'É verdade o que',
                 'o LANCE disse?',
                 'Que não trato',
                 'bem os POKéMON?',
                 'Amor…',
                 'Confiança…',
                 'São mesmo',
                 'o que me falta?',
                 'Será que me',
                 'impedem?',
                 'Eu… só não',
                 'entendo.',
                 'Mas não vai',
                 'terminar aqui.',
                 'Agora não.',
                 'Não por isso.',
                 'Não vou desistir',
                 'do sonho de',
                 'ser o melhor',
                 'mestre POKéMON!',
                 ),
    '46:50cc': L('46:50cc',
                 'Humf. Este é o',
                 'meu poder real.',
                 'Vou acabar com',
                 'a TEAM ROCKET.',
                 'E vou',
                 'esmagar o LANCE',
                 'sob meus pés.',
                 ),
    '46:5140': L('46:5140',
                 'Fui desafiado',
                 'para uma batalha',
                 'lá embaixo.',
                 'É perigoso',
                 'lá. Melhor',
                 'tomar cuidado.',
                 ),
    '46:519a': L('46:519a',
                 'Há lojas',
                 'lá embaixo…',
                 'Mas também',
                 'há treinadores.',
                 'Tenho medo',
                 'de descer.',
                 ),
    '46:551e': L('46:551e',
                 'Está escrito',
                 'SWITCH 1.',
                 ),
    '46:55e1': L('46:55e1',
                 'Está DESLIGADO.',
                 'Ligar?',
                 ),
    '46:55f7': L('46:55f7',
                 'Está LIGADO.',
                 'Desligar?',
                 ),
    '46:560d': L('46:560d',
                 'Está escrito',
                 'SWITCH 2.',
                 ),
    '46:5624': L('46:5624',
                 'Está escrito',
                 'SWITCH 3.',
                 ),
    '46:563b': L('46:563b',
                 'Está escrito',
                 'EMERGÊNCIA.',
                 ),
    '46:5795': L('46:5795',
                 'Ei, garoto!',
                 'Você nos atrasa!',
                 'Nosso esquema',
                 'é trabalhar',
                 'nos bastidores,',
                 'onde ninguém vê!',
                 ),
    '46:57f7': L('46:57f7',
                 'Perco a vontade',
                 'de trabalhar se',
                 'alguém me vê.',
                 'Anda, garoto,',
                 'cai fora!',
                 ),
    '46:5840': L('46:5840',
                 'Oohah! Oohah!',
                 'As coisas no',
                 'chão são lixo.',
                 'Leve-as se',
                 'quiser!',
                 ),
    '46:5b8f': L('46:5b8f',
                 'DIRECTOR: Quem?',
                 'O quê? Você veio',
                 'me resgatar?',
                 'Obrigado!',
                 'A RADIO TOWER!',
                 'O que está',
                 'acontecendo lá?',
                 'Tomada pela',
                 'TEAM ROCKET?',
                 'Aqui. Pegue',
                 'a CARD KEY.',
                 ),
    '46:5c24': L('46:5c24',
                 'DIRECTOR: Use-a',
                 'para abrir as',
                 'persianas do 3F.',
                 ),
    '46:5c56': L('46:5c56',
                 'Imploro sua',
                 'ajuda.',
                 'Não dá pra saber',
                 'o que farão',
                 'se controlarem',
                 'o transmissor.',
                 'Eles podem',
                 'até controlar',
                 'POKéMON com',
                 'um sinal especial',
                 'Você é o único',
                 'em quem confio.',
                 'Por favor, salve',
                 'a RADIO TOWER…',
                 'E todos os',
                 'POKéMON do país!',
                 ),
    '46:5f3d': L('46:5f3d',
                 'Ei!',
                 'Eu sou o KARATE',
                 'KING!',
                 'Treino sozinho',
                 'aqui no escuro!',
                 'Você!',
                 'Batalhe comigo!',
                 'Hwaaarggh!',
                 ),
    '46:5f99': L('46:5f99',
                 'Waaaarggh!',
                 'Fui derrotado!',
                 ),
    '46:5fb0': L('46:5fb0',
                 'Estou arrasado…',
                 'Meu treino',
                 'ainda não bastou.',
                 'Mas derrota é',
                 'derrota. Admito.',
                 'Como prova de',
                 'que você venceu,',
                 'vou lhe dar um',
                 'POKéMON lutador.',
                 ),
    '46:6045': L('46:6045',
                 '{PLAYER} recebeu',
                 'TYROGUE.',
                 ),
    '46:605a': L('46:605a',
                 'TYROGUE é do',
                 'tipo lutador.',
                 'Ele evolui e',
                 'fica mais forte.',
                 'Continue firme',
                 'no treino. Eu',
                 'também sigo.',
                 'Adeus!',
                 ),
    '46:60cf': L('46:60cf',
                 'Você não tem',
                 'espaço no time!',
                 ),
    '46:6267': L('46:6267',
                 'Está cravado',
                 'no gelo.',
                 ),
    '47:438b': L('47:438b',
                 'Uau! Você me',
                 'assustou!',
                 'Estava com',
                 'BLACKGLASSES,',
                 'então não',
                 'te notei.',
                 'O que estou',
                 'fazendo aqui?',
                 'Ei, não se',
                 'preocupe.',
                 'Vou te dar',
                 'um BLACKGLASSES,',
                 'então esqueça',
                 'que me viu, ok?',
                 ),
    '47:4458': L('47:4458',
                 'BLACKGLASSES',
                 'aumenta o poder',
                 'de golpes',
                 ),
    '47:459c': L('47:459c',
                 'CLAIR: Tudo bem.',
                 'Reconheço seu',
                 'verdadeiro poder.',
                 'Este BADGE é seu',
                 ),
    '47:45e1': L('47:45e1',
                 '{PLAYER} recebeu',
                 'RISINGBADGE.',
                 ),
    '47:45fa': L('47:45fa',
                 'RISINGBADGE fará',
                 'seus POKéMON',
                 'usarem o golpe',
                 'de escalar',
                 'cachoeiras.',
                 'Além disso, todos',
                 'os POKéMON vão',
                 'te reconhecer',
                 'como treinador',
                 'e obedecer',
                 'seus comandos.',
                 'Também quero',
                 'que leve esta TM.',
                 ),
    '47:46d6': L('47:46d6',
                 'Isto contém',
                 'DRAGONBREATH.',
                 'Não, não tem',
                 'nada a ver com',
                 'minha respiração.',
                 'Se você não',
                 'quiser, não',
                 'precisa levar.',
                 ),
    '47:4754': L('47:4754',
                 'Então, você',
                 'conseguiu todos',
                 'os BADGES.',
                 'Seu destino',
                 'é a LIGA POKéMON',
                 'no INDIGO',
                 'PLATEAU.',
                 'Sabe como',
                 'chegar lá?',
                 'Daqui, vá',
                 'a NEW BARK TOWN.',
                 'Depois SURF',
                 'para o leste.',
                 'A rota é dura.',
                 'Não ouse',
                 'perder na',
                 'LIGA POKéMON!',
                 'Se perder,',
                 'vou me sentir',
                 'pior por ter',
                 'perdido pra você.',
                 ),
    '47:4881': L('47:4881',
                 'SANTUÁRIO DRAGÃO',
                 'Um santuário em',
                 'honra aos POKéMON',
                 'dragão que viveu',
                 "no DRAGON'S DEN.",
                 ),
    '47:48d6': L('47:48d6',
                 '…',
                 'O quê? {PLAYER}?',
                 '…Não, não vou',
                 'batalhar agora…',
                 'Meus POKéMON',
                 'não estão prontos',
                 'Não posso',
                 'forçá-los agora.',
                 'Preciso ser',
                 'disciplinado',
                 'para me tornar',
                 'o maior treinador',
                 ),
    '47:4980': L('47:4980',
                 '…',
                 'Ufa…',
                 'Aprenda a',
                 'se afastar.',
                 ),
    '47:49a6': L('47:49a6',
                 '{PLAYER} achou um',
                 '{STRBUF}!',
                 ),
    '47:49b8': L('47:49b8',
                 'Mas {PLAYER}',
                 'não pode levar',
                 'mais itens.',
                 ),
    '49:497e': L('49:497e',
                 'ECRUTEAK DANCE',
                 'THEATER',
                 ),
    '49:5f27': L('49:5f27',
                 'MT.SILVER',
                 ),
    '4a:4613': L('4a:4613',
                 'ROUTE 26',
                 'POKéMON LEAGUE',
                 'RECEPTION GATE',
                 ),
    '4a:486a': L('4a:486a',
                 'Ei!',
                 ),
    '4a:4870': L('4a:4870',
                 'Sabe o que você',
                 'acabou de fazer?',
                 'Você deu seu',
                 'primeiro passo',
                 'em KANTO.',
                 'Confira no',
                 'mapa da POKéGEAR',
                 ),
    '4a:4c7e': L('4a:4c7e',
                 'TOHJO FALLS',
                 'A ligação entre',
                 'KANTO e JOHTO',
                 ),
    '4a:4d53': L('4a:4d53',
                 'ROUTE 28',
                 ),
    '4b:60e1': L('4b:60e1',
                 'ROUTE 35',
                 ),
}
