# -*- coding: utf-8 -*-
"""Lote 10b: Routes 36/44/45/46 e National Park Gate"""
from pt.estrutura import linhas as L

DIALOGO = {
    "4b:6321": L("4b:6321",  # 2
                 "E uma árvore",
                 "estranha?"),
    "4b:6346": L("4b:6346",  # 2
                 "{PLAYER} usou o",
                 "SQUIRTBOTTLE."),
    "4b:6360": L("4b:6360",  # 5
                 "A árvore estranha",
                 "não gosta do",
                 "SQUIRTBOTTLE!",
                 "A árvore estranha",
                 "atacou!"),
    "4b:63a7": L("4b:63a7",  # 7
                 "Wa-hey!",
                 "Eu ia quebrar",
                 "essa árvore",
                 "com meu soco",
                 "direto.",
                 "Mas não consegui!",
                 "Sou um fracasso!"),
    "4b:6408": L("4b:6408",  # 5
                 "Você tirou",
                 "aquela árvore?",
                 "Impressionado!",
                 "Quero que você",
                 "tenha isso."),
    "4b:6464": L("4b:6464",  # 9
                 "Isso e ROCK SMASH.",
                 "Você pode quebrar",
                 "pedras com um",
                 "só golpe bem",
                 "mirado.",
                 "Se houver pedras",
                 "no seu caminho,",
                 "apenas quebre",
                 "todas!"),
    "4b:64f0": L("4b:64f0",  # 7
                 "Uma árvore",
                 "está bloqueando",
                 "o caminho para",
                 "GOLDENROD CITY.",
                 "Está me impedindo",
                 "de comprar.",
                 "Alguém deve agir."),
    "4b:6568": L("4b:6568",  # 5
                 "Aquela árvore",
                 "desapareceu sem",
                 "rastro.",
                 "Ah! Aquela árvore",
                 "era um POKéMON?"),
    "4b:66cc": L("4b:66cc",  # 4
                 "ARTHUR: Quem e",
                 "você?",
                 "Sou ARTHUR de",
                 "quinta-feira."),
    "4b:66f9": L("4b:66f9",  # 2
                 "Aqui. Você pode",
                 "ficar com isso."),
    "4b:6713": L("4b:6713",  # 6
                 "ARTHUR: Um POKéMON",
                 "que usa golpes",
                 "do tipo pedra",
                 "deveria guardar",
                 "isso.",
                 "Golpes de pedra."),
    "4b:6776": L("4b:6776",  # 4
                 "ARTHUR: Sou ARTHUR",
                 "de quinta-feira.",
                 "Sou o segundo",
                 "de sete crianças."),
    "4b:67bf": L("4b:67bf",  # 3
                 "ARTHUR: Hoje não",
                 "é quinta-feira.",
                 "Que decepção."),
    "4b:67f0": L("4b:67f0",  # 1
                 "ROTA 36"),
    "4b:67fa": L("4b:67fa",  # 2
                 "RUÍNAS DE ALPH",
                 "ENTRADA NORTE"),
    "4b:6818": L("4b:6818",  # 10
                 "TRAINER TIPS",
                 "Status de POKéMON",
                 "variam -- mesmo",
                 "dentro da mesma",
                 "espécie.",
                 "Seus status podem",
                 "ser parecidos.",
                 "Mas as diferenças",
                 "se tornar claras",
                 "conforme crescem."),
    "4b:68ba": L("4b:68ba",  # 8
                 "TRAINER TIPS",
                 "Use DIG para ir",
                 "à entrada de",
                 "qualquer lugar.",
                 "É conveniente",
                 "para explorar",
                 "cavernas e outros",
                 "lugares assim."),
    "4b:cc00": L("4b:cc00",  # 3
                 "POKéMON, e eu",
                 "posso ver que",
                 "você também e."),
    "4d:4c00": L("4d:4c00",  # 3
                 "POKéMON, e eu",
                 "posso ver que",
                 "você também e."),
    "4d:4d96": L("4d:4d96",  # 2
                 "ROTA 44",
                 "ICE PATH a frente"),
    "4d:4daf": L("4d:4daf",  # 3
                 "ROTA 44",
                 "MAHOGANY TOWN -",
                 "BLACKTHORN CITY"),
    "4d:5490": L("4d:5490",  # 2
                 "ROTA 45",
                 "MONTANHA a frente"),
    "4d:57aa": L("4d:57aa",  # 2
                 "ROTA 46",
                 "MONTANHA a frente"),
    "4d:9549": L("4d:9549",  # 3
                 "AFARI ZONE OFFICE",
                 "esta fechado até",
                 "aviso posterior."),
    "4d:d148": L("4d:d148",  # 3
                 "OWN",
                 "A Nobre Cidade",
                 "Roxa"),
    "4d:d656": L("4d:d656",  # 6
                 "tipos devem dar",
                 "uma vantagem",
                 "na batalha.",
                 "Tenho certeza que",
                 "as INSIGNIAS de",
                 "KANTO ajudarão."),
    "56:6515": L("56:6515",  # 10
                 "O Concurso de",
                 "Captura Insetos",
                 "é realizado na",
                 "terça, quinta e",
                 "sábado.",
                 "Não só você ganha",
                 "um prêmio por vir,",
                 "como também pode",
                 "ficar com um",
                 "POKéMON inseto."),
    "56:660d": L("56:660d",  # 4
                 "Não se pergunta",
                 "quem faria algo",
                 "assim?",
                 "E por que?"),
    "56:6648": L("56:6648",  # 7
                 "Você viu aquela",
                 "árvore estranha",
                 "na estrada?",
                 "Isso pode explicar",
                 "por que menos",
                 "pessoas visitam",
                 "as RUÍNAS."),
    "56:69c0": L("56:69c0",  # 12
                 "Hoje é {STRBUF}.",
                 "Isso quer dizer",
                 "o Concurso de",
                 "Captura Insetos",
                 "é hoje.",
                 "As regras são",
                 "simples.",
                 "Use um dos seus",
                 "POKéMON, capture",
                 "um POKéMON inseto",
                 "para ser julgado.",
                 "Você quer tentar?"),
    "56:6a70": L("56:6a70",  # 3
                 "Aqui estão as",
                 "PARK BALLS para",
                 "o Concurso."),
    "56:6a9a": L("56:6a9a",  # 2
                 "{PLAYER} recebeu",
                 "20 PARK BALLS."),
    "56:6ab5": L("56:6ab5",  # 16
                 "A pessoa que",
                 "capturar o",
                 "POKéMON inseto",
                 "mais forte é a",
                 "vencedora.",
                 "Você tem 20",
                 "minutos.",
                 "Se ficar sem PARK",
                 "BALLS, acabou.",
                 "Você pode ficar",
                 "com o último",
                 "POKéMON que",
                 "capturar.",
                 "Vá e capture o",
                 "POKéMON inseto",
                 "mais forte!"),
    "56:6b99": L("56:6b99",  # 9
                 "Opa\u2026",
                 "Você tem mais de",
                 "um POKéMON.",
                 "Você terá que usar",
                 "{STRBUF}, o",
                 "primeiro POKéMON",
                 "na sua equipe.",
                 "Esta tudo bem",
                 "com você?"),
    "56:6c0a": L("56:6c0a",  # 3
                 "Tudo bem. Vamos",
                 "guardar os outros",
                 "durante o teste."),
    "56:6c3e": L("56:6c3e",  # 3
                 "POKéMON de",
                 "{PLAYER} ficaram",
                 "com o HELPER."),
    "56:6c6a": L("56:6c6a",  # 4
                 "Escolha o POKéMON",
                 "para usar no",
                 "Concurso, depois",
                 "venha me ver."),
    "56:6caf": L("56:6caf",  # 3
                 "OK. Esperamos que",
                 "você participe",
                 "no futuro."),
    "56:6cdb": L("56:6cdb",  # 8
                 "Opa\u2026",
                 "O 1º POKéMON",
                 "na sua equipe",
                 "não pode lutar.",
                 "Troque-o pelo",
                 "POKéMON que quer",
                 "usar, depois",
                 "venha me ver."),
    "56:6d4f": L("56:6d4f",  # 11
                 "Opa\u2026",
                 "Sua equipe e seu",
                 "PC BOX estão",
                 "cheios.",
                 "Você não tem",
                 "onde guardar o",
                 "POKéMON inseto",
                 "que capturar.",
                 "Libere espaço na",
                 "equipe ou na BOX,",
                 "depois volte."),
    "56:6df2": L("56:6df2",  # 8
                 "Opa\u2026",
                 "Você tem um OVO",
                 "como o primeiro",
                 "POKéMON do grupo.",
                 "Troque-o pelo",
                 "POKéMON que quer",
                 "usar, depois",
                 "venha me ver."),
    "56:6e6d": L("56:6e6d",  # 4
                 "Ainda restam",
                 "{STRBUF} min.",
                 "Quer terminar",
                 "agora?"),
    "56:6eac": L("56:6eac",  # 4
                 "OK. Por favor",
                 "espere aqui pelo",
                 "anuncio dos",
                 "vencedores."),
    "56:6ee7": L("56:6ee7",  # 3
                 "OK. Volte lá fora",
                 "e termine",
                 "o que falta."),
    "56:6f12": L("56:6f12",  # 4
                 "O Concurso de hoje",
                 "acabou. Esperamos",
                 "que você participe",
                 "no futuro."),
    "56:6f57": L("56:6f57",  # 3
                 "Alguns POKéMON só",
                 "podem ser vistos",
                 "no PARQUE."),
    "56:6f80": L("56:6f80",  # 3
                 "DON: Uau, você me",
                 "venceu. Você e",
                 "muito bom."),
    "56:6fab": L("56:6fab",  # 5
                 "DON: Sorte tem uma",
                 "muita influência.",
                 "Nunca se sabe",
                 "que POKéMON vai",
                 "aparecer."),
    "56:6ff6": L("56:6ff6",  # 3
                 "ED: Invidio você.",
                 "Não consegui",
                 "desta vez."),
    "56:7027": L("56:7027",  # 2
                 "ED: Talvez você",
                 "venca com POKéMON"),
    "56:7049": L("56:7049",  # 3
                 "NICK: Muito bem!",
                 "Vou criar meus",
                 "POKéMON melhor."),
    "56:707d": L("56:707d",  # 4
                 "NICK: Talvez você",
                 "ganhe mais pontos",
                 "maior com um",
                 "POKéMON incomum."),
    "56:70c1": L("56:70c1",  # 3
                 "WILLIAM: Você e",
                 "o vencedor? O que",
                 "você capturou?"),
    "56:70f1": L("56:70f1",  # 4
                 "WILLIAM: Estou",
                 "satisfeito porque",
                 "peguei o POKéMON",
                 "que eu queria."),
    "56:7135": L("56:7135",  # 3
                 "BENNY: Parabéns!",
                 "Você ganhou meu",
                 "respeito!"),
    "56:7163": L("56:7163",  # 3
                 "BENNY: Eu capturei",
                 "um SCYTHER antes,",
                 "mas não venci."),
    "56:7197": L("56:7197",  # 3
                 "BARRY: O POKéMON",
                 "que você capturou",
                 "\u2026e incrível!"),
    "56:71c4": L("56:71c4",  # 7
                 "BARRY: É mais",
                 "vencer se você",
                 "capturar um",
                 "POKéMON inseto de",
                 "nível alto.",
                 "Mas acho que eles",
                 "olham mais coisas"),
    "56:7232": L("56:7232",  # 5
                 "CINDY: Venceu?",
                 "Que ótimo!",
                 "Você quer ir",
                 "caçar POKéMON",
                 "insetos comigo?"),
    "56:727f": L("56:727f",  # 2
                 "CINDY: Eu amo",
                 "POKéMON insetos!"),
    "56:729f": L("56:729f",  # 3
                 "JOSH: Eu\u2026 não",
                 "acredito que perdi",
                 "no concurso\u2026"),
    "56:72d0": L("56:72d0",  # 3
                 "JOSH: Ouvi que",
                 "alguém venceu",
                 "com um CATERPIE!"),
    "56:7302": L("56:7302",  # 2
                 "SAMUEL: Na próxima",
                 "vou vencer."),
    "56:7327": L("56:7327",  # 3
                 "SAMUEL: Droga.",
                 "Achei que teria",
                 "melhor pontuação\u2026"),
    "56:7356": L("56:7356",  # 4
                 "KIPP: Você pode",
                 "me dar dicas?",
                 "Quero estudar",
                 "seu estilo."),
    "56:7396": L("56:7396",  # 4
                 "KIPP: Estudo bem,",
                 "mas isso não é",
                 "suficiente para",
                 "vencer."),
    "56:74dd": L("56:74dd",  # 7
                 "Opa\u2026 Seu PACK",
                 "esta cheio.",
                 "Guardaremos seu",
                 "prêmio, mas",
                 "só por hoje.",
                 "Libere espaço,",
                 "depois volte."),
    "56:754c": L("56:754c",  # 4
                 "{PLAYER}?",
                 "Aqui esta o prêmio",
                 "que estavamos",
                 "para você."),
}
