# -*- coding: utf-8 -*-
"""Lote 21 -- banco 5b: o FAST SHIP e os treinadores da travessia.

O navio entre OLIVINE e VERMILION, com os marinheiros, as criancas em
excursao, os cavalheiros e as senhoras.

Ficam no original: FAST SHIP, MAGNET TRAIN, DEPT.STORE, DAY-CARE,
POKéMON SALON, RADIO STATION, KARATE KING, LILY, MARY, BADGES, e os
nomes de cidade e regiao.
"""
from pt.estrutura import linhas as L

DIALOGO = {
    # ---------------- os desafiantes ----------------
    "5b:4de0": L("5b:4de0", "Eu queria ganhar!"),
    "5b:4df2": L("5b:4df2",
                 "Treinadores de",
                 "JOHTO podem lutar",
                 "com os LÍDERES de",
                 "KANTO."),
    "5b:4e2a": L("5b:4e2a",
                 "Estou treinando",
                 "para ser CAMPEÃO"),
    "5b:4e4c": L("5b:4e4c",
                 "Qual é a diferença",
                 "entre nós dois?"),
    "5b:4e6e": L("5b:4e6e",
                 "Um dia eu venço",
                 "você!"),

    # ---------------- as radios ----------------
    "5b:4e8d": L("5b:4e8d",
                 "Você conhece a",
                 "LILY? Ela é uma",
                 "DJ de KANTO."),
    "5b:4ec2": L("5b:4ec2",
                 "A LILY é legal,",
                 "mas a MARY é a",
                 "melhor!",
                 "Quero conhecer as",
                 "rádios de JOHTO!"),
    "5b:4f0e": L("5b:4f0e", "Está sozinho?", "Então vamos lutar"),
    "5b:4f30": L("5b:4f30", "Isso é demais", "para mim!"),
    "5b:4f4b": L("5b:4f4b",
                 "Será que tem",
                 "alguma montanha",
                 "boa para escalar",
                 "em KANTO?"),

    # ---------------- o senhor que perdeu algo ----------------
    "5b:5068": L("5b:5068",
                 "Ah, não. Perdi uma",
                 "coisa que é muito",
                 "importante."),
    "5b:509a": L("5b:509a", "Eu… não consigo", "achar…"),
    "5b:50ae": L("5b:50ae",
                 "Desisto. Filho,",
                 "você não precisa",
                 "procurar. Esqueça",
                 "isso!"),
    "5b:50fc": L("5b:50fc", "Que azar!", "Eu perdi!"),
    "5b:5112": L("5b:5112",
                 "Achei uma moeda",
                 "bonita aqui.",
                 "Alguém deve ter",
                 "perdido…"),

    # ---------------- os cuspidores de fogo ----------------
    "5b:52a4": L("5b:52a4", "Fsss… A chama", "está fraquinha…"),
    "5b:52be": L("5b:52be",
                 "Acho que o fogo é",
                 "fraco no mar.",
                 "Não faz diferença?",
                 "Sério?"),

    # ---------------- as criancas ----------------
    "5b:52fa": L("5b:52fa",
                 "Vou visitar minha",
                 "vovó para pegar",
                 "uns insetos!"),
    "5b:5329": L("5b:5329", "Ooh, uau. Você é", "durão, cara!"),
    "5b:5347": L("5b:5347",
                 "Dá para achar um",
                 "monte de POKéMON",
                 "nas árvores!"),

    # ---------------- o coracao partido ----------------
    "5b:5379": L("5b:5379",
                 "Estou tentando",
                 "esquecer as mágoas",
                 "Vamos batalhar!"),
    "5b:53a4": L("5b:53a4", "Meu peito chora…"),
    "5b:53b5": L("5b:53b5",
                 "Uma viagem é o",
                 "melhor remédio",
                 "para um coração",
                 "partido.",
                 "Mas a viagem de",
                 "FAST SHIP é curta"),
    "5b:5418": L("5b:5418",
                 "Vou fazer um teste",
                 "com as minhas",
                 "músicas na RADIO",
                 "STATION."),
    "5b:5456": L("5b:5456", "Uau!", "Distorção total!"),
    "5b:5470": L("5b:5470",
                 "Falando na RADIO",
                 "STATION,",
                 "qual é o número da",
                 "sorte da semana?"),

    # ---------------- as meninas ----------------
    "5b:59f9": L("5b:59f9", "Ei, filho! Quer", "batalhar comigo?"),
    "5b:5a2b": L("5b:5a2b",
                 "Você viaja",
                 "sozinho?",
                 "Sua mãe não fica",
                 "preocupada?"),
    "5b:5a5e": L("5b:5a5e",
                 "Você acha que eu",
                 "sou bebê?",
                 "Isso não é justo!"),
    "5b:5a92": L("5b:5a92",
                 "Bebê é um jeito",
                 "grosso de chamar",
                 "nós, meninas!"),
    "5b:5ab9": L("5b:5ab9",
                 "Eu não sou bebê!",
                 "Não é bonito falar",
                 "assim com a dama!"),
    "5b:5af8": L("5b:5af8",
                 "Às vezes crianças",
                 "são mais espertas",
                 "que adultos!"),
    "5b:5b25": L("5b:5b25",
                 "Psiu! Meu cérebro",
                 "está captando",
                 "sinais de rádio!"),
    "5b:5b51": L("5b:5b51", "…Estou ouvindo", "alguma coisa!"),
    "5b:5b67": L("5b:5b67",
                 "Entendi. Dá para",
                 "ouvir a rádio de",
                 "JOHTO no navio."),

    # ---------------- as senhoras ----------------
    "5b:5b9e": L("5b:5b9e",
                 "O que você acha?",
                 "Meus POKéMON são",
                 "lindos, não são?"),
    "5b:5bce": L("5b:5bce",
                 "Ah, não! Meus",
                 "lindos POKéMON!"),
    "5b:5bec": L("5b:5bec",
                 "Preciso ir ao",
                 "POKéMON SALON e",
                 "deixá-los lindos!"),
    "5b:5c1f": L("5b:5c1f",
                 "Vou fazer compras",
                 "na DEPT.STORE e",
                 "depois…"),
    "5b:5c4d": L("5b:5c4d", "O que eu ia", "fazer mesmo?"),
    "5b:5c66": L("5b:5c66",
                 "Ah, sim! Tenho que",
                 "buscar meu POKéMON",
                 "no DAY-CARE!"),
    "5b:5c97": L("5b:5c97",
                 "Que tipos de POKé",
                 "BALLS você tem",
                 "com você?"),
    "5b:5cc4": L("5b:5cc4", "Espera! Para! Não!", "Por favor!"),
    "5b:5cdf": L("5b:5cdf",
                 "Você devia usar a",
                 "BALL certa para",
                 "cada situação."),

    # ---------------- os marinheiros ----------------
    "5b:60bd": L("5b:60bd",
                 "Nada melhor que",
                 "uma batalha na",
                 "minha folga."),
    "5b:60ea": L("5b:60ea",
                 "Ganhando ou não,",
                 "a folga acabou!"),
    "5b:6108": L("5b:6108",
                 "Acho que não dá",
                 "para ganhar se eu",
                 "não levar a sério"),
    "5b:6133": L("5b:6133", "Estou entediado.", "Quer batalhar?"),
    "5b:6151": L("5b:6151", "Uau! Você é forte", "demais!"),
    "5b:6169": L("5b:6169",
                 "SAFFRON, CELADON…",
                 "Ouvi que tem",
                 "muitas cidades",
                 "grandes em KANTO."),
    "5b:61a7": L("5b:61a7", "Urrf…", "Estou enjoado!"),
    "5b:61ba": L("5b:61ba", "Não consigo mais", "me mexer…"),
    "5b:61d2": L("5b:61d2",
                 "Chega de navio",
                 "para mim. Da",
                 "próxima vez eu vou",
                 "de MAGNET TRAIN."),
    "5b:6210": L("5b:6210",
                 "É aqui que os",
                 "marinheiros ralam"),
    "5b:6230": L("5b:6230", "Perdi no meu", "próprio campo…"),
    "5b:624a": L("5b:624a",
                 "Recebemos passa-",
                 "geiros diferentes",
                 "de VERMILION CITY",
                 "a OLIVINE CITY."),
    "5b:628c": L("5b:628c",
                 "Mesmo estando no",
                 "mar, eu não posso",
                 "pescar!",
                 "Que tédio!",
                 "Vamos batalhar!"),
    "5b:62d8": L("5b:62d8", "Eu… já não estou", "entediado…"),
    "5b:62f2": L("5b:62f2",
                 "Pretendo pescar no",
                 "píer de VERMILION"),
    "5b:6317": L("5b:6317",
                 "Estou fortalecendo",
                 "as pernas firmes",
                 "contra o balanço",
                 "do navio!"),
    "5b:6355": L("5b:6355", "Balancei e", "capotei!"),
    "5b:636e": L("5b:636e",
                 "Não consegui achar",
                 "o KARATE KING em",
                 "JOHTO.",
                 "Dizem que ele",
                 "treina em alguma",
                 "caverna por aí."),
    "5b:63c9": L("5b:63c9",
                 "Sou marinheiro!",
                 "Mas estou criando",
                 "POKéMON para virar",
                 "o CAMPEÃO!"),
    "5b:640c": L("5b:640c",
                 "Minha falta de",
                 "treino é clara…"),
    "5b:642f": L("5b:642f",
                 "Oito BADGES!",
                 "Elas provam que",
                 "você venceu os",
                 "LÍDERES.",
                 "Não é à toa que",
                 "você é tão bom!"),

    # ---------------- a professora ----------------
    "5b:6486": L("5b:6486",
                 "Não encoste um",
                 "dedo nos alunos!"),
    "5b:64b1": L("5b:64b1",
                 "Estamos em excur-",
                 "são nas RUÍNAS",
                 "perto de VIOLET."),
}
