# -*- coding: utf-8 -*-
"""Lote 31 -- bancos 4c, 4d, 4e e 4f: as derivadas de Kanto e das rotas.

O SUNNY e a MONICA e as placas das rotas (4c); PEWTER, VIRIDIAN e o
diálogo do BLUE (4d); PEWTER GYM, o GINÁSIO fantasma de VIRIDIAN, o
vereador, CINNABAR, a CELADON (4e); e as cidades de Kanto, o LT.SURGE,
a MISTY, a SABRINA e a ERIKA (4f).

Ficam no original: nomes proprios de lugares, pessoas, itens e golpes;
as palavras POKéMON, GYM, BADGE, LEADER (dentro de "LEADER: X") e
ROUTE/RESPECT routes; o resto da caixa e traducao minha, a partir do
ingles original do jogo.
"""
from pt.estrutura import linhas as L

DIALOGO = {
    # ---------------- 4c: o SUNNY e a MONICA ----------------
    "4c:422d": L("4c:422d",
                 "SUNNY: Oi!",
                 "Eu sou o SUNNY de",
                 "sábado, ou seja,",
                 "hoje é sábado!"),
    "4c:4269": L("4c:4269",
                 "Me disseram para",
                 "te dar isso se eu",
                 "te visse!"),
    "4c:4294": L("4c:4294",
                 "SUNNY: Aquilo…",
                 "Hum…",
                 "…O que era mesmo…",
                 "…",
                 "Ah! Lembrei!",
                 "Um POKéMON que",
                 "tem golpes",
                 "elétricos devia",
                 "segurar.",
                 "Minha irmã MONICA",
                 "disse que aumenta",
                 "os golpes",
                 "elétricos!"),
    "4c:4336": L("4c:4336",
                 "SUNNY: Minhas",
                 "irmãs e meus ir-",
                 "mãos são MONICA,",
                 "TUSCANY, WESLEY,",
                 "ARTHUR, FRIEDA e",
                 "SANTOS. Eles são",
                 "todos mais velhos"),
    "4c:43a8": L("4c:43a8",
                 "SUNNY: Hoje não",
                 "é sábado?",
                 "Hum… Esqueci!"),
    "4c:43d1": L("4c:43d1",
                 "ROUTE 37"),
    "4c:48b2": L("4c:48b2",
                 "ROUTE 38",
                 "OLIVINE CITY -",
                 "ECRUTEAK CITY"),
    "4c:4d5a": L("4c:4d5a",
                 "ROUTE 39",
                 "OLIVINE CITY -",
                 "ECRUTEAK CITY"),
    "4c:5183": L("4c:5183",
                 "Mesmo não",
                 "vendo daqui,",
                 "CIANWOOD fica",
                 "do outro lado"),
    "4c:51c4": L("4c:51c4",
                 "MONICA: Prazer, eu",
                 "sou a MONICA de",
                 "segunda."),
    "4c:51f4": L("4c:51f4",
                 "Em sinal de",
                 "amizade, um pre-",
                 "sente pra você!"),
    "4c:522a": L("4c:522a",
                 "MONICA: É um",
                 "item que aumenta",
                 "o poder de golpes",
                 "de voar.",
                 "Equipe um POKéMON",
                 "pássaro com",
                 "esse item."),
    "4c:529a": L("4c:529a",
                 "MONICA: Meus",
                 "irmãos e irmãs",
                 "estão espalhados",
                 "por aí.",
                 "Tente encontrá-",
                 "los todos!"),
    "4c:52f5": L("4c:52f5",
                 "MONICA: Acho que",
                 "hoje não é",
                 "segunda. Que"),
    "4c:5325": L("4c:5325",
                 "ROUTE 40",
                 "CIANWOOD CITY -",
                 "OLIVINE CITY"),
    "4c:5dee": L("4c:5dee",
                 "ROUTE 42",
                 "ECRUTEAK CITY -",
                 "MAHOGANY TOWN"),
    "4c:5e5e": L("4c:5e5e",
                 "ROUTE 42",
                 "ECRUTEAK CITY -",
                 "MAHOGANY TOWN"),

    # ---------------- 4d: PEWTER, VIRIDIAN e o BLUE ----------------
    "4d:456f": L("4d:456f",
                 "ROUTE 43",
                 "LAKE OF RAGE -",
                 "MAHOGANY TOWN"),
    "4d:4596": L("4d:4596",
                 "ROUTE 43",
                 "LAKE OF RAGE -",
                 "MAHOGANY TOWN"),
    "4d:588a": L("4d:588a",
                 "Já visitou o",
                 "PEWTER GYM?",
                 "O LÍDER usa",
                 "POKéMON de pedra."),
    "4d:58c8": L("4d:58c8",
                 "De noite, CLEFAIRY",
                 "vêm pra brincar no",
                 "MT.MOON.",
                 "Mas nem toda",
                 "noite."),
    "4d:590e": L("4d:590e",
                 "Ah, você veio",
                 "de tão longe, de",
                 "JOHTO?",
                 "Isso traz memó-",
                 "rias. Quando eu",
                 "era jovem, ia",
                 "a JOHTO treinar.",
                 "Você me lembra",
                 "muito do que eu",
                 "era, jovem como",
                 "você.",
                 "Quero que fique",
                 "com um item que",
                 "achei em JOHTO."),
    "4d:59f2": L("4d:59f2",
                 "Ir a lugares",
                 "novos, conhecer",
                 "gente nova…",
                 "Essas são as",
                 "alegrias de"),
    "4d:5a47": L("4d:5a47",
                 "PEWTER CITY",
                 "A Cidade Cinzenta"),
    "4d:5a66": L("4d:5a66",
                 "PEWTER CITY",
                 "POKéMON GYM",
                 "LÍDER: BROCK",
                 "O Treinador",
                 "de pedra"),
    "4d:5aa6": L("4d:5aa6",
                 "Há um aviso…",
                 "aqui…",
                 "PEWTER MUSEUM OF",
                 "SCIENCE está",
                 "fechado…"),
    "4d:5af1": L("4d:5af1",
                 "Há um aviso…",
                 "LOJA do",
                 "MT.MOON GIFT SHOP",
                 "agora aberta!"),
    "4d:5b24": L("4d:5b24",
                 "Bem-vindo a",
                 "PEWTER CITY!"),
    "4d:5d80": L("4d:5d80",
                 "ROUTE 2",
                 "VIRIDIAN CITY -",
                 "PEWTER CITY"),
    "4d:5da5": L("4d:5da5",
                 "CAVERNA DIGLETT"),

    # ---------------- 4e: VIRIDIAN, o cafezal, CINNABAR e CELADON ----------------
    "4e:4062": L("4e:4062",
                 "Ei, garoto! Acabei",
                 "de tomar um café",
                 "bem forte e estou",
                 "ligado no 220!",
                 "Preciso conversar",
                 "com alguém, e",
                 "você vai servir!",
                 "Pode não parecer,",
                 "mas eu era expert",
                 "em capturar POKé-",
                 "MON.",
                 "Acredita em mim?"),
    "4e:412c": L("4e:412c",
                 "Bom, bom. Sim, eu",
                 "era alguém fora",
                 "do comum, posso",
                 "dizer!"),
    "4e:4174": L("4e:4174",
                 "O quê? Seu mole-",
                 "que!",
                 "Se eu fosse um",
                 "pouco mais jovem,",
                 "eu te mostraria",
                 "uma ou duas. Tsc!"),
    "4e:41ce": L("4e:41ce",
                 "Este GINÁSIO não",
                 "tinha um LÍDER",
                 "até pouco tempo.",
                 "Um rapaz de",
                 "PALLET virou o",
                 "LÍDER, mas vive",
                 "fora."),
    "4e:423b": L("4e:423b",
                 "Vai encarar o",
                 "LÍDER?",
                 "Boa sorte.",
                 "Vai precisar."),
    "4e:4281": L("4e:4281",
                 "Bocejo!",
                 "Devo ter dormido",
                 "no sol.",
                 "…Tive um sonho",
                 "com um DROWZEE",
                 "comendo meu sonho.",
                 "Estranho, né?",
                 "Hã?",
                 "O que é isto?",
                 "De onde veio",
                 "essa MT?",
                 "Que sinistro!",
                 "Tome, pode ficar",
                 "com esta MT."),
    "4e:4343": L("4e:4343",
                 "A MT42 contém",
                 "DREAM EATER…",
                 "…Zzzzz…"),
    "4e:4367": L("4e:4367",
                 "Ouvi dizer que há",
                 "muitos itens no",
                 "chão da",
                 "VIRIDIAN FOREST."),
    "4e:43ac": L("4e:43ac",
                 "VIRIDIAN CITY",
                 "O Paraíso Verde",
                 "Eterno"),
    "4e:43d8": L("4e:43d8",
                 "VIRIDIAN CITY",
                 "POKéMON GYM",
                 "LÍDER: …",
                 "O resto do texto",
                 "está ilegível…"),
    "4e:4456": L("4e:4456",
                 "TRAINER HOUSE",
                 "O Clube das Lutas",
                 "entre Treinadores"),
    "4e:4650": L("4e:4650",
                 "ROUTE 1",
                 "PALLET TOWN -",
                 "VIRIDIAN CITY"),
    "4e:46c2": L("4e:46c2",
                 "Eu também crio",
                 "POKéMON.",
                 "Eles servem de",
                 "meus guardas"),
    "4e:46fb": L("4e:46fb",
                 "Tecnologia é",
                 "incrível!",
                 "Dá pra trocar",
                 "POKéMON no tempo",
                 "como e-mail."),
    "4e:4746": L("4e:4746",
                 "PALLET TOWN",
                 "Um lugar sereno,",
                 "de paz e pureza"),
    "4e:4778": L("4e:4778",
                 "CASA do RED"),
    "4e:4785": L("4e:4785",
                 "LABORATÓRIO de",
                 "PESQUISA do OAK"),
    "4e:479c": L("4e:479c",
                 "CASA do BLUE"),

    # ---------------- 4e: o BLUE, CINNABAR, FUCHSIA e ROUTE 18 ----------------
    "4e:49a7": L("4e:49a7",
                 "Quem é você?",
                 "Bem, é óbvio",
                 "que você é um",
                 "treinador…",
                 "Meu nome é BLUE.",
                 "Eu já fui o",
                 "CAMPEÃO, embora",
                 "tenha sido por",
                 "pouco tempo…",
                 "Aquele RED",
                 "me venceu…",
                 "Enfim, o que",
                 "você quer? Quer",
                 "me desafiar ou",
                 "o quê?",
                 "…Detesto dizer,",
                 "mas não estou a",
                 "fim de lutar",
                 "agora.",
                 "Olhe ao seu",
                 "redor…",
                 "Um vulcão entra",
                 "em erupção, e de",
                 "repente, uma",
                 "cidade some.",
                 "Podemos ganhar",
                 "e perder em lutas",
                 "de POKéMON. Mas",
                 "se a natureza se",
                 "mexer, morremos",
                 "num segundo.",
                 "…",
                 "É assim que as",
                 "coisas são…",
                 "Mas, enfim, ainda",
                 "sou treinador.",
                 "Se vejo um",
                 "adversário bom,",
                 "me dá vontade de",
                 "lutar.",
                 "Se quiser,",
                 "vá ao GINÁSIO de",
                 "VIRIDIAN. Vou te",
                 "enfrentar."),
    "4e:4c48": L("4e:4c48",
                 "Há um aviso…",
                 "aqui…",
                 "O GINÁSIO de CIN-",
                 "NABAR mudou para",
                 "as ILHAS SEAFOAM.",
                 "BLAINE"),
    "4e:4c97": L("4e:4c97",
                 "CINNABAR ISLAND",
                 "A Cidade Fogo de",
                 "Desejo Ardente"),
    "4e:4e97": L("4e:4e97",
                 "O que este cartaz",
                 "diz?",
                 "CINNABAR GYM",
                 "LÍDER: BLAINE"),
    "4e:51da": L("4e:51da",
                 "Desculpe. Esta",
                 "estrada está em",
                 "obras.",
                 "Se quiser chegar",
                 "a CINNABAR, é",
                 "melhor ir pro sul",
                 "de PALLET TOWN."),
    "4e:524f": L("4e:524f",
                 "Estou todo suado.",
                 "Hora de nadar!"),
    "4e:5270": L("4e:5270",
                 "Quem sabe quanto",
                 "tempo pra mover",
                 "este pedregulho…"),
    "4e:52a8": L("4e:52a8",
                 "As obras na estra-",
                 "da terminaram.",
                 "Agora posso",
                 "voltar a pescar."),
    "4e:52e7": L("4e:52e7",
                 "ROUTE 19",
                 "FUCHSIA CITY -",
                 "SEAFOAM ISLANDS"),
    "4e:5310": L("4e:5310",
                 "Atenção: cuidado",
                 "ao nadar até as",
                 "SEAFOAM ISLANDS.",
                 "POLÍCIA de",
                 "FUCHSIA"),
    "4e:53eb": L("4e:53eb",
                 "Um dos ELITE",
                 "FOUR já foi o",
                 "LÍDER do GINÁSIO",
                 "de FUCHSIA."),
    "4e:5429": L("4e:5429",
                 "A filha do KOGA",
                 "virou o LÍDER do",
                 "GINÁSIO depois",
                 "que ele entrou no",
                 "ELITE FOUR."),
    "4e:5479": L("4e:5479",
                 "A SAFARI ZONE está",
                 "fechada… Que",
                 "pena, era a",
                 "maior atração",
                 "de FUCHSIA."),
    "4e:54c8": L("4e:54c8",
                 "FUCHSIA CITY",
                 "Veja! É o Rosa",
                 "da Paixão!"),
    "4e:54f0": L("4e:54f0",
                 "FUCHSIA CITY",
                 "POKéMON GYM",
                 "LÍDER: JANINE",
                 "A Mestra Ninja",
                 "dos Venenos"),
    "4e:5531": L("4e:5531",
                 "Há um aviso…",
                 "O ESCRITÓRIO da",
                 "SAFARI ZONE está",
                 "fechado até",
                 "novo aviso."),
    "4e:557b": L("4e:557b",
                 "SAFARI ZONE",
                 "CASA do GUARDIÃO"),
    "4e:5596": L("4e:5596",
                 "O GUARDIÃO está",
                 "no exterior.",
                 "Por isso, a",
                 "SAFARI ZONE está",
                 "fechada."),
    "4e:55dd": L("4e:55dd",
                 "Não jogue lixo.",
                 "Leve seu lixo",
                 "com você."),
    "4e:57c8": L("4e:57c8",
                 "ROUTE 18",
                 "CELADON CITY -",
                 "FUCHSIA CITY"),

    # ---------------- 4e: CELADON e a CYCLING ROAD ----------------
    "4e:5aa6": L("4e:5aa6",
                 "CYCLING ROAD",
                 "Descida livre",
                 "até o fim!"),
    "4e:5b3a": L("4e:5b3a",
                 "Este POLIWRATH é",
                 "meu parceiro.",
                 "Será que um dia",
                 "ele evolui para",
                 "POKéMON sapo."),
    "4e:5b9b": L("4e:5b9b",
                 "Perdi de novo no",
                 "caça-níquel…",
                 "Agora as garotas",
                 "também jogam.",
                 "Você devia dar",
                 "uma olhada."),
    "4e:5c00": L("4e:5c00",
                 "Os GRIMER têm",
                 "aparecido muito.",
                 "Viu o lago na",
                 "frente da casa?",
                 "Os GRIMER vivem",
                 "lá agora.",
                 "De onde saíram?",
                 "Isto é um pro-",
                 "blema sério…"),
    "4e:5c99": L("4e:5c99",
                 "Nihihi! Este",
                 "GINÁSIO é ótimo!",
                 "Só entra garota",
                 "aqui!"),
    "4e:5cd2": L("4e:5cd2",
                 "Quer saber um",
                 "segredo?",
                 "A CELADON MANSION",
                 "tem uma porta se-",
                 "creta."),
    "4e:5d12": L("4e:5d12",
                 "Está rolando um",
                 "concurso de comer",
                 "no restaurante.",
                 "Só de ver eles",
                 "comendo, já me",
                 "sinto inchado…"),
    "4e:5d7a": L("4e:5d7a",
                 "A CELADON DEPT.",
                 "STORE tem a maior",
                 "e melhor seleção",
                 "de mercadorias.",
                 "Se não achar",
                 "lá, não acha em",
                 "lugar nenhum.",
                 "Nossa… pareço",
                 "um vendedor de",
                 "loja."),
    "4e:5e18": L("4e:5e18",
                 "De olhar pro",
                 "chão enquanto an-",
                 "dava, fiquei",
                 "tonto."),
    "4e:5e52": L("4e:5e52",
                 "CELADON CITY",
                 "A Cidade dos",
                 "Sonhos Coloridos"),
    "4e:5e7b": L("4e:5e7b",
                 "CELADON CITY",
                 "POKéMON GYM",
                 "LÍDER: ERIKA",
                 "A Princesa que",
                 "ama a Natureza"),
    "4e:5ebb": L("4e:5ebb",
                 "Ache tudo o que",
                 "você precisa na",
                 "CELADON DEPT."),
    "4e:5ee6": L("4e:5ee6",
                 "CELADON MANSION"),
    "4e:5ef7": L("4e:5ef7",
                 "A diversão de to-",
                 "dos--CELADON GAME",
                 "CORNER"),
    "4e:5f2a": L("4e:5f2a",
                 "DICAS de TREINO",
                 "GUARD SPEC.",
                 "protege POKéMON",
                 "contra ataques",
                 "SPECIAL, como",
                 "fogo e água.",
                 "Compre seus itens",
                 "na CELADON DEPT.",
                 "STORE!"),
    "4e:6081": L("4e:6081",
                 "Que aviso é esse?",
                 "…Os treinadores",
                 "mal-educados têm",
                 "batalhado no",
                 "UNDERGROUND PATH.",
                 "Por causa das re-",
                 "clamações dos",
                 "moradores locais,",
                 "o UNDERGROUND",
                 "PATH foi lacrado",
                 "indefinidamente.",
                 "CELADON POLÍCIA"),
    "4e:614f": L("4e:614f",
                 "Está trancado…"),

    # ---------------- 4f: rotas e cidades de Kanto ----------------
    "4f:437c": L("4f:437c",
                 "ROUTE 15",
                 "FUCHSIA CITY -",
                 "LAVENDER TOWN"),
    "4f:4921": L("4f:4921",
                 "DICAS de TREINO",
                 "Olhe! Bem ali,",
                 "no lado esquerdo",
                 "do poste."),
    "4f:4960": L("4f:4960",
                 "ROUTE 13",
                 "Norte: SILENCE",
                 "BRIDGE"),
    "4f:4982": L("4f:4982",
                 "Norte: LAVENDER",
                 "TOWN",
                 "Oeste: FUCHSIA",
                 "CITY"),
    "4f:4cf7": L("4f:4cf7",
                 "ROUTE 12",
                 "NORTE: LAVENDER",
                 "TOWN"),
    "4f:4d18": L("4f:4d18",
                 "ÁREA de PESCA"),
    "4f:4fc6": L("4f:4fc6",
                 "ROUTE 11"),
    "4f:5048": L("4f:5048",
                 "Que prédio é",
                 "esse, hein?",
                 "É a TORRE de",
                 "RÁDIO de KANTO."),
    "4f:5080": L("4f:5080",
                 "KANTO tem bons",
                 "programas de"),
    "4f:50a2": L("4f:50a2",
                 "As pessoas vêm",
                 "de longe para",
                 "homenagear as",
                 "almas dos POKé-",
                 "MON."),
    "4f:50f2": L("4f:50f2",
                 "Você precisa de",
                 "uma POKé FLUTE",
                 "pra acordar POKé-",
                 "MON. Todo treina-",
                 "dor sabe disso!"),
    "4f:513d": L("4f:513d",
                 "LAVENDER TOWN",
                 "A Cidade Nobre",
                 "Roxa"),
    "4f:5162": L("4f:5162",
                 "RÁDIO KANTO",
                 "STATION",
                 "Seus Programas",
                 "Favoritos no Ar",
                 "24 Horas!"),
    "4f:51a7": L("4f:51a7",
                 "LAVENDER VOLUN-",
                 "TEER POKéMON"),
    "4f:51c6": L("4f:51c6",
                 "SOUL HOUSE",
                 "Que as Almas dos",
                 "POKéMON"),
    "4f:5308": L("4f:5308",
                 "VERMILION PORT é",
                 "a porta marítima",
                 "de KANTO.",
                 "Navios de luxo",
                 "do mundo todo",
                 "aportam aqui."),
    "4f:5362": L("4f:5362",
                 "Meu POKéMON está",
                 "preparando o ter-",
                 "reno para a obra.",
                 "Mas não tenho",
                 "dinheiro para co-",
                 "meçar…"),
    "4f:53d5": L("4f:53d5",
                 "Um MACHOP rosna",
                 "enquanto pisa o",
                 "chão para apla-"),
    "4f:540d": L("4f:540d",
                 "Há oito GINÁSIOS",
                 "em KANTO.",
                 "Aquele prédio",
                 "grande é o GINÁ-",
                 "SIO de VERMILION."),
    "4f:5457": L("4f:5457",
                 "SNORLAX ronca",
                 "tranquilamente…"),
    "4f:5477": L("4f:5477",
                 "Colocaram a POKé-",
                 "GEAR perto do",
                 "SNORLAX dormindo…",
                 "…",
                 "SNORLAX acordou!"),
    "4f:54bb": L("4f:54bb",
                 "Treinadores",
                 "habilidosos se",
                 "reúnem em KANTO.",
                 "Os LÍDERES são",
                 "fortes e não são",
                 "fáceis de vencer."),
    "4f:551e": L("4f:551e",
                 "Você começou a",
                 "colecionar as",
                 "BADGES de KANTO?",
                 "Você não acha",
                 "que os treinadores",
                 "daqui são fortes?"),
    "4f:557b": L("4f:557b",
                 "Acho que você",
                 "vai acabar logo",
                 "com a conquista",
                 "dos GINÁSIOS de",
                 "KANTO.",
                 "Me avise se",
                 "pegar as oito"),
    "4f:55e6": L("4f:55e6",
                 "Parabéns!",
                 "Você pegou as",
                 "BADGES de KANTO.",
                 "Tenho um prêmio",
                 "pra você."),
    "4f:563d": L("4f:563d",
                 "Uma variedade",
                 "de tipos POKéMON",
                 "te dá vantagem",
                 "na batalha.",
                 "Tenho certeza",
                 "que as GYM BADGES",
                 "de KANTO ajudam."),
    "4f:56ac": L("4f:56ac",
                 "VERMILION CITY",
                 "O Porto dos",
                 "Belos Pôr do Sol"),
    "4f:56da": L("4f:56da",
                 "VERMILION CITY",
                 "POKéMON GYM",
                 "LÍDER: LT.SURGE",
                 "O Americano",
                 "Relâmpago"),
    "4f:571b": L("4f:571b",
                 "POKéMON FAN CLUB",
                 "Todos os Fãs de",
                 "POKéMON"),
    "4f:5741": L("4f:5741",
                 "CAVERNA do"),
    "4f:5751": L("4f:5751",
                 "VERMILION PORT",
                 "ENTRADA"),
    "4f:5820": L("4f:5820",
                 "A estrada está",
                 "fechada até que",
                 "o problema na",
                 "USINA se resolva."),
    "4f:5864": L("4f:5864",
                 "UNDERGROUND PATH",
                 "CERULEAN CITY -",
                 "VERMILION CITY"),
    "4f:5923": L("4f:5923",
                 "Uma menininha",
                 "expert em imitar",
                 "as pessoas mora",
                 "aqui.",
                 "Ela imita até",
                 "quem está con-",
                 "versando com ela.",
                 "É confuso."),
    "4f:59a3": L("4f:59a3",
                 "A menina COPYCAT",
                 "parecia triste.",
                 "Ela disse que",
                 "perdeu sua POKé",
                 "DOLL--CLEFAIRY."),
    "4f:59f6": L("4f:59f6",
                 "Você veio de",
                 "JOHTO?",
                 "Você pode voltar",
                 "pra casa de MAGNET",
                 "TRAIN."),
    "4f:5a44": L("4f:5a44",
                 "Você veio de",
                 "JOHTO?",
                 "Dá pra voltar",
                 "pra casa pulando",
                 "no MAGNET TRAIN."),
    "4f:5a94": L("4f:5a94",
                 "Fui ao GINÁSIO,",
                 "a fim de batalhar",
                 "com treinadores…",
                 "No fim, acabei",
                 "entrando no GINÁ-",
                 "SIO vago ao",
                 "lado.",
                 "Nossa, que sem-",
                 "graça!"),
    "4f:5b24": L("4f:5b24",
                 "Esta é a SILPH",
                 "CO., famosa por",
                 "produtos POKéMON.",
                 "No passado, a",
                 "TEAM ROCKET",
                 "queria a empresa",
                 "por causa disso."),
    "4f:5b92": L("4f:5b92",
                 "Nhoc… Nhoc…",
                 "Ouvi dizer que",
                 "há um grande pro-",
                 "blema na USINA.",
                 "Nhoc… Nhoc…"),
    "4f:5be1": L("4f:5be1",
                 "Nhoc… Nhoc…",
                 "Ouvi dizer que",
                 "houve um grande",
                 "rolo na USINA.",
                 "Nhoc… Nhoc…",
                 "Haaah, que cheio!"),
    "4f:5c3b": L("4f:5c3b",
                 "Entrar num beco",
                 "pela primeira",
                 "vez me deixa",
                 "meio ansioso."),
    "4f:5c7b": L("4f:5c7b",
                 "Existe um lugar",
                 "chamado TRAINER",
                 "HOUSE em VIRIDIAN",
                 "onde treinadores",
                 "de todo canto",
                 "se reúnem."),
    "4f:5cdb": L("4f:5cdb",
                 "Nossa cidade foi",
                 "citada num",
                 "programa de rádio",
                 "É bom ouvir",
                 "elogios pra sua",
                 "cidade, mas é",
                 "um pouco sem-",
                 "graça também."),
    "4f:5d4d": L("4f:5d4d",
                 "SAFFRON CITY",
                 "A Cidade Dourada",
                 "do Comércio"),
    "4f:5d7c": L("4f:5d7c",
                 "SAFFRON CITY",
                 "POKéMON GYM",
                 "LÍDER: SABRINA",
                 "Mestra dos POKéMON",
                 "Psíquicos!"),
    "4f:5dbf": L("4f:5dbf",
                 "Todos são Bem-",
                 "vindos! DOJO de"),
    "4f:5de0": L("4f:5de0",
                 "SILPH CO.",
                 "PRÉDIO da"),
    "4f:5dfb": L("4f:5dfb",
                 "CASA do SR.PSI-",
                 "QUICO"),
    "4f:5e0f": L("4f:5e0f",
                 "SAFFRON CITY",
                 "MAGNET TRAIN",
                 "STATION"),
    "4f:5f1e": L("4f:5f1e",
                 "A estrada está",
                 "fechada até que",
                 "o problema na",
                 "USINA se resolva."),
    "4f:5f62": L("4f:5f62",
                 "UNDERGROUND PATH",
                 "CERULEAN CITY -",
                 "VERMILION CITY"),
    "4f:5f93": L("4f:5f93",
                 "O que é isto?",
                 "Casa à venda…",
                 "Ninguém mora aí."),
    "4f:60b0": L("4f:60b0",
                 "A USINA de KANTO",
                 "fica perto do fim",
                 "da ROUTE 9.",
                 "Houve um acidente",
                 "de algum tipo",
                 "por lá."),
    "4f:610c": L("4f:610c",
                 "Você quer captu-",
                 "rar um de cada",
                 "tipo de POKéMON?",
                 "Deve ser um",
                 "desafio e tanto,",
                 "mas parece legal."),
    "4f:6170": L("4f:6170",
                 "O CABO ao norte",
                 "é um bom lugar",
                 "pra encontros.",
                 "Garotas gostam!"),
    "4f:61c2": L("4f:61c2",
                 "Eu e meu SLOWBRO",
                 "formamos uma",
                 "dupla incrível!"),
    "4f:61f1": L("4f:61f1",
                 "SLOWBRO, mostre",
                 "seu CONFUSION!"),
    "4f:6216": L("4f:6216",
                 "Sou fã da",
                 "MISTY do GINÁSIO",
                 "de CERULEAN."),
    "4f:623d": L("4f:623d",
                 "Vi o cara sus-",
                 "peito ir pro CABO",
                 "de CERULEAN."),
    "4f:6271": L("4f:6271",
                 "Aqui havia uma",
                 "caverna com POKé-",
                 "MON horríveis e",
                 "fortes."),
    "4f:62b6": L("4f:62b6",
                 "Hein?",
                 "Meu ITEMFINDER",
                 "está reagindo…"),
    "4f:62da": L("4f:62da",
                 "CERULEAN CITY",
                 "Uma Estranha Aura",
                 "Azul a rodeia."),
    "4f:630d": L("4f:630d",
                 "CERULEAN CITY",
                 "POKéMON GYM",
                 "LÍDER: MISTY",
                 "A Sereia",
                 "Levada"),
    "4f:6349": L("4f:6349",
                 "Há um aviso…",
                 "aqui…",
                 "A BIKE SHOP mudou",
                 "para a GOLDENROD",
                 "CITY em JOHTO…"),
    "4f:6394": L("4f:6394",
                 "Há um aviso…",
                 "aqui…",
                 "Acabe com os la-",
                 "drões e faça da",
                 "cidade um lugar",
                 "mais alegre!",
                 "POLÍCIA CERULEAN"),
    "4f:6403": L("4f:6403",
                 "CERULEAN CAPE",
                 "adiante"),
    "4f:6418": L("4f:6418",
                 "Está trancado…"),
}