# -*- coding: utf-8 -*-
"""Lote 27 -- as derivadas dos bancos 51, 52 e 53: os marinheiros e o
farol de OLIVINE, a MOOMOO FARM (51), ECRUTEAK, a TIN TOWER, o BILL e as
KIMONO GIRLS (52) e o GINASIO do BLAINE em CINNABAR (53).

Ficam no original: BILL, BLAINE, MORTY, RHYDON, MILTANK, BUTTERFREE,
EEVEE, ESPEON, UMBREON, POKéMON, GINÁSIO, STRENGTH, SURF, SNORE, REVIVE,
ITEMFINDER, BERRY, BERRIES, MOOMOO, MOOMOO MILK, TIME CAPSULE, TIN TOWER,
BURNED TOWER, LAKE OF RAGE, SEAFOAM ISLANDS, MOUNT MORTAR, KIMONO GIRLS,
TEAM ROCKET, CINNABAR, ECRUTEAK, CIANWOOD, OLIVINE, GOLDENROD, KANTO,
VOLCANOBADGE, BADGE, BURN HEAL, HIDDEN POWER.
"""
from pt.estrutura import linhas as L

DIALOGO = {

    # ---------------- banco 51 ----------------
    "51:400e": L("51:400e",
                 "Os marinheiros",
                 "são generosos.",
                 "Um me ensinou",
                 "o STRENGTH.",
                 "Agora meu POKéMON",
                 "move pedregulhos."),
    "51:4067": L("51:4067",
                 "Tem uma pessoa",
                 "em CIANWOOD CITY",
                 "através do mar.",
                 "Eu ouvi ele se",
                 "gabar dos seus",
                 "POKéMON raros."),
    "51:4583": L("51:4583",
                 "Quando meu POKéMON",
                 "ficou doente, o",
                 "FARMACÊUTICO de",
                 "ECRUTEAK fez um",
                 "remédio pra mim."),
    "51:45d1": L("51:45d1",
                 "RHYDON: Grrugooh!"),
    "51:4624": L("51:4624",
                 "No caminho para",
                 "CIANWOOD, existem",
                 "Há quatro ilhas",
                 "desertas.",
                 "Crianças ruins são",
                 "levadas pras ilhas",
                 "como castigo!"),
    "51:4692": L("51:4692",
                 "Quando me meto em",
                 "enrascada, papai",
                 "sempre me assusta"),
    "51:472a": L("51:472a",
                 "OLIVINE fica no",
                 "mar!",
                 "E se fica no mar,",
                 "com certeza há",
                 "peixes!",
                 "Pesco aqui há",
                 "30 anos.",
                 "Quer encarar o",
                 "mar e pescar",
                 "também?"),
    "51:47bc": L("51:47bc",
                 "Ah, hahaha!",
                 "Temos para nós",
                 "um novo pescador!"),
    "51:47e8": L("51:47e8",
                 "Peixe não existe",
                 "só no mar.",
                 "Eles vão pra onde",
                 "há água."),
    "51:482d": L("51:482d",
                 "O quêê? Você não",
                 "gosta de pescar!?",
                 "Inacreditável!"),
    "51:4860": L("51:4860",
                 "E aí, como vai?",
                 "Pegou uma grande?"),
    "51:48bd": L("51:48bd",
                 "Hah! Seus POKéMON",
                 "parecem mesmo ser",
                 "pesos-leves!",
                 "Eles não têm força",
                 "pra mover de lado",
                 "os pedregulhos.",
                 "Tome, use isto",
                 "e ensine o golpe",
                 "STRENGTH a eles!",
                 "Vai precisar da",
                 "BADGE do GINÁSIO",
                 "de GOLDENROD pra",
                 "usar fora de luta"),
    "51:4980": L("51:4980",
                 "No mar, a única",
                 "coisa que conta",
                 "Só dá pra contar",
                 "com você mesmo.",
                 "Tenho orgulho do",
                 "meu corpo sarado!"),
    "51:49e0": L("51:49e0",
                 "Cruzando o mar?",
                 "Então escute!",
                 "Há redemoinhos",
                 "no caminho para",
                 "CIANWOOD.",
                 "Seu POKéMON tem",
                 "que saber de um",
                 "golpe pra passar",
                 "dos redemoinhos."),
    "51:4aaa": L("51:4aaa",
                 "Seus POKéMON já",
                 "sabem o golpe pra",
                 "carregar pessoas",
                 "sobre a água?"),
    "51:4aec": L("51:4aec",
                 "Meu BUTTERFREE",
                 "veio do namorado",
                 "lá do exterior.",
                 "Ele trouxe um MAIL",
                 "que ele mandou.",
                 "Quer saber o que",
                 "diz?",
                 "Vamos ver… Não!",
                 "É um segredo!"),
    "51:4bb0": L("51:4bb0",
                 "De onde mesmo você",
                 "é?",
                 "De NEW BARK TOWN?",
                 "O PROF.ELM mora",
                 "perto daí, certo?",
                 "Você veio de bem",
                 "longe pra chegar."),
    "51:4d04": L("51:4d04",
                 "MOOMOO doente…",
                 "Ela precisa de",
                 "muitas BERRIES."),
    "51:4d30": L("51:4d30",
                 "Dando comida pra",
                 "MOOMOO!"),
    "51:4d56": L("51:4d56",
                 "O choro é fraco…"),
    "51:4d77": L("51:4d77",
                 "Dar uma BERRY pra",
                 "MILTANK?"),
    "51:4d91": L("51:4d91",
                 "{PLAYER} deu uma",
                 "BERRY à MILTANK."),
    "51:4dad": L("51:4dad",
                 "A MILTANK ficou",
                 "mais saudável!"),
    "51:4dd1": L("51:4dd1",
                 "MILTANK ficou",
                 "bem saudável!"),
    "51:4df0": L("51:4df0",
                 "MILTANK ficou",
                 "muito saudável!"),
    "51:4e11": L("51:4e11",
                 "{PLAYER} não tem",
                 "BERRIES…"),
    "51:4e24": L("51:4e24",
                 "{PLAYER} não quer",
                 "dar uma BERRY.",
                 "MILTANK triste."),
    "51:4f0d": L("51:4f0d",
                 "A MILTANK não me",
                 "dá leite mais não.",
                 "agora.",
                 "Esta FAZENDA aqui",
                 "tem leite famoso.",
                 "Quase todo mundo",
                 "quer beber.",
                 "Ela me dá bastante",
                 "leite se eu der",
                 "muitas BERRIES,",
                 "eu acho."),
    "51:4fb7": L("51:4fb7",
                 "Gostou do meu",
                 "MOOMOO MILK?",
                 "É meu orgulho e",
                 "alegria, filho.",
                 "Dê aos POKéMON",
                 "pra recuperar HP!",
                 "Te vendo por só",
                 "¥500."),
    "51:5031": L("51:5031",
                 "Toma!",
                 "Bebe e aproveita!"),
    "51:5050": L("51:5050",
                 "Desculpa, filho.",
                 "Sem grana, nada!"),
    "51:506f": L("51:506f",
                 "Acho que sua",
                 "MOCHILA tá cheia."),
    "51:508e": L("51:508e",
                 "Não quer mais?",
                 "Volte depois, tá?"),
    "51:50b3": L("51:50b3",
                 "Melhor eu ir",
                 "ordenhar."),
    "51:50cd": L("51:50cd",
                 "Nosso leite vai",
                 "até para KANTO.",
                 "Então se nossa",
                 "MILTANK não der",
                 "leite, ficamos",
                 "em apuros."),
    "51:512d": L("51:512d",
                 "Você curou nossa",
                 "MILTANK, meu bem.",
                 "Agora dá MOOMOO",
                 "MILK de novo.",
                 "Toma uma lembrança",
                 "por seu trabalho."),
    "51:519e": L("51:519e",
                 "Isso aí é o",
                 "SNORE.",
                 "É um golpe raro",
                 "que só funciona",
                 "quando o POKéMON",
                 "está dormindo.",
                 "Melhor pensar bem",
                 "em como usar,",
                 "meu bem."),
    "51:5c32": L("51:5c32",
                 "O quê? A TEAM",
                 "ROCKET voltou",
                 "de novo?",
                 "Vi uns homens de",
                 "preto no LAKE OF",
                 "RAGE…"),
    "51:5c83": L("51:5c83",
                 "Seguro meu POKéMON",
                 "de evoluir cedo",
                 "demais.",
                 "Faço aprenderem",
                 "certos golpes an-",
                 "tes de deixar eles",
                 "evoluírem."),
    "51:5ce8": L("51:5ce8",
                 "POKéMON ficam mais",
                 "fortes ao evoluir",
                 "mas aprendem os",
                 "golpes bem mais",
                 "devagar."),
    "51:5d88": L("51:5d88",
                 "O MOUNT MORTAR é",
                 "um labirinto.",
                 "Cuidado pra não",
                 "se perder lá."),

    # ---------------- banco 52 ----------------
    "52:40cc": L("52:40cc",
                 "A TIN TOWER é",
                 "proibida a quem",
                 "sem a BADGE do",
                 "GINÁSIO daqui.",
                 "Ah!",
                 "A BADGE do GINÁSIO",
                 "de ECRUTEAK! Pode",
                 "passar adiante."),
    "52:413f": L("52:413f",
                 "A TIN TOWER à",
                 "frente foi feita",
                 "como abrigo dos",
                 "POKéMON que voam."),
    "52:417d": L("52:417d",
                 "A TIN TOWER",
                 "tremeu! POKéMON",
                 "deve ter voltado",
                 "ao topo!"),
    "52:41b9": L("52:41b9",
                 "Duas torres…",
                 "Dois POKéMON…",
                 "Mas quando uma",
                 "queimou, os dois",
                 "POKéMON voaram",
                 "e nunca voltaram."),
    "52:4304": L("52:4304",
                 "Oi, eu sou o BILL.",
                 "E você é quem?",
                 "{PLAYER}, hein?",
                 "Você chegou numa",
                 "boa hora."),
    "52:434e": L("52:434e",
                 "Acabei de ajustar",
                 "a minha TIME",
                 "CAPSULE.",
                 "Você sabe que dá",
                 "pra trocar POKéMON",
                 "certo?",
                 "Minha TIME CAPSULE",
                 "foi feita pra",
                 "trocar com o",
                 "passado.",
                 "Não pode mandar",
                 "nada que",
                 "não existia no",
                 "passado.",
                 "Se mandasse, o PC",
                 "do passado ia",
                 "quebrar.",
                 "Então é preciso",
                 "tirar tudo que",
                 "não tinha no",
                 "passado.",
                 "Em resumo, nada",
                 "de golpe novo ou",
                 "POKéMON novo na",
                 "TIME CAPSULE.",
                 "Não se preocupe.",
                 "Já terminei os",
                 "ajustes.",
                 "Amanhã, as TIME",
                 "CAPSULES vão",
                 "funcionam nos",
                 "CENTROS POKéMON.",
                 "Preciso voltar pra",
                 "GOLDENROD pra ver",
                 "a família.",
                 "Tchau!"),
    "52:4581": L("52:4581",
                 "O jeito das KIMONO",
                 "GIRLS dançarem é",
                 "maravilhoso. Assim",
                 "como elas usam",
                 "seus POKéMON."),
    "52:45d6": L("52:45d6",
                 "MORTY, o LÍDER",
                 "do GINÁSIO, é tão",
                 "legal.",
                 "Os POKéMON dele",
                 "são fortes também"),
    "52:461c": L("52:461c",
                 "LAKE OF RAGE…",
                 "O aparecimento do",
                 "bando de GYARADOS",
                 "Sinto cheiro de",
                 "conspiração. Sei!"),
    "52:46d3": L("52:46d3",
                 "Isso aconteceu",
                 "quando jovem.",
                 "O céu de repente",
                 "ficou preto. Um",
                 "POKéMON gigante",
                 "voador cobriu",
                 "o sol.",
                 "Que POKéMON",
                 "será que era?",
                 "Parecia um pássaro",
                 "e um dragão."),
    "52:4782": L("52:4782",
                 "Será que existe um",
                 "POKéMON gigante?",
                 "Se ele existe,",
                 "deve ser forte."),
    "52:4b94": L("52:4b94",
                 "Não só as KIMONO",
                 "GIRLS são ótimas",
                 "dançarinas, também",
                 "são boas em",
                 "POKéMON.",
                 "Sempre as desafio,",
                 "mas nunca deixei",
                 "nem um arranhão.",
                 "nelas…"),
    "52:4c1b": L("52:4c1b",
                 "Jovem! Se você",
                 "derrotar todas as",
                 "KIMONO GIRLS, eu",
                 "te dou um prêmio."),
    "52:4c5e": L("52:4c5e",
                 "O jeito que você",
                 "lutou parecia",
                 "ver uma dança.",
                 "Foi uma raridade",
                 "ver isso!",
                 "Quero que você",
                 "fique com isto.",
                 "Sem medo, aceite!"),
    "52:4cdf": L("52:4cdf",
                 "Isto é o SURF.",
                 "É um golpe que",
                 "deixa POKéMON",
                 "nadar na água."),
    "52:4d19": L("52:4d19",
                 "Queria que meu",
                 "POKéMON fosse",
                 "tão elegante…"),
    "52:4d4e": L("52:4d4e",
                 "RHYDON: Grogoh",
                 "grugrooh!"),
    "52:4d68": L("52:4d68",
                 "Aquele homem vive",
                 "com seu RHYDON.",
                 "Diz que quer um",
                 "POKéMON que saiba",
                 "SURF e dançar.",
                 "Será que ele quer",
                 "fazer um POKéMON",
                 "de nado sincroni-",
                 "zado?"),
    "52:4dee": L("52:4dee",
                 "As KIMONO GIRLS",
                 "são tão lindas…",
                 "Mas elas passam",
                 "por um treino",
                 "rigoroso.",
                 "E também têm que",
                 "aprender costumes",
                 "antes de aparecer",
                 "em público.",
                 "Mas se você ama",
                 "algo, tudo é",
                 "possível."),
    "52:4ebd": L("52:4ebd",
                 "É um painel chique",
                 "que é decorado",
                 "com flores."),
    "52:4f8c": L("52:4f8c",
                 "Meu EEVEE virou",
                 "um ESPEON.",
                 "Mas o do meu amigo",
                 "EEVEE virou um",
                 "UMBREON.",
                 "Por que será? Nós",
                 "dois criávamos",
                 "nosso EEVEE do",
                 "mesmo jeito…"),
    "52:5019": L("52:5019",
                 "Se usar REVIVE,",
                 "um POKéMON que",
                 "desmaiou vai",
                 "acordar."),
    "52:58cc": L("52:58cc",
                 "Ah. Está numa",
                 "aventura com",
                 "seus POKéMON?",
                 "E o que seria",
                 "uma aventura sem",
                 "caça ao tesouro?",
                 "Tô certo ou não",
                 "estou certo?"),
    "52:5945": L("52:5945",
                 "Ótimo! Você",
                 "entende o real",
                 "espírito de",
                 "aventura.",
                 "Gostei! Leve",
                 "isto com você."),
    "52:599e": L("52:599e",
                 "Há muitos itens",
                 "espalhados por aí",
                 "E que não são",
                 "óbvios.",
                 "Use o ITEMFINDER",
                 "pra checar se há",
                 "um item no chão",
                 "perto de você.",
                 "Ele não mostra o",
                 "lugar exato,",
                 "então vai ter que",
                 "procurar.",
                 "Ah! Ouvi dizer que",
                 "há itens",
                 "na BURNED TOWER",
                 "de ECRUTEAK."),
    "52:5a95": L("52:5a95",
                 "Ah… Cada um com",
                 "seu gosto, né…"),
    "52:5ab6": L("52:5ab6",
                 "HISTÓRIA DE",
                 "ECRUTEAK",
                 "Quer ler?"),
    "52:5adc": L("52:5adc",
                 "Em ECRUTEAK havia",
                 "duas torres.",
                 "Cada torre era",
                 "o abrigo de",
                 "POKéMON voadores.",
                 "Mas uma delas",
                 "queimou até o",
                 "chão.",
                 "Os dois POKéMON",
                 "não são vistos",
                 "desde então…",
                 "Continuar lendo?"),
    "52:5b92": L("52:5b92",
                 "ECRUTEAK também",
                 "era o lar de três",
                 "POKéMON corriam",
                 "pela cidade.",
                 "Dizem que nasceram",
                 "da água e do",
                 "relâmpago e do",
                 "fogo.",
                 "Mas não conseguiam",
                 "conter seu poder",
                 "excessivo.",
                 "Por isso os três",
                 "correram como o",
                 "vento até o",
                 "campo."),

    # ---------------- banco 53 ----------------
    "53:4fa7": L("53:4fa7",
                 "BLAINE, do GINÁSIO",
                 "de CINNABAR",
                 "mora sozinho na",
                 "CAVERNA das",
                 "SEAFOAM ISLANDS…"),
    "53:4ff1": L("53:4ff1",
                 "Já faz um ano",
                 "desde que o vulcão",
                 "entrou em erupção"),
    "53:50fc": L("53:50fc",
                 "Nenhum morador de",
                 "CINNABAR se feriu",
                 "com a erupção.",
                 "Que ótimo!"),
    "53:51ba": L("53:51ba",
                 "BLAINE: Uaaah!",
                 "Meu GINÁSIO em",
                 "CINNABAR queimou.",
                 "Eu e meus POKéMON",
                 "de fogo ficamos",
                 "sem casa por",
                 "causa do vulcão.",
                 "Buaaah!",
                 "Mas voltei à ativa",
                 "como LÍDER de",
                 "GINÁSIO aqui na",
                 "caverna.",
                 "Se você me vencer",
                 "eu te dou",
                 "uma BADGE.",
                 "Ha! Melhor levar",
                 "BURN HEAL!"),
    "53:52b8": L("53:52b8",
                 "BLAINE: Demais.",
                 "Estou esgotado…",
                 "Você ganhou a",
                 "VOLCANOBADGE!"),
    "53:52f5": L("53:52f5",
                 "{PLAYER} recebeu",
                 "a VOLCANOBADGE."),
    "53:530f": L("53:530f",
                 "BLAINE: Perdi",
                 "desta vez, mas",
                 "vou vencer na",
                 "próxima.",
                 "Quando eu refizer",
                 "o meu GINÁSIO,",
                 "de CINNABAR,",
                 "teremos revanche."),
    "53:538e": L("53:538e",
                 "BLAINE: Meus",
                 "POKéMON de fogo",
                 "ficarão ainda mais",
                 "fortes. Veja!"),
    "53:53cb": L("53:53cb",
                 "E aí!",
                 "…Hein? Já acabou?",
                 "tão rápido?",
                 "Desculpa, cara!",
                 "O GINÁSIO de",
                 "CINNABAR sumiu,",
                 "então não sabia",
                 "onde te achar.",
                 "Mas você está",
                 "bem forte, mesmo",
                 "sem meu conselho.",
                 "Eu já sabia!"),
    "53:5477": L("53:5477",
                 "Um GINÁSIO pode",
                 "ser em qualquer",
                 "lugar, desde que",
                 "o LÍDER esteja",
                 "lá. Não precisa de",
                 "prédio."),
    "53:5521": L("53:5521",
                 "…Você vagou muito",
                 "longe…",
                 "Aqui eu meditei.",
                 "Dentro de mim,",
                 "um novo poder",
                 "despertou.",
                 "Deixe-me dividir",
                 "meu poder com",
                 "seu POKéMON.",
                 "Tome, criança."),
    "53:55b4": L("53:55b4",
                 "Vê isto? É o",
                 "HIDDEN POWER!",
                 "Ele extrai o",
                 "poder do POKéMON",
                 "pra atacar.",
                 "Lembre-se: o tipo",
                 "e o poder dependem",
                 "do POKéMON",
                 "que o usa."),
    "53:5649": L("53:5649",
                 "Estou meditando…"),
    "53:5af5": L("53:5af5",
                 "Só quem vai ao",
                 "LAKE OF RAGE",
                 "passou por aqui",
                 "ultimamente."),
    "53:5b3b": L("53:5b3b",
                 "Ninguém mais vai",
                 "ao LAKE OF RAGE",
                 "nesses dias."),
    "53:5ca8": L("53:5ca8",
                 "Pare aí, moço!",
                 "moço!",
                 "O pedágio é ¥1000",
                 "para passar."),
    "53:5cf2": L("53:5cf2",
                 "Então pague o que",
                 "tiver, por favor."),
    "53:5d13": L("53:5d13",
                 "Hihihi. Estamos",
                 "enchendo o bolso.",
                 "Todo mundo quer",
                 "ver o que rola",
                 "no LAKE OF",
                 "RAGE."),
    "53:5d6d": L("53:5d6d",
                 "Fui expulso do",
                 "meu posto por",
                 "aqueles de preto.",
                 "Eles deixaram",
                 "isto para trás.",
                 "Isso me deixa",
                 "desconfortável.",
                 "Pode levar?"),
    "53:5dff": L("53:5dff",
                 "Use este portão",
                 "pra não andar",
                 "na grama."),
}
