# -*- coding: utf-8 -*-
"""Lote 16 -- banco 4c inteiro: as gemeas, os nadadores e as WHIRL ISLANDS.

Rotas 34 a 41 e o mar entre OLIVINE e CIANWOOD.  Sao as falas de
ver/vencer/perder dos treinadores do caminho, mais as conversas sobre as
WHIRL ISLANDS e o POKéMON de asas prateadas.

Ficam no original: ANN, ANNE, WHIRL ISLANDS, ISLANDS, STARYU, LAPRAS,
MOOMOO FARM, POKé FANS, SURF, CIANWOOD CITY, OLIVINE.
"""
from pt.estrutura import linhas as L

DIALOGO = {
    # ---------------- as gemeas ANN e ANNE ----------------
    "4c:40bc": L("4c:40bc", "ANN & ANNE: Você", "é mau!"),
    "4c:40d5": L("4c:40d5",
                 "ANN: Eu sei o que",
                 "minha irmã e meus",
                 "POKéMON estão",
                 "pensando."),
    "4c:410f": L("4c:410f",
                 "ANNE: Eu e a ANN",
                 "estamos nisso",
                 "juntas!"),
    "4c:4138": L("4c:4138", "ANN & ANNE: Você", "é mau!"),
    "4c:4151": L("4c:4151",
                 "ANNE: Sentimos o",
                 "mesmo que os",
                 "nossos POKéMON."),

    # ---------------- quem usa status ----------------
    "4c:4180": L("4c:4180",
                 "POKéMON não fazem",
                 "nada se estiverem",
                 "dormindo.",
                 "Vou mostrar como",
                 "isso é assustador"),
    "4c:41ca": L("4c:41ca", "Perdi. Que", "tristeza…"),
    "4c:41e5": L("4c:41e5",
                 "Fazer o POKéMON",
                 "dormir ou deixar",
                 "ele paralisado são",
                 "boas técnicas."),

    # ---------------- os colegiais ----------------
    "4c:45d6": L("4c:45d6",
                 "Dá vontade de sair",
                 "voando agora."),
    "4c:45f9": L("4c:45f9",
                 "Pretendo treinar",
                 "em CIANWOOD CITY",
                 "para meu POKéMON",
                 "aprender a voar."),
    "4c:4638": L("4c:4638",
                 "Deixa eu tentar",
                 "uma coisa que",
                 "aprendi hoje."),
    "4c:4661": L("4c:4661",
                 "Acho que não",
                 "estudei bastante."),
    "4c:4681": L("4c:4681",
                 "Tenho tantas",
                 "provas para fazer",
                 "que sobra pouco",
                 "tempo pro POKéMON",
                 "Então quando dá",
                 "para jogar, eu me",
                 "concentro mesmo."),
    "4c:46f0": L("4c:46f0",
                 "Você é bom em",
                 "treinar?",
                 "Se for, pode me",
                 "mostrar como?"),
    "4c:472e": L("4c:472e",
                 "Entendi. Então dá",
                 "para lutar assim."),
    "4c:4752": L("4c:4752",
                 "Eu sei de uma",
                 "boa!",
                 "O leite da MOOMOO",
                 "FARM é famoso pelo",
                 "sabor."),

    # ---------------- as senhoras e os POKé FANS ----------------
    "4c:4796": L("4c:4796",
                 "Oi! Que treinador",
                 "fofo você é!",
                 "Posso ver seus",
                 "POKéMON?"),
    "4c:47ca": L("4c:47ca",
                 "Que bom que eu vi",
                 "seus POKéMON!"),
    "4c:47eb": L("4c:47eb",
                 "Quando vejo POKé-",
                 "MON, meus nervos",
                 "se acalmam."),
    "4c:481d": L("4c:481d",
                 "Já estive no",
                 "exterior, então",
                 "conheço todo tipo",
                 "de POKéMON!"),
    "4c:4856": L("4c:4856",
                 "Sua habilidade é",
                 "de nível mundial!"),
    "4c:4872": L("4c:4872",
                 "Todo tipo de",
                 "gente pelo mundo",
                 "vive feliz com",
                 "os POKéMON."),
    "4c:4acc": L("4c:4acc",
                 "Acabei de voltar",
                 "para OLIVINE.",
                 "Que tal uma",
                 "batalha POKéMON?"),
    "4c:4b10": L("4c:4b10",
                 "Meus POKéMON foram",
                 "pegos e criados",
                 "no exterior.",
                 "São meus compa-",
                 "nheiros nas longas",
                 "viagens."),
    "4c:4b68": L("4c:4b68",
                 "Você se importa se",
                 "eu me gabar dos",
                 "meus POKéMON?"),
    "4c:4b94": L("4c:4b94", "Nem consigo me", "gabar…"),
    "4c:4bae": L("4c:4bae",
                 "Não vou ouvir",
                 "você se gabar!",
                 "Nós POKé FANS",
                 "temos a regra de",
                 "não ouvir os",
                 "outros se gabarem"),
    "4c:4c11": L("4c:4c11",
                 "Que POKéMON",
                 "queridos.",
                 "Vamos mostrar os",
                 "nossos POKéMON",
                 "ao mesmo tempo."),
    "4c:4c53": L("4c:4c53", "Não me importo", "de perder."),
    "4c:4c68": L("4c:4c68",
                 "Você conhece os",
                 "POKéMON bebês?",
                 "Aposto que são",
                 "adoráveis!"),
    "4c:4ca2": L("4c:4ca2",
                 "Deixa eu ver do",
                 "que os seus",
                 "POKéMON são bons."),
    "4c:4ccd": L("4c:4ccd",
                 "Ooh, seus POKéMON",
                 "têm potencial."),
    "4c:4ced": L("4c:4ced",
                 "Sabe como cada",
                 "POKéMON tem uma",
                 "habilidade?",
                 "Com gente é igual",
                 "Cada um tem um",
                 "potencial dife-",
                 "rente."),

    # ---------------- os nadadores ----------------
    "4c:4fc3": L("4c:4fc3", "Tá! Chega! Perdi!"),
    "4c:4fd7": L("4c:4fd7",
                 "CIANWOOD CITY fica",
                 "bem longe",
                 "daqui."),
    "4c:5009": L("4c:5009",
                 "Um jovem como",
                 "você devia nadar.",
                 "Não use SURF no",
                 "seu POKéMON."),
    "4c:5054": L("4c:5054",
                 "Nadar exercita",
                 "o corpo inteiro.",
                 "É saudável."),
    "4c:5087": L("4c:5087",
                 "Você vai para",
                 "CIANWOOD?",
                 "Que tal uma luta",
                 "rápida antes?"),
    "4c:50c3": L("4c:50c3", "Perdi essa!"),
    "4c:50d5": L("4c:50d5",
                 "Eu diria que nado",
                 "melhor que você.",
                 "É isso aí!"),
    "4c:5103": L("4c:5103",
                 "Boia não é",
                 "comigo.",
                 "Estou agarrado a",
                 "um POKéMON do mar"),
    "4c:5137": L("4c:5137",
                 "Ooh, estou ficando",
                 "tonto!"),
    "4c:514f": L("4c:514f",
                 "Enquanto eu boio",
                 "assim, as ondas",
                 "me levam."),
    "4c:54e4": L("4c:54e4",
                 "Eita! Minha pele",
                 "está enrugada!"),
    "4c:5500": L("4c:5500",
                 "Não é relaxante",
                 "só boiar assim?",
                 "Né?"),
    "4c:552b": L("4c:552b",
                 "Estou cansado.",
                 "Se eu ganhar, me",
                 "empreste um."),
    "4c:5566": L("4c:5566",
                 "É tão longe até",
                 "CIANWOOD.",
                 "Mas voltar para",
                 "OLIVINE também",
                 "não é fácil.",
                 "O que eu faço?"),

    # ---------------- as WHIRL ISLANDS ----------------
    "4c:55c0": L("4c:55c0",
                 "Viu aquelas ilhas",
                 "bloqueadas por",
                 "redemoinhos?",
                 "Tem que ter um",
                 "segredo ali!"),
    "4c:5612": L("4c:5612",
                 "Qual é o segredo",
                 "da sua força?"),
    "4c:5636": L("4c:5636",
                 "Era uma noite",
                 "escura e de",
                 "tempestade… Eu vi",
                 "um POKéMON gigante",
                 "voando das ilhas.",
                 "Ele espalhava",
                 "penas das asas",
                 "prateadas dele."),
    "4c:56b8": L("4c:56b8",
                 "As ondas aqui",
                 "são bravas.",
                 "Elas cansam a",
                 "gente na nadada."),
    "4c:56fe": L("4c:56fe",
                 "As correntes não",
                 "me deixam chegar",
                 "naquela ilha."),
    "4c:572f": L("4c:572f",
                 "Você busca os",
                 "segredos das",
                 "WHIRL ISLANDS?"),
    "4c:575e": L("4c:575e",
                 "Ooh, você tem",
                 "muito fôlego!"),
    "4c:577f": L("4c:577f",
                 "Um segredo das",
                 "WHIRL ISLANDS…",
                 "Lá dentro é",
                 "escuro total!"),
    "4c:57b6": L("4c:57b6",
                 "Estou indo para",
                 "as WHIRL ISLANDS.",
                 "Vou explorar com",
                 "uns amigos."),
    "4c:57f9": L("4c:57f9", "É assim que se", "faz?"),
    "4c:5811": L("4c:5811",
                 "Dizem que tem um",
                 "POKéMON enorme lá",
                 "no fundo das",
                 "WHIRL ISLANDS.",
                 "O que será que",
                 "pode ser?"),
    "4c:586c": L("4c:586c",
                 "Você fica tão",
                 "elegante montado",
                 "no seu POKéMON."),
    "4c:58a3": L("4c:58a3",
                 "Não tinha uma",
                 "música sobre um",
                 "menino no LAPRAS?"),
    "4c:58d8": L("4c:58d8",
                 "O tempo está tão",
                 "lindo que eu fico",
                 "abobado!"),
    "4c:590b": L("4c:590b",
                 "Queimadura de sol",
                 "é ruim pra pele.",
                 "Mas eu não uso",
                 "protetor.",
                 "Não vou poluir",
                 "a água."),
    "4c:5962": L("4c:5962",
                 "Se precisar",
                 "descansar, é só",
                 "boiar.",
                 "Você recupera o",
                 "fôlego e pode",
                 "seguir em frente",
                 "com força."),
    "4c:59c5": L("4c:59c5",
                 "Oh! Você tem mais",
                 "energia que eu."),
    "4c:59ea": L("4c:59ea",
                 "Ouvi rugidos lá",
                 "do fundo das",
                 "ISLANDS."),
    "4c:5a17": L("4c:5a17",
                 "À noite, STARYU",
                 "se juntam perto",
                 "da superfície."),
    "4c:5a54": L("4c:5a54",
                 "Os cardumes de",
                 "STARYU acendem",
                 "ao mesmo tempo.",
                 "É tão bonito que",
                 "chega a assustar."),

    # ---------------- os pescadores e o resto ----------------
    "4c:5c4a": L("4c:5c4a", "O quê? Isso não", "está certo."),
    "4c:5c62": L("4c:5c62",
                 "Quero virar o",
                 "treinador CAMPEÃO",
                 "com os POKéMON",
                 "que eu pesquei.",
                 "É a melhor parte",
                 "de pescar!"),
    "4c:5cbf": L("4c:5cbf",
                 "Ah, que bom estar",
                 "ao ar livre!",
                 "Me sinto livre!"),
    "4c:5cf6": L("4c:5cf6",
                 "Perder parece",
                 "pouca coisa se",
                 "você olha para o",
                 "céu enorme!"),
    "4c:5d33": L("4c:5d33",
                 "EI!",
                 "Este é o meu lugar",
                 "secreto! Some,",
                 "seu forasteiro!"),
}
