# -*- coding: utf-8 -*-
"""Lote 14b -- o resto do telefone: o PROF.ELM e os treinadores.

Banco 41.  Sao as ligacoes de revanche, de avistamento de POKéMON e as
saudacoes que os treinadores fazem ao ligar -- montadas com {STRBUF}
para o nome de quem liga, do POKéMON e do lugar.

Nove chaves do banco ficaram de fora: sao a cauda de falas que o lote
14a ja traduziu (`41:4acc` e o fim de `41:4aba`).  O filtro automatico
nao as pegou porque a fala-mae saiu da lista de pendentes assim que foi
traduzida -- ficou sem par para comparar.  Conferi a olho.

Ficam no original: PROF.ELM, LAB, TEAM ROCKET, EGG, ROD, PARK, KAZ,
AUDREY, VIOLET CITY.
"""
from pt.estrutura import linhas as L

DIALOGO = {
    # ---------------- o PROF.ELM ----------------
    "41:55b4": L("41:55b4",
                 "A-alô? {PLAYER}?",
                 "É um desastre!",
                 "Ah, hum, é",
                 "terrível!",
                 "O que eu faço?",
                 "Isso… Ai, não…",
                 "Por favor volte",
                 "para cá agora!"),
    "41:5624": L("41:5624",
                 "Alô, {PLAYER}?",
                 "Descobrimos uma",
                 "coisa sobre o",
                 "EGG!",
                 "Meu assistente",
                 "está no CENTRO",
                 "POKéMON de VIOLET",
                 "CITY. Pode falar",
                 "com ele?"),
    "41:56a3": L("41:56a3",
                 "{PLAYER}, como",
                 "vão as coisas?",
                 "Liguei porque tem",
                 "algo estranho",
                 "acontecendo com as",
                 "transmissões.",
                 "Estavam falando",
                 "da TEAM ROCKET.",
                 "{PLAYER}, você",
                 "sabe de alguma",
                 "coisa?",
                 "Será que a TEAM",
                 "ROCKET voltou?",
                 "Não, isso não pode",
                 "ser verdade.",
                 "Desculpe incomodar",
                 "Se cuide!"),
    "41:57a6": L("41:57a6",
                 "Alô, {PLAYER}?",
                 "Tenho uma coisa",
                 "aqui para você.",
                 "Pode dar uma",
                 "passada no LAB?",
                 "Até mais!"),
    "41:57fa": L("41:57fa",
                 "Alô, {PLAYER}?",
                 "Como vai?",
                 "Consegui uma",
                 "coisa bacana.",
                 "Passe no meu LAB",
                 "e pegue!",
                 "Até mais!"),

    # ---------------- saudacoes de quem liga ----------------
    "41:5862": L("41:5862",
                 "Alô. Aqui é",
                 "{STRBUF}…",
                 "Bom dia,",
                 "{PLAYER}!"),
    "41:588a": L("41:588a",
                 "Alô. Aqui é",
                 "{STRBUF}…",
                 "Como vai,",
                 "{PLAYER}?"),
    "41:58b3": L("41:58b3",
                 "Alô. Aqui é",
                 "{STRBUF}…",
                 "Boa noite,",
                 "{PLAYER}!"),
    "41:58db": L("41:58db",
                 "Oi. Aqui é",
                 "{STRBUF}.",
                 "Oi, {PLAYER}!",
                 "Bom dia."),
    "41:5904": L("41:5904",
                 "Oi. Aqui é",
                 "{STRBUF}.",
                 "Oi, {PLAYER}!",
                 "Tudo bem?"),
    "41:592c": L("41:592c",
                 "Oi. Aqui é",
                 "{STRBUF}.",
                 "Oi, {PLAYER}!",
                 "Boa noite."),
    "41:5955": L("41:5955",
                 "{PLAYER}, bom",
                 "dia!",
                 "É {STRBUF}.",
                 "Como você está?"),
    "41:5989": L("41:5989",
                 "{PLAYER}, oi!",
                 "É {STRBUF}.",
                 "O tempo está bom?"),
    "41:59b5": L("41:59b5",
                 "{PLAYER}, boa",
                 "noite!",
                 "É {STRBUF}.",
                 "Tem um minuto?"),
    "41:59e4": L("41:59e4",
                 "Bom dia,",
                 "{PLAYER}.",
                 "Aqui é {STRBUF}.",
                 "Eu te acordei?"),
    "41:5a15": L("41:5a15",
                 "Alô, {PLAYER}.",
                 "Aqui é {STRBUF}.",
                 "Como vai tudo?"),
    "41:5a3f": L("41:5a3f",
                 "Boa noite,",
                 "{PLAYER}.",
                 "Aqui é {STRBUF}.",
                 "Estava acordado?"),

    # ---------------- o treinador fala do POKéMON dele ----------------
    "41:5a70": L("41:5a70",
                 "Como estão seus",
                 "POKéMON?",
                 "Meu {STRBUF} é",
                 "muito animado.",
                 "Dá trabalho!"),
    "41:5ab5": L("41:5ab5",
                 "Como estão seus",
                 "POKéMON?",
                 "Eu mantenho meu",
                 "{STRBUF} em dia",
                 "indo sempre aos",
                 "CENTROS POKéMON."),
    "41:5b0d": L("41:5b0d",
                 "Meu {STRBUF}",
                 "está lindo.",
                 "Queria poder",
                 "te mostrar."),
    "41:5b42": L("41:5b42",
                 "Eu enfeitei meu",
                 "{STRBUF}.",
                 "Ficou ainda mais",
                 "fofo que antes."),
    "41:5b7b": L("41:5b7b",
                 "Ah, sim, consegui",
                 "vencer um",
                 "{STRBUF} durão.",
                 "Preciso deixar meu",
                 "time mais forte."),
    "41:5bcb": L("41:5bcb",
                 "Você tem que ouvir",
                 "isso! Eu lutei",
                 "com {STRBUF}",
                 "outro dia.",
                 "Foi fácil! Tinha",
                 "vantagem de tipo."),
    "41:5c27": L("41:5c27",
                 "Ei, escuta!",
                 "Quase peguei",
                 "{STRBUF} outro",
                 "dia.",
                 "Ah, foi por muito",
                 "pouco!"),
    "41:5c76": L("41:5c76",
                 "Adivinha o que",
                 "rolou outro dia.",
                 "Perdi o {STRBUF}",
                 "de novo.",
                 "Talvez eu não seja",
                 "bom nisso…"),

    # ---------------- convite para revanche ----------------
    "41:5cdb": L("41:5cdb",
                 "Quer batalhar?",
                 "Não vai ser igual",
                 "à última vez que",
                 "a gente se viu.",
                 "Vou estar perto de",
                 "{STRBUF}."),
    "41:5d37": L("41:5d37",
                 "Você quer",
                 "batalhar? Eu vou",
                 "ganhar desta vez!",
                 "Vou estar te",
                 "esperando lá em",
                 "{STRBUF}.",
                 "Me procure, tá?"),

    # ---------------- engano ----------------
    "41:5da0": L("41:5da0",
                 "Alô? Aqui é",
                 "{STRBUF}…",
                 "Opa… Você não é",
                 "o KAZ! Desculpe,",
                 "número errado."),
    "41:5de2": L("41:5de2",
                 "Alô, aqui é",
                 "{STRBUF}. Como",
                 "vai, AUDREY?",
                 "Hã? {PLAYER}?",
                 "Opa! Foi engano!"),

    # ---------------- avistamento ----------------
    "41:5e48": L("41:5e48",
                 "Você tem que ver",
                 "isso! É doido!",
                 "Um monte de",
                 "{STRBUF}",
                 "apareceu perto de",
                 "{STRBUF}!"),
    "41:5e9c": L("41:5e9c",
                 "É incrível!",
                 "Em {STRBUF},",
                 "{STRBUF} estão",
                 "mordendo como se",
                 "não houvesse fim.",
                 "{PLAYER}, traga",
                 "sua ROD, amigo!"),
    "41:5efa": L("41:5efa",
                 "Um amigo acabou",
                 "de me contar.",
                 "Ele viu um monte",
                 "de {STRBUF} em",
                 "{STRBUF}.",
                 "{PLAYER}, vá",
                 "dar uma olhada."),
    "41:5f50": L("41:5f50",
                 "Estão fazendo o",
                 "Concurso de",
                 "Captura Insetos",
                 "hoje no PARK.",
                 "{PLAYER}, você",
                 "vai?"),
}
