# -*- coding: utf-8 -*-
"""Lote 17 -- banco 4d inteiro: rotas do norte, HIKERS e os pássaros lendários.

Rotas 42 a 46 e a subida para BLACKTHORN.  Falas de ver/vencer/perder,
mais as conversas sobre ARTICUNO/ZAPDOS/MOLTRES e o MORTY.

Ficam no original: KURT, LURE BALL, ULTRA BALL, HP UP, ARTICUNO, ZAPDOS,
MOLTRES, NIDOKING, POLIWAG, MARY, MORTY, HIKERS, ICE PATH, BLACKTHORN,
LAKE OF RAGE, ECRUTEAK, GOLDENROD.
"""
from pt.estrutura import linhas as L

DIALOGO = {
    # ---------------- os POKé FANS e os raros ----------------
    "4d:41d8": L("4d:41d8", "Como você pôde", "fazer isso comigo"),
    "4d:41f6": L("4d:41f6",
                 "Do que mais eu",
                 "gosto além de",
                 "POKéMON?",
                 "A MARY do rádio.",
                 "Deve ser fofa!"),
    "4d:423d": L("4d:423d",
                 "Ei! Você tem algum",
                 "POKéMON raro?"),
    "4d:425e": L("4d:425e",
                 "Ah, meus pobres",
                 "POKéMON queridos!"),
    "4d:427d": L("4d:427d",
                 "Eu ficaria feliz",
                 "só de ter um",
                 "POKéMON raro."),
    "4d:42aa": L("4d:42aa",
                 "Você acredita",
                 "nisso?",
                 "Um cara chamado",
                 "{RIVAL} zoou os",
                 "meus POKéMON!",
                 "Droga! Meu POKéMON",
                 "é ótimo!"),
    "4d:42fa": L("4d:42fa",
                 "Meu NIDOKING foi",
                 "muito bem!"),
    "4d:431c": L("4d:431c",
                 "Não tem problema",
                 "as pessoas gos-",
                 "tarem de tipos",
                 "diferentes.",
                 "POKéMON não é só",
                 "ter o mais",
                 "poderoso."),

    # ---------------- os pescadores ----------------
    "4d:4385": L("4d:4385",
                 "Estou numa fase",
                 "Deve ser o",
                 "equipamento.",
                 "Vamos lutar para",
                 "mudar o clima!"),
    "4d:43d4": L("4d:43d4",
                 "Perdi, mas me",
                 "sinto melhor."),
    "4d:43f7": L("4d:43f7",
                 "A LURE BALL do",
                 "KURT é a melhor",
                 "para pegar POKéMON",
                 "fisgado.",
                 "É bem mais",
                 "eficaz que uma",
                 "ULTRA BALL."),
    "4d:48d1": L("4d:48d1", "Deixa pra", "lá."),
    "4d:48e8": L("4d:48e8",
                 "Aquele POLIWAG",
                 "que escapou…",
                 "Era enorme.",
                 "Juro que tinha uns",
                 "5 metros!"),
    "4d:4937": L("4d:4937",
                 "Eu pesco até não",
                 "aguentar mais.",
                 "E luto até",
                 "cair também.",
                 "É essa a minha",
                 "relação com os",
                 "meus POKéMON."),
    "4d:4995": L("4d:4995", "Hmmmm…", "Não está certo."),
    "4d:49af": L("4d:49af",
                 "São 100 vitórias",
                 "e 101 derrotas.",
                 "Não vou lutar de",
                 "novo tão cedo."),

    # ---------------- as criancas e o piquenique ----------------
    "4d:4459": L("4d:4459",
                 "Dá para fazer",
                 "tanta coisa com",
                 "meu POKéMON!"),
    "4d:4489": L("4d:4489",
                 "Perder não tem",
                 "graça nenhuma…"),
    "4d:44a2": L("4d:44a2",
                 "O que está",
                 "havendo no LAKE?",
                 "A gente ia",
                 "acampar lá."),
    "4d:44e5": L("4d:44e5",
                 "Você também vai",
                 "ao LAKE OF RAGE?",
                 "Vamos brincar um",
                 "pouquinho!"),
    "4d:4528": L("4d:4528", "Brinquei demais!"),
    "4d:453c": L("4d:453c",
                 "Estou num pique-",
                 "nique com POKéMON",
                 "Não quer vir?"),

    # ---------------- os pássaros lendários ----------------
    "4d:49ef": L("4d:49ef",
                 "Você conhece os",
                 "POKéMON pássaro",
                 "lendários?"),
    "4d:4a1b": L("4d:4a1b", "Ufa! Você é bom", "mesmo."),
    "4d:4a33": L("4d:4a33",
                 "ARTICUNO, ZAPDOS",
                 "e MOLTRES são",
                 "os três POKéMON",
                 "pássaro lendários",
                 "Mas ouvi que tem",
                 "outros pássaros",
                 "lendários também."),
    "4d:4aa7": L("4d:4aa7", "Eu vou ganhar,", "com certeza!"),
    "4d:4ac0": L("4d:4ac0", "Arrgh… Que", "derrota chocante…"),
    "4d:4adf": L("4d:4adf",
                 "É importante ter",
                 "convicção do seu",
                 "lado."),
    "4d:4b0f": L("4d:4b0f",
                 "Faço qualquer",
                 "coisa para pôr a",
                 "mão em raros!"),
    "4d:4b3e": L("4d:4b3e",
                 "Oooh, seus POKéMON",
                 "são atraentes."),
    "4d:4b61": L("4d:4b61",
                 "Se um POKéMON tem",
                 "cores diferentes",
                 "do normal, ele",
                 "vale mais.",
                 "O quê? Isso não",
                 "é verdade?"),

    # ---------------- os veteranos ----------------
    "4d:4bbf": L("4d:4bbf",
                 "Dá para ver que",
                 "você é um bom",
                 "treinador.",
                 "Eu sou bom em",
                 "POKéMON e vejo que",
                 "você também é."),
    "4d:4c26": L("4d:4c26", "Tch! Foi derrota", "total pra mim."),
    "4d:4c49": L("4d:4c49",
                 "Uau. Você tem",
                 "muitas BADGES.",
                 "Não é à toa que",
                 "é tão forte.",
                 "Será que o MORTY",
                 "do GINÁSIO de",
                 "ECRUTEAK ainda",
                 "está treinando?",
                 "Ele me arrebentou",
                 "feio."),
    "4d:4cd0": L("4d:4cd0",
                 "Você parece forte",
                 "Bons treinadores",
                 "procuram rivais",
                 "fortes por si."),
    "4d:4d14": L("4d:4d14", "Não! Assim não", "dá mesmo."),
    "4d:4d30": L("4d:4d30",
                 "A gente melhora",
                 "vivendo muitas",
                 "batalhas.",
                 "Lutei muito para",
                 "ser o que sou",
                 "hoje, uma elite."),

    # ---------------- os HIKERS ----------------
    "4d:504b": L("4d:504b",
                 "Vou voltar para o",
                 "ICE PATH de",
                 "BLACKTHORN e",
                 "treinar mais."),
    "4d:5087": L("4d:5087",
                 "Ei! Você tem gar-",
                 "ra! Mas sabe?",
                 "Quando o assunto",
                 "é garra pura,",
                 "o cara sou eu!"),
    "4d:50dc": L("4d:50dc",
                 "Meus POKéMON não",
                 "tiveram garra!"),
    "4d:50fb": L("4d:50fb",
                 "Nossa, como eu",
                 "amo HP UP! Hmmm!",
                 "Fico bebendo o",
                 "dos meus POKéMON!",
                 "Não me controlo!"),
    "4d:5147": L("4d:5147", "Meus POKéMON são", "pura força!"),
    "4d:5162": L("4d:5162", "Uahahah! Eu sou o", "grande perdedor!"),
    "4d:517e": L("4d:517e",
                 "Eu não sou bom de",
                 "pensar, sabe?",
                 "Então eu vou de",
                 "força mesmo!"),
    "4d:51c4": L("4d:51c4",
                 "Por que eu subo",
                 "montanhas?",
                 "Porque elas estão",
                 "lá.",
                 "Por que eu treino",
                 "POKéMON?",
                 "Porque eles estão",
                 "lá!"),
    "4d:5220": L("4d:5220", "Derrotas…", "Também estão lá!"),
    "4d:523b": L("4d:523b",
                 "A melhor coisa",
                 "que já me acon-",
                 "teceu foi conhecer",
                 "POKéMON."),
    "4d:5276": L("4d:5276",
                 "Eu estava treinan-",
                 "do sozinho aqui.",
                 "Veja o fruto do",
                 "meu trabalho!"),
    "4d:52bc": L("4d:52bc",
                 "Isso pede medidas",
                 "extremas.",
                 "Vou para as monta-",
                 "nhas treinar na",
                 "solidão."),
    "4d:5652": L("4d:5652", "Piedade! Você me", "mostrou a força!"),
    "4d:5674": L("4d:5674",
                 "Acabou. Tudo bem.",
                 "Nós HIKERS somos",
                 "assim mesmo."),

    # ---------------- os sabios ----------------
    "4d:530e": L("4d:530e",
                 "O que você acha",
                 "sobre criar",
                 "POKéMON?"),
    "4d:5339": L("4d:5339", "Você ganhou meu", "respeito."),
    "4d:5350": L("4d:5350",
                 "Vejo que você cria",
                 "os seus POKéMON",
                 "com carinho.",
                 "O laço que vocês",
                 "criam vai salvar",
                 "você nos apertos."),
    "4d:53b2": L("4d:53b2",
                 "Qual é a sua",
                 "estratégia?",
                 "É tolice usar",
                 "golpes fortes",
                 "sem critério."),
    "4d:5414": L("4d:5414",
                 "Não sou a favor",
                 "de golpes fortes",
                 "demais.",
                 "Quero ganhar, mas",
                 "também não quero",
                 "ferir POKéMON."),
    "4d:5473": L("4d:5473", "Eu também sou bom", "de POKéMON."),

    # ---------------- quem cria POKéMON ----------------
    "4d:56a5": L("4d:56a5",
                 "Eu também crio",
                 "POKéMON!",
                 "Quer batalhar",
                 "comigo?"),
    "4d:56dd": L("4d:56dd",
                 "Dei o meu melhor",
                 "e não bastou.",
                 "Sem desculpa, eu",
                 "admito que perdi."),
    "4d:571b": L("4d:571b",
                 "Eu também crio",
                 "POKéMON!",
                 "Vamos lutar!"),
    "4d:5749": L("4d:5749",
                 "Já fui a muitos",
                 "GINÁSIOS, mas o",
                 "de GOLDENROD é o",
                 "meu favorito.",
                 "Ele é cheio de",
                 "flores lindas!"),

    # ---------------- os cacadores de inseto ----------------
    "4d:5c53": L("4d:5c53",
                 "Vou procurar",
                 "POKéMON inseto",
                 "mais fortes."),
    "4d:5c7c": L("4d:5c7c",
                 "Se você anda no",
                 "mato alto de",
                 "shorts, se corta",
                 "todo?"),
    "4d:5cc2": L("4d:5cc2", "Ai, ai, ai!"),
    "4d:5cd5": L("4d:5cd5",
                 "Arde de verdade",
                 "quando você toma",
                 "banho."),
    "4d:5d00": L("4d:5d00",
                 "Por que as meninas",
                 "não gostam deles?"),
    "4d:5d29": L("4d:5d29",
                 "POKéMON inseto",
                 "afundam feito",
                 "pelúcia quando",
                 "você aperta.",
                 "Eu adoro essa",
                 "sensação!"),
}
