# -*- coding: utf-8 -*-
"""Lote 28 -- as 101 derivadas do banco 5e: a CELADON DEPT. STORE, o
GAME CORNER, a CELADON MANSION (GAME FREAK), o GINASIO da ERIKA, o
EATATHON CONTEST, a CYCLING ROAD e a vending machine.

Ficam no original: ERIKA, JASMINE, CELADON, GOLDENROD, FUCHSIA CITY,
KANTO, JOHTO, CYCLING ROAD, POKéDEX, POKéMON, GAME FREAK, DEPT. STORE,
PORYGON, MR.MIME, PIKACHU, MEOWTH, TEAM ROCKET, GAME CORNER, SURF MAIL,
LOVELY MAIL, COIN CASE, BICYCLE, UPGRADE, TM03, CURSE, GIGA DRAIN,
RAINBOWBADGE, PRODUCER, CHEF, TM, PS, MAIL, PRODUTOR.
"""
from pt.estrutura import linhas as L

DIALOGO = {

    # ---------------- banco 5e ----------------
    "5e:4011": L("5e:4011",
                 "Bem-vindo à LOJA",
                 "DE DEPARTAMENTOS",
                 "CELADON!",
                 "O índice está",
                 "na parede."),
    "5e:4057": L("5e:4057",
                 "Esta LOJA é da",
                 "mesma rede que a",
                 "de GOLDENROD.",
                 "As duas foram",
                 "reformadas ao",
                 "mesmo tempo,",
                 "juntas."),
    "5e:40cb": L("5e:40cb",
                 "É minha primeira",
                 "vez aqui.",
                 "É tão grande…",
                 "Tenho medo de me",
                 "perder."),
    "5e:410c": L("5e:410c",
                 "1º ANDAR: RECEPÇÃO",
                 "E SERVIÇOS",
                 "2º ANDAR: MERCADO",
                 "DO TREINADOR",
                 "3º: LOJA DE TM",
                 "4º: PRESENTES",
                 "5º: FARMÁCIA",
                 "6º: MÁQ. DE",
                 "VENDAS"),
    "5e:41ed": L("5e:41ed",
                 "Me tornei",
                 "treinador",
                 "por incentivo do",
                 "meu filho.",
                 "Fico impressionado",
                 "com a seleção de",
                 "itens práticos."),
    "5e:4262": L("5e:4262",
                 "Meu pai está tendo",
                 "trabalho para",
                 "decorar os nomes",
                 "dos itens e como",
                 "eles devem ser",
                 "usados…"),
    "5e:42c0": L("5e:42c0",
                 "Produtos ótimos",
                 "para treinadores!",
                 "2º ANDAR: MERCADO",
                 "DO TREINADOR"),
    "5e:4377": L("5e:4377",
                 "Não consigo",
                 "decidir em qual",
                 "POKéMON usar esta",
                 "TM…"),
    "5e:43aa": L("5e:43aa",
                 "Opa! Negociei meu",
                 "POKéMON sem tirar",
                 "o UPGRADE que o",
                 "POKéMON tinha."),
    "5e:43eb": L("5e:43eb",
                 "Enfim consegui um",
                 "PORYGON!",
                 "Sou péssimo nas",
                 "máquinas, nunca",
                 "juntaria moedas",
                 "para trocar…",
                 "…Hã?",
                 "O PORYGON trocado",
                 "virou outro",
                 "POKéMON!"),
    "5e:4485": L("5e:4485",
                 "LOJA DE TM vende",
                 "golpes raros."),
    "5e:44a9": L("5e:44a9",
                 "3º ANDAR: LOJA",
                 "DE TM! Deixe seu",
                 "POKéMON forte!"),
    "5e:4545": L("5e:4545",
                 "Vim comprar uma",
                 "SURF MAIL para",
                 "minha namorada."),
    "5e:4579": L("5e:4579",
                 "Este é o único",
                 "lugar onde você",
                 "compra uma LOVELY",
                 "MAIL."),
    "5e:45b0": L("5e:45b0",
                 "Dê seu recado",
                 "com PRESENTES!",
                 "4º: PRESENTES"),
    "5e:4647": L("5e:4647",
                 "Quero comprar",
                 "itens que elevem",
                 "os status do",
                 "POKéMON, mas não",
                 "tenho dinheiro…"),
    "5e:4696": L("5e:4696",
                 "Quero um PP UP,",
                 "pra elevar o PP",
                 "dos golpes, mas",
                 "não dá comprar"),
    "5e:46da": L("5e:46da",
                 "Usar itens neles",
                 "deixa o POKéMON",
                 "feliz.",
                 "Eles odeiam alguns",
                 "itens, porém…"),
    "5e:4724": L("5e:4724",
                 "5º ANDAR FARMÁCIA"),
    "5e:486c": L("5e:486c",
                 "Uma máquina de",
                 "vendas! O menu:"),
    "5e:4890": L("5e:4890",
                 "Click!",
                 "{STRBUF}",
                 "saiu."),
    "5e:48aa": L("5e:48aa",
                 "Opa, dinheiro",
                 "insuficiente…"),
    "5e:48c3": L("5e:48c3",
                 "Não há mais espaço",
                 "para coisas…"),
    "5e:48e3": L("5e:48e3",
                 "Uma máquina de",
                 "vendas com roleta",
                 "de prêmios…",
                 "Você não vê mais",
                 "dessas hoje."),
    "5e:492c": L("5e:492c",
                 "Ahh! Não há jogos",
                 "aqui!",
                 "Eu queria jogar…"),
    "5e:495a": L("5e:495a",
                 "6º ANDAR: PRAÇA DO",
                 "TELHADO: VENDAS"),
    "5e:4a32": L("5e:4a32",
                 "Meus POKéMON me",
                 "fazem companhia,",
                 "nunca me sinto",
                 "sozinho.",
                 "Até o MEOWTH",
                 "traz dinheiro."),
    "5e:4ac7": L("5e:4ac7",
                 "SUÍTE DO GERENTE",
                 "DA MANSÃO CELADON"),
    "5e:4b55": L("5e:4b55",
                 "{PLAYER} ligou o",
                 "PC.",
                 "…",
                 "Alguém estava no",
                 "meio de escrever",
                 "um e-mail.",
                 "…Espero que",
                 "visite KANTO.",
                 "Vai se surpreender",
                 "com quanta coisa",
                 "muita coisa",
                 "mudou por aqui.",
                 "Também verá",
                 "vários POKéMON",
                 "que não existem",
                 "em JOHTO.",
                 "Ao PRODUTOR",
                 "…"),
    "5e:4c48": L("5e:4c48",
                 "GAME FREAK",
                 "SALA DE ENCONTROS"),
    "5e:4cea": L("5e:4cea",
                 "Isso mesmo!",
                 "Sou o DESIGNER",
                 "do JOGO!",
                 "Completar sua",
                 "POKéDEX é duro,",
                 "mas não desista!"),
    "5e:4d41": L("5e:4d41",
                 "Uau! Excelente!",
                 "Você completou sua",
                 "POKéDEX!",
                 "Parabéns!"),
    "5e:4d7f": L("5e:4d7f",
                 "O ARTISTA GRÁFICO",
                 "vai imprimir um",
                 "DIPLOMA pra você.",
                 "Deve mostrá-lo por",
                 "aí."),
    "5e:4dd0": L("5e:4dd0",
                 "Sou o ARTISTA",
                 "GRÁFICO.",
                 "Eu te desenhei!"),
    "5e:4df4": L("5e:4df4",
                 "Sou o ARTISTA",
                 "GRÁFICO.",
                 "Ah, completou sua",
                 "POKéDEX?",
                 "Posso imprimir",
                 "o seu DIPLOMA?"),
    "5e:4e4c": L("5e:4e4c",
                 "Me avise se quiser",
                 "imprimir o",
                 "DIPLOMA."),
    "5e:4eb1": L("5e:4eb1",
                 "Quem, eu? Sou o",
                 "PROGRAMADOR.",
                 "Jogue nas máquinas",
                 "caça-níqueis!"),
    "5e:4ee6": L("5e:4ee6",
                 "As GÊMEAS são",
                 "adoráveis!",
                 "JASMINE também",
                 "é bonita.",
                 "Ah, eu as adoro!"),
    "5e:4f27": L("5e:4f27",
                 "GAME FREAK",
                 "SALA DE PRODUÇÃO"),
    "5e:4f44": L("5e:4f44",
                 "É um desenho",
                 "detalhado de uma",
                 "moça bonita."),
    "5e:4f6e": L("5e:4f6e",
                 "É o programa do",
                 "jogo. Mexer nele",
                 "pode causar um bug",
                 "no jogo!"),
    "5e:4fb2": L("5e:4fb2",
                 "Está cheio de",
                 "materiais de",
                 "referência e até",
                 "um POKé DOLL."),
    "5e:50ad": L("5e:50ad",
                 "Deixe-me contar",
                 "algo terrível…"),
    "5e:50d0": L("5e:50d0",
                 "Claro, não é tão",
                 "assustador",
                 "enquanto ainda há",
                 "luz do dia.",
                 "Volte depois do",
                 "pôr do sol, tá?"),
    "5e:5129": L("5e:5129",
                 "Era uma vez",
                 "um menino que",
                 "ganhou uma",
                 "BICYCLE nova…",
                 "Quis testá-la",
                 "na mesma hora…",
                 "Se divertia tanto",
                 "que nem notou",
                 "que o sol tinha",
                 "se posto…",
                 "Voltando pra casa",
                 "na noite escura,",
                 "e a BICYCLE",
                 "parou de repente",
                 "Os pedais ficaram",
                 "pesados!",
                 "Quando parou",
                 "de pedalar, a",
                 "BICYCLE foi",
                 "puxada pra trás!",
                 "Como se fosse",
                 "amaldiçoada e",
                 "quisesse levá-lo",
                 "pro abismo!",
                 "…",
                 "…",
                 "SHRIEEEEK!",
                 "O menino estava",
                 "subindo a",
                 "CYCLING ROAD",
                 "…",
                 "Tum-tum-tum!",
                 "Por ter ouvido",
                 "com paciência,",
                 "fique com a TM03!"),
    "5e:5339": L("5e:5339",
                 "O TM03 é CURSE.",
                 "É um golpe que",
                 "drena o PS da",
                 "vítima aos",
                 "poucos."),
    "5e:53b4": L("5e:53b4",
                 "ERIKA é mestre em",
                 "POKéMON do tipo",
                 "grama. Ela vai",
                 "fazer você pagar",
                 "se bobear."),
    "5e:5405": L("5e:5405",
                 "O esconderijo",
                 "da EQUIPE ROCKET",
                 "fica no porão da",
                 "CASA DE JOGOS.",
                 "Ah, espera. Isso",
                 "foi há três anos."),
    "5e:5571": L("5e:5571",
                 "Bem-vindo!",
                 "Você pode trocar",
                 "suas moedas por",
                 "prêmios incríveis",
                 "na casa ao lado."),
    "5e:55b6": L("5e:55b6",
                 "As caça-níqueis",
                 "são todas de",
                 "última geração."),
    "5e:55e3": L("5e:55e3",
                 "É esta máquina",
                 "que eu quero.",
                 "Ela me limpou",
                 "ontem, então",
                 "deveria pagar",
                 "hoje."),
    "5e:5636": L("5e:5636",
                 "Acho que esta",
                 "máquina vai pagar",
                 "agora…",
                 "As chances variam",
                 "entre máquinas."),
    "5e:567d": L("5e:567d",
                 "Hahahaha!",
                 "As moedas não",
                 "param de sair!",
                 "Hã? Quer jogar,",
                 "garoto?",
                 "Vou dividir minha",
                 "sorte com você!"),
    "5e:56e6": L("5e:56e6",
                 "Hahahaha!",
                 "É bom fazer",
                 "coisas boas para",
                 "as outras",
                 "pessoas!"),
    "5e:572b": L("5e:572b",
                 "Ei, você não tem",
                 "uma COIN CASE.",
                 "Como vou te dar",
                 "moedas, se você",
                 "não tem uma?"),
    "5e:577a": L("5e:577a",
                 "Ei, sua COIN",
                 "CASE está cheia.",
                 "Você deve estar",
                 "numa maré de",
                 "sorte também."),
    "5e:57c6": L("5e:57c6",
                 "Ei! Futuro",
                 "CAMPEÃO!",
                 "Também joga nas",
                 "caça-níqueis?",
                 "Estou tentando",
                 "juntar moedas",
                 "para um POKéMON",
                 "de prêmio. Mas",
                 "ainda não tenho…"),
    "5e:584e": L("5e:584e",
                 "Hmm… As chances",
                 "são melhores na",
                 "fila do PIKACHU,",
                 "…o que fazer?"),
    "5e:5894": L("5e:5894",
                 "Ei!",
                 "Atrás deste",
                 "pôster…",
                 "Não há nada!"),
    "5e:58c2": L("5e:58c2",
                 "Ei!",
                 "Atrás deste",
                 "pôster…",
                 "Não há nada!"),
    "5e:58f0": L("5e:58f0",
                 "Há um isqueiro",
                 "aqui."),
    "5e:5908": L("5e:5908",
                 "Uma latinha de",
                 "refri. Alguém vem",
                 "buscar depois…",
                 "Hã? Está vazia!"),
    "5e:5c59": L("5e:5c59",
                 "Queria um MR.MIME",
                 "mas me faltaram",
                 "100 moedas…"),
    "5e:5c8a": L("5e:5c8a",
                 "Ufa…",
                 "Preciso ficar",
                 "calmo e frio…",
                 "Não posso perder",
                 "a calma, ou",
                 "perco o dinheiro…"),
    "5e:5cdf": L("5e:5cdf",
                 "Bem-vindo!",
                 "Trocamos suas",
                 "moedas por",
                 "prêmios incríveis"),
    "5e:5d15": L("5e:5d15",
                 "Qual prêmio você",
                 "quer?"),
    "5e:5d32": L("5e:5d32",
                 "Então você quer",
                 "o {STRBUF}?"),
    "5e:5d4e": L("5e:5d4e",
                 "Aqui está!"),
    "5e:5d5c": L("5e:5d5c",
                 "Você não tem",
                 "moedas pra isso…"),
    "5e:5d79": L("5e:5d79",
                 "Você não tem",
                 "espaço para isto."),
    "5e:5d93": L("5e:5d93",
                 "Oh. Volte com",
                 "mais moedas!"),
    "5e:5db5": L("5e:5db5",
                 "Oh? Você não tem",
                 "a COIN CASE."),
    "5e:5ec9": L("5e:5ec9",
                 "ERIKA: Olá…",
                 "Que tempo",
                 "agradável, hein?",
                 "É tão calmo…",
                 "Posso até",
                 "cochilar…",
                 "Me chamo ERIKA.",
                 "Sou a LÍDER do",
                 "GINÁSIO CELADON.",
                 "…Oh? Você veio",
                 "de JOHTO?",
                 "Que bom…",
                 "Oh. Desculpe, não",
                 "percebi que",
                 "queria me",
                 "desafiar.",
                 "Muito bem, mas",
                 "não vou perder."),
    "5e:5fdf": L("5e:5fdf",
                 "ERIKA: Oh!",
                 "Admito a derrota…",
                 "Você é realmente",
                 "forte…",
                 "Vou lhe dar a",
                 "RAINBOWBADGE…"),
    "5e:6037": L("5e:6037",
                 "{PLAYER} recebeu",
                 "a RAINBOWBADGE."),
    "5e:6051": L("5e:6051",
                 "ERIKA: Foi uma",
                 "partida adorável.",
                 "Me senti",
                 "inspirada.",
                 "Fique com este",
                 "TM.",
                 "É GIGA DRAIN.",
                 "É um golpe que",
                 "drena metade do",
                 "dano causado,",
                 "curando seu",
                 "POKéMON. Se",
                 "quiser, use…"),
    "5e:6100": L("5e:6100",
                 "sar seu",
                 "POKéMON. Por",
                 "favor, use se",
                 "quiser…"),
    "5e:6130": L("5e:6130",
                 "ERIKA: Perder",
                 "deixa um gosto",
                 "amargo…",
                 "Mas saber que",
                 "há treinadores",
                 "fortes me espole",
                 "a melhorar…"),
    "5e:64ba": L("5e:64ba",
                 "Oi!",
                 "Estamos fazendo",
                 "uma competição",
                 "de comilança. Não",
                 "podemos atender."),
    "5e:6505": L("5e:6505",
                 "…Nhac, nhac…"),
    "5e:6516": L("5e:6516",
                 "Não fale comigo!",
                 "Você vai quebrar",
                 "a concentração!"),
    "5e:6546": L("5e:6546",
                 "…Glup… Glup…"),
    "5e:6554": L("5e:6554",
                 "Quero quantidade",
                 "antes de",
                 "qualidade! Fico",
                 "feliz quando como"),
    "5e:658a": L("5e:658a",
                 "Nhac, nhac…"),
    "5e:6599": L("5e:6599",
                 "A comida é boa",
                 "aqui, mas a de",
                 "GOLDENROD é a",
                 "melhor de todas."),
    "5e:65dd": L("5e:65dd",
                 "Nhac… nhac…"),
    "5e:65ee": L("5e:65ee",
                 "Ninguém aqui vai",
                 "te dar uma COIN",
                 "CASE. Procure em",
                 "JOHTO."),
    "5e:6630": L("5e:6630",
                 "Nhac… nhac…",
                 "Ainda posso comer"),
    "5e:6654": L("5e:6654",
                 "Manda mais, CHEF!"),
    "5e:6661": L("5e:6661",
                 "Competição de",
                 "comilança! Sem",
                 "limite de tempo!",
                 "batalha sem fim!",
                 "O maior comedor",
                 "leva tudo grátis!"),
    "5e:66c3": L("5e:66c3",
                 "{PLAYER} achou",
                 "um {STRBUF}."),
    "5e:66d5": L("5e:66d5",
                 "Mas {PLAYER} não",
                 "pode levar mais"),
    "5e:6757": L("5e:6757",
                 "Se você descer a",
                 "CYCLING ROAD,",
                 "você vai parar",
                 "em FUCHSIA CITY."),
    "5e:67e6": L("5e:67e6",
                 "A CYCLING ROAD",
                 "começa aqui. É",
                 "tudo ladeira",
                 "abaixo, e bem",
                 "emocionante!",
                 "Uma sensação",
                 "que só se sente",
                 "em navio",
                 "ou trem."),
    "5e:6874": L("5e:6874",
                 "Ei! Pare!",
                 "Você não pode ir",
                 "para a CYCLING",
                 "ROAD sem",
                 "BICYCLE."),
    "5e:690a": L("5e:690a",
                 "Você soube do",
                 "acidente na USINA",
                 "DE ENERGIA?",
                 "Fica a leste,",
                 "perto da CIDADE",
                 "LAVANDA."),
    "5e:6970": L("5e:6970",
                 "Levo meu trabalho",
                 "de GUARDA a sério",
                 "Ei! Você tem uma",
                 "POKéDEX.",
                 "Certo. Você pode",
                 "passar."),
    "5e:6a0a": L("5e:6a0a",
                 "CYCLING ROAD",
                 "a subida começa"),
    "5e:6a2b": L("5e:6a2b",
                 "Espera! Você não",
                 "tem BICYCLE?",
                 "A CYCLING ROAD",
                 "fica aqui.",
                 "Você precisa de",
                 "BICYCLE pra ir"),
    "5e:8b63": L("5e:8b63",
                 "…"),
    "5e:ce62": L("5e:ce62",
                 "ado por pessoa",
                 "má, acaba ficando",
                 "mau também."),
}