# -*- coding: utf-8 -*-
"""Lote 26 -- as ultimas varridas: o GINÁSIO de BROCK e o circuito de
nadadores de Cianwood (54), o CONCURSO DE CAPTURA e os rádios (56), a
GOLDENROD dos treinadores, da bike e do SWEET HONEY (57), o GINÁSIO
elétrico do LT.SURGE (59), o GINÁSIO de pedra de BROCK (5a), as RUÍNAS
DE ALPH (5b), os artistas marciais (5d) e as meninas da ERIKA (5e).

Ficam no original: LT.SURGE, BROCK, WHITNEY, MISTY, ERIKA, DAISY,
MEOWTH, JOHTO, POKéMON, GINÁSIO, SWEET HONEY, SILPHSCOPE, DEFESA,
INSÍGNIAS, RUÍNAS, BICICLETAS.
"""
from pt.estrutura import linhas as L

DIALOGO = {

    # ---------------- banco 54 ----------------
    "54:4762": L("54:4762",
                 "Desculpe por me",
                 "ausentar… Vamos",
                 "continuar!"),
    "54:4790": L("54:4790",
                 "Eu desisto! Você é",
                 "o vencedor!"),
    "54:47ae": L("54:47ae",
                 "Vou nadar em",
                 "silêncio."),
    "54:47c8": L("54:47c8",
                 "Não deixe minha",
                 "elegante natação",
                 "te intimidar."),
    "54:47f7": L("54:47f7",
                 "Ooh, você me",
                 "venceu com calma…"),
    "54:4818": L("54:4818",
                 "Não fique tão con-",
                 "fiante ao ganhar.",
                 "MISTY vai te pegar",
                 "se você se des-",
                 "cuidar."),
    "54:486a": L("54:486a",
                 "Glub…",
                 "Eu sou o primeiro!",
                 "Venha me pegar!"),
    "54:489b": L("54:489b",
                 "MISTY melhorou",
                 "muito nos últimos",
                 "anos.",
                 "Não baixe a guar-",
                 "da, ou você será",
                 "esmagado!"),

    # ---------------- banco 56 ----------------
    "56:4c58": L("56:4c58",
                 "Qual tópico ler?"),
    "56:50b1": L("56:50b1",
                 "Esta máquina im-",
                 "prime dados como",
                 "figurinhas!"),
    "56:73ce": L("56:73ce",
                 "Dizem que há um",
                 "POKéMON parecido",
                 "com uma árvore.",
                 "Você pode revelar",
                 "sua identidade com",
                 "um SILPHSCOPE 2."),
    "56:7433": L("56:7433",
                 "O CONCURSO DE",
                 "CAPTURA ocorre",
                 "terça, quinta",
                 "e sábado.",
                 "Não só você ganha",
                 "um prêmio por",
                 "participar,",
                 "mas também fica",
                 "com o inseto que",
                 "você capturar."),

    # ---------------- banco 57 ----------------
    "57:43a0": L("57:43a0",
                 "Não pense que sou",
                 "fácil de vencer!"),
    "57:43bb": L("57:43bb",
                 "Droga… Pensei que",
                 "você fosse fraco…"),
    "57:43db": L("57:43db",
                 "No mundo dos",
                 "POKéMON, será que",
                 "é mais forte:",
                 "macho ou fêmea?"),
    "57:441b": L("57:441b",
                 "Gosto mais de POKé",
                 "MON fofos do que",
                 "dos fortes.",
                 "Mas tenho POKéMON",
                 "fortes e fofos!"),
    "57:447a": L("57:447a",
                 "Tento vencer a",
                 "WHITNEY, mas…",
                 "É deprimente.",
                 "Estou bem! Se eu",
                 "perder, tentarei",
                 "de novo da pró-",
                 "xima vez!"),
    "57:4537": L("57:4537",
                 "Oh, que treinador",
                 "bonitinho! Gosto",
                 "de você, mas não",
                 "vou me segurar!"),
    "57:457e": L("57:457e",
                 "Vejamos… Ops,",
                 "acabou?"),
    "57:4599": L("57:4599",
                 "Uau, você deve ser",
                 "bom pra me vencer!",
                 "Continue assim!"),
    "57:45c8": L("57:45c8",
                 "Dê o seu melhor,",
                 "ou eu vou te der-",
                 "rubar!"),
    "57:45f7": L("57:45f7",
                 "Não! Oh, MEOWTH,",
                 "me desculpe!"),
    "57:4615": L("57:4615",
                 "Ensinei ao MEOWTH",
                 "golpes para lidar",
                 "com todo tipo…"),
    "57:48ca": L("57:48ca",
                 "Acabaram de sair!",
                 "Bicicletas compac-",
                 "tas de primeira!"),
    "57:587b": L("57:587b",
                 "Queria te dar um",
                 "pouco de SWEET",
                 "HONEY, mas você",
                 "não tem espaço."),
    "57:58be": L("57:58be",
                 "Toma! Um pouco de",
                 "SWEET HONEY!"),
    "57:58e3": L("57:58e3",
                 "{PLAYER} recebeu",
                 "SWEET HONEY."),
    "57:58fc": L("57:58fc",
                 "Meu irmão pega o",
                 "SWEET HONEY, vai",
                 "pra algum lugar",
                 "com ele.",
                 "O que será que ele",
                 "está aprontando?"),
    "57:5956": L("57:5956",
                 "Você pôs SWEET",
                 "HONEY na árvore?",
                 "O que aconteceu",
                 "com ele?"),
    "57:598f": L("57:598f",
                 "Você pôs SWEET",
                 "HONEY na árvore?",
                 "Leva quase um",
                 "dia para o POKéMON",
                 "ser atraído."),
    "57:59e4": L("57:59e4",
                 "BUTTERFREE: Freh!"),
    "57:5c67": L("57:5c67",
                 "Dar itens para os",
                 "POKéMON segurarem",
                 "durante a batalha",
                 "pode virar o jogo",
                 "a seu favor."),

    # ---------------- banco 59 ----------------
    "59:4ea8": L("59:4ea8",
                 "Veio derrotar o",
                 "LT.SURGE?",
                 "Não enquanto eu",
                 "estiver aqui!"),
    "59:4ede": L("59:4ede",
                 "Desculpe, falhei",
                 "com o LT.SURGE,",
                 "senhor!"),
    "59:4f02": L("59:4f02",
                 "Quando eu estava",
                 "no exército, o",
                 "LT.SURGE salvou",
                 "a minha vida."),
    "59:4f3a": L("59:4f3a",
                 "LT.SURGE viu meu",
                 "potencial com",
                 "POKéMON elétri-",
                 "cos.",
                 "Acha que vai",
                 "me vencer?"),
    "59:4f89": L("59:4f89",
                 "Ooh, que choque!"),
    "59:4f9d": L("59:4f9d",
                 "Se as armadilhas",
                 "funcionassem,",
                 "você já estaria",
                 "frito…"),
    "59:4fd9": L("59:4fd9",
                 "Vou te derrubar!",
                 "Prepare-se para",
                 "levar um choque!"),
    "59:500c": L("59:500c",
                 "Gwaaah!",
                 "Fui superado…"),
    "59:5028": L("59:5028",
                 "Nada de se achar",
                 "por me vencer.",
                 "LT.SURGE é muito",
                 "durão."),
    "59:5791": L("59:5791",
                 "{STRBUF} parece",
                 "satisfeito."),
    "59:57a5": L("59:57a5",
                 "DAISY: Aí está!",
                 "Tudo pronto.",
                 "Viu? Não ficou",
                 "bonito, né?",
                 "É um POKéMON",
                 "muito fofo."),

    # ---------------- banco 5a ----------------
    "5a:435d": L("5a:435d",
                 "Os treinadores",
                 "deste GINÁSIO",
                 "usam POKéMON de",
                 "pedra. O tipo",
                 "pedra tem DEFESA",
                 "alta. As batalhas",
                 "podem demorar",
                 "bastante. Você",
                 "está preparado?"),
    "5a:43ec": L("5a:43ec",
                 "Preciso vencer",
                 "essas batalhas…"),
    "5a:440a": L("5a:440a",
                 "Ei, você! Treina-",
                 "dor de JOHTO!",
                 "BROCK é durão.",
                 "Vai te punir se",
                 "você não o levar",
                 "a sério."),

    # ---------------- banco 5b ----------------
    "5b:64e4": L("5b:64e4",
                 "Você conhece as",
                 "RUÍNAS DE ALPH?"),
    "5b:650d": L("5b:650d",
                 "Os rádios captam",
                 "sinais estranhos",
                 "nas RUÍNAS."),
    "5b:653f": L("5b:653f",
                 "Há painéis",
                 "esquisitos nas",
                 "RUÍNAS DE ALPH."),
    "5b:6586": L("5b:6586",
                 "Li que existem",
                 "quatro painéis de",
                 "pedra."),

    # ---------------- banco 5d ----------------
    "5d:4cae": L("5d:4cae",
                 "Nossa! Uma estante",
                 "cheia de CDs e ví-",
                 "deos de POKéMON.",
                 "Deve ser a",
                 "biblioteca."),
    "5d:52a5": L("5d:52a5",
                 "Se eu recuperar",
                 "meu POKéMON,",
                 "o que você vai",
                 "usar na batalha?"),
    "5d:568c": L("5d:568c",
                 "Meu POKéMON e eu",
                 "estamos unidos",
                 "pela amizade.",
                 "Nosso laço",
                 "nunca se quebra!"),
    "5d:56de": L("5d:56de",
                 "Isto não é real!"),
    "5d:56ef": L("5d:56ef",
                 "Você parece ter",
                 "um forte laço",
                 "com seu POKéMON!"),
    "5d:5723": L("5d:5723",
                 "Nada tememos,",
                 "nós, lutadores!"),
    "5d:5745": L("5d:5745",
                 "Isso é chocante!"),
    "5d:5756": L("5d:5756",
                 "POKéMON de luta",
                 "temem os psíqui-",
                 "cos…"),
    "5d:577f": L("5d:577f",
                 "Palavras são",
                 "inúteis. Deixe",
                 "os punhos falar!"),
    "5d:57b5": L("5d:57b5",
                 "Perdi! Estou",
                 "sem palavras!"),
    "5d:57ce": L("5d:57ce",
                 "Meus punhos fú-",
                 "rios despedaçam",
                 "seu POKéMON!"),
    "5d:57f7": L("5d:57f7",
                 "Fui despedaçado!"),
    "5d:5809": L("5d:5809",
                 "Meu POKéMON per-",
                 "deu… Meu orgulho",
                 "está quebrado…"),

    # ---------------- banco 5e ----------------
    "5e:4e7f": L("5e:4e7f",
                 "Algo está errado.",
                 "Terei que cancelar",
                 "a impressão."),
    "5e:5058": L("5e:5058",
                 "EU SEI TUDO!"),
    "5e:619d": L("5e:619d",
                 "Espere! Aqui só",
                 "entram garotas!"),
    "5e:61cd": L("5e:61cd",
                 "Nós não temos",
                 "nada contra os",
                 "meninos. Só há",
                 "assuntos que só",
                 "garotas podem",
                 "conversar."),
    "5e:622f": L("5e:622f",
                 "Oh, uma batalha?",
                 "Que assustador,",
                 "mas tudo bem!"),
    "5e:626a": L("5e:626a",
                 "Olha todas as",
                 "suas INSÍGNIAS.",
                 "Não é à toa que",
                 "não venci!"),
    "5e:62a1": L("5e:62a1",
                 "Você estava",
                 "olhando as flores",
                 "ou para mim?"),
    "5e:62dd": L("5e:62dd",
                 "Como faço para",
                 "ficar elegante",
                 "como a ERIKA?"),
    "5e:630e": L("5e:630e",
                 "Vamos mostrar",
                 "golpes que ERIKA",
                 "nos ensinou!"),
    "5e:634c": L("5e:634c",
                 "ERIKA vai se",
                 "vingar por nós!"),
    "5e:636d": L("5e:636d",
                 "Nós vamos proteger",
                 "a ERIKA!"),
    "5e:638b": L("5e:638b",
                 "Não conseguimos…"),
    "5e:639c": L("5e:639c",
                 "ERIKA é muito,",
                 "muito mais forte!"),
}