# -*- coding: utf-8 -*-
"""Lote 15c -- fim do banco 4b: a KATE, os casais e os caçadores de inseto.

Ficam no original: KURT, FAST BALL, POKé BALL, WHT APRICORN, VENONAT,
ILEX FOREST, NATIONAL PARK, BADGES, e os nomes IRENE, JENN, KATE.
"""
from pt.estrutura import linhas as L

DIALOGO = {
    # ---------------- a KATE, a irma mais velha ----------------
    "4b:576f": L("4b:576f",
                 "JENN: A luz do sol",
                 "deixa o corpo",
                 "mais forte."),
    "4b:5799": L("4b:5799",
                 "KATE: Você foi bem",
                 "malvado com as",
                 "minhas irmãzinhas"),
    "4b:57c9": L("4b:57c9",
                 "KATE: Não! Não",
                 "acredito nisso."),
    "4b:57eb": L("4b:57eb",
                 "KATE: Você é forte",
                 "demais. Eu não",
                 "tive chance.",
                 "Tome. Você merece",
                 "isto."),
    "4b:5834": L("4b:5834",
                 "KATE: Desculpe ter",
                 "pulado em cima.",
                 "Nunca esperamos",
                 "que alguém nos",
                 "achasse aqui. Você",
                 "nos assustou."),
    "4b:5893": L("4b:5893",
                 "ILEX FOREST",
                 "Pelo Portão"),

    # ---------------- os casais ----------------
    "4b:5c4d": L("4b:5c4d",
                 "A música do rádio",
                 "muda o humor dos",
                 "POKéMON selvagens"),
    "4b:5c81": L("4b:5c81",
                 "Vou mostrar para",
                 "minha namorada que",
                 "eu sou bom!"),
    "4b:5cac": L("4b:5cac",
                 "Queria que você",
                 "tivesse perdido…"),
    "4b:5cd0": L("4b:5cd0",
                 "Fui humilhado",
                 "na frente da minha",
                 "namorada…"),
    "4b:5cfd": L("4b:5cfd",
                 "Meu namorado é",
                 "fraco, não dá para",
                 "contar com ele."),
    "4b:5d29": L("4b:5d29",
                 "Nossa! Você é",
                 "tão forte!"),
    "4b:5d43": L("4b:5d43",
                 "Confio mais nos",
                 "meus POKéMON que",
                 "no meu namorado."),

    # ---------------- quem coleciona BADGE ----------------
    "4b:5d73": L("4b:5d73",
                 "Você vai para o",
                 "GINÁSIO? Eu vou!"),
    "4b:5d96": L("4b:5d96",
                 "Ah. Eu não",
                 "consegui…"),
    "4b:5daa": L("4b:5daa",
                 "As BADGES de",
                 "GINÁSIO são lindas",
                 "Eu coleciono."),

    # ---------------- as BALLS do KURT ----------------
    "4b:5dd6": L("4b:5dd6",
                 "Que tipo de POKé",
                 "BALL você usa?"),
    "4b:5df8": L("4b:5df8",
                 "Eita! Não fui",
                 "rápido o bastante"),
    "4b:5e11": L("4b:5e11",
                 "Alguns POKéMON",
                 "fogem na hora.",
                 "Tente pegar eles",
                 "com a FAST BALL",
                 "do KURT.",
                 "Sempre que acho um",
                 "WHT APRICORN, eu",
                 "levo para o KURT.",
                 "Ele faz uma POKé",
                 "BALL sob medida."),
    "4b:5eaa": L("4b:5eaa",
                 "Veja como eu sou",
                 "bom com a BALL!"),
    "4b:5ece": L("4b:5ece",
                 "Ufa! Que choque",
                 "foi esse!"),
    "4b:5ee6": L("4b:5ee6",
                 "Eu ia deslumbrar",
                 "você com o meu",
                 "POKéMON premiado.",
                 "Mas a sua força",
                 "me eletrizou!"),

    # ---------------- os cacadores de inseto ----------------
    "4b:5f36": L("4b:5f36",
                 "Eu vou a qualquer",
                 "lugar onde apareça",
                 "POKéMON inseto."),
    "4b:5f61": L("4b:5f61",
                 "Entendi. Então",
                 "você luta assim."),
    "4b:5f81": L("4b:5f81",
                 "Meu VENONAT ganhou",
                 "o Concurso de",
                 "Captura Insetos",
                 "no NATIONAL PARK."),
}
