# -*- coding: utf-8 -*-
"""Lote 8c -- a base secreta da TEAM ROCKET sob MAHOGANY, os tres andares.

Traduzido a partir do ingles original.  Chave = ponteiro da ROM USA.
Escrito com `linhas()` -- ver pt/estrutura.py.

Ficam no original: LANCE, GIOVANNI, MURKROW, ELECTRODE, PERSIAN,
TEAM ROCKET, ROCKETS, WHIRLPOOL, LAKE, MAHOGANY.  "EXECUTIVE" vira
"EXECUTIVO" e "MASTER" vira "MESTRE": sao cargos, nao nomes proprios.
"""
from pt.estrutura import linhas as L

DIALOGO = {
    # ---------------- B1F ----------------
    "45:47cd": L("45:47cd", "Ei!", "Invasor à vista!"),
    "45:47e3": L("45:47e3", "Droga… Eu falhei…"),
    "45:47f4": L("45:47f4", "Minha vez!", "Não tem saída!"),
    "45:4814": L("45:4814",
                 "Tem câmeras nas",
                 "estátuas de",
                 "POKéMON.",
                 "Vamos aparecendo",
                 "até você achar um",
                 "botão secreto."),
    "45:4a37": L("45:4a37",
                 "É uma estátua de",
                 "PERSIAN…",
                 "Os olhos dela são",
                 "muito brilhantes."),
    "45:4a68": L("45:4a68",
                 "Um botão secreto!",
                 "Melhor apertar."),
    "45:4a8b": L("45:4a8b",
                 "O botão está",
                 "desligado."),

    # ---------------- B2F: os EXECUTIVOS ----------------
    "45:4f65": L("45:4f65", "Pare bem", "aí!"),
    "45:4f7b": L("45:4f7b",
                 "Não podemos ter um",
                 "pirralho como você",
                 "solto por aí.",
                 "Faz mal para o",
                 "orgulho da TEAM",
                 "ROCKET, sabe.",
                 "Por mais forte que",
                 "seja, não dá para",
                 "encarar nós dois",
                 "ao mesmo tempo.",
                 "Sinto muito, bebê.",
                 "Prepare-se para",
                 "apanhar."),
    "45:5044": L("45:5044",
                 "Ei! Não seja tão",
                 "egoísta. Divida a",
                 "diversão."),
    "45:5075": L("45:5075",
                 "O quê? Você tinha",
                 "um cúmplice?",
                 "Cadê o seu",
                 "senso de honra?",
                 "Como chefe",
                 "interino no lugar",
                 "do GIOVANNI, vou",
                 "mostrar o erro",
                 "que é se meter",
                 "com a TEAM ROCKET"),
    "45:5114": L("45:5114",
                 "Tch, você é forte",
                 "mesmo.",
                 "Que pena.",
                 "Se você entrasse",
                 "na TEAM ROCKET,",
                 "podia virar um",
                 "EXECUTIVO."),
    "45:517e": L("45:517e",
                 "…Este esconderijo",
                 "já era…",
                 "Mas tudo bem.",
                 "O experimento de",
                 "transmissão foi um",
                 "sucesso total.",
                 "Não importa mais",
                 "o que acontece",
                 "com este lugar.",
                 "Temos planos bem",
                 "maiores.",
                 "Você vai conhecer",
                 "o verdadeiro",
                 "poder da TEAM",
                 "ROCKET em breve.",
                 "Aproveite enquanto",
                 "pode…",
                 "Fufufufu…"),

    # ---------------- B2F: o LANCE e o transmissor ----------------
    "45:5290": L("45:5290",
                 "LANCE: É isso.",
                 "Derrotamos todos",
                 "os ROCKETS",
                 "daqui.",
                 "Mas estou preocu-",
                 "pado com o rapaz",
                 "com quem batalhei",
                 "no caminho…"),
    "45:5306": L("45:5306",
                 "Desculpe, {PLAYER}",
                 "Vi como você ia",
                 "bem, então eu só",
                 "fiquei de fora.",
                 "Agora só falta",
                 "uma coisa:",
                 "desligar aquele",
                 "sinal de rádio."),
    "45:5387": L("45:5387",
                 "É esta máquina",
                 "que está causando",
                 "todo o problema.",
                 "Não vejo nenhum",
                 "botão nela…",
                 "Não temos escolha.",
                 "Vamos ter que",
                 "derrubar todos os",
                 "ELECTRODE.",
                 "Isso deve impedir",
                 "a máquina de",
                 "transmitir aquele",
                 "sinal estranho.",
                 "Os POKéMON não têm",
                 "culpa, então isso",
                 "me deixa com",
                 "remorso.",
                 "{PLAYER}, vamos",
                 "dividir a tarefa."),
    "45:54a2": L("45:54a2",
                 "LANCE: Deixe este",
                 "lado comigo."),
    "45:54c1": L("45:54c1",
                 "LANCE: Aquele",
                 "sinal estranho",
                 "finalmente parou.",
                 "O LAKE deve estar",
                 "normal de novo.",
                 "Você é o herói!",
                 "Muito obrigado",
                 "em nome de todos",
                 "os POKéMON.",
                 "Ah, sim. Você",
                 "devia levar isto.",
                 "Achei aqui, mas",
                 "não tenho uso",
                 "nenhum para isso."),
    "45:55b0": L("45:55b0",
                 "É o WHIRLPOOL.",
                 "Ensine para um",
                 "POKéMON e cruze",
                 "águas revoltas.",
                 "Mas lembre-se",
                 "de uma coisa.",
                 "Só dá para usar",
                 "fora de batalha",
                 "com a BADGE do",
                 "GINÁSIO MAHOGANY."),
    "45:564c": L("45:564c",
                 "{PLAYER}…",
                 "O caminho até se",
                 "tornar MESTRE",
                 "POKéMON é longo e",
                 "difícil.",
                 "Sabendo disso,",
                 "você vai seguir?",
                 "…",
                 "Entendo. Não, você",
                 "tem razão.",
                 "Se desistisse",
                 "assim tão fácil,",
                 "nunca teria",
                 "corrido atrás",
                 "desse sonho para",
                 "começar.",
                 "Espero ver você",
                 "de novo!"),
    "45:574f": L("45:574f",
                 "LANCE: Você está",
                 "bem?",
                 "Seus POKéMON estão",
                 "machucados.",
                 "Tome, dê um pouco",
                 "do meu remédio",
                 "para eles."),
    "45:57af": L("45:57af",
                 "LANCE: {PLAYER},",
                 "vamos dar o nosso",
                 "melhor por eles."),

    # ---------------- B2F: portas e maquina ----------------
    "45:59f1": L("45:59f1",
                 "A porta fechou…",
                 "Precisa de senha",
                 "para abrir."),
    "45:5a23": L("45:5a23",
                 "A porta fechou…",
                 "{PLAYER} digitou",
                 "a senha.",
                 "A porta abriu!"),
    "45:5a5f": L("45:5a5f",
                 "É o transmissor",
                 "de rádio que está",
                 "mandando o sinal",
                 "sinistro.",
                 "Está funcionando",
                 "a todo vapor."),
    "45:5abb": L("45:5abb",
                 "O transmissor de",
                 "rádio finalmente",
                 "parou a transmis-",
                 "são maligna."),

    # ---------------- B3F ----------------
    "45:5e2f": L("45:5e2f",
                 "LANCE: Precisa de",
                 "duas senhas para",
                 "entrar na sala",
                 "do chefe.",
                 "Só uns poucos",
                 "ROCKETS conhecem",
                 "essas senhas.",
                 "Aquele ROCKET ali",
                 "teve a bondade",
                 "de me contar.",
                 "{PLAYER}, vamos",
                 "buscar as senhas."),
    "45:5eeb": L("45:5eeb",
                 "Urrggh… O cara",
                 "de capa é",
                 "forte demais…"),
    "45:5f1d": L("45:5f1d",
                 "…",
                 "Eu não disse que",
                 "eu ia",
                 "destruir a TEAM",
                 "ROCKET?",
                 "…Me diga, quem era",
                 "o cara de capa",
                 "que usava POKéMON",
                 "dragão?",
                 "Meus POKéMON não",
                 "foram páreo.",
                 "Não ligo de ter",
                 "perdido. Eu venço",
                 "ele com POKéMON",
                 "mais fortes.",
                 "O que me incomoda",
                 "é o que ele falou",
                 "Ele disse que eu",
                 "não amo e não",
                 "confio o bastante",
                 "nos meus POKéMON.",
                 "Fico furioso de",
                 "ter perdido para",
                 "um bonzinho.",
                 "…Hunf! Não tenho",
                 "tempo para gente",
                 "como você!"),
    "45:60b6": L("45:60b6",
                 "O quê? Quem é você",
                 "Esta é a sala",
                 "do nosso líder,",
                 "GIOVANNI.",
                 "Desde que acabou",
                 "com a TEAM ROCKET",
                 "há três anos, ele",
                 "está treinando.",
                 "Mas temos certeza",
                 "que ele volta",
                 "um dia para",
                 "assumir de novo.",
                 "Por isso estamos",
                 "de guarda.",
                 "Não vou deixar",
                 "ninguém mexer",
                 "neste lugar!"),
    "45:61c7": L("45:61c7",
                 "Eu… Eu não pude",
                 "fazer nada…",
                 "GIOVANNI, por",
                 "favor me perdoe…"),
    "45:61fe": L("45:61fe",
                 "Não, não posso",
                 "deixar isso me",
                 "abalar. Preciso",
                 "avisar os outros…"),
    "45:623b": L("45:623b",
                 "MURKROW: A senha",
                 "é…",
                 "SALVE GIOVANNI."),
    "45:6626": L("45:6626",
                 "A porta fechou…",
                 "Precisa de duas",
                 "senhas para abrir"),
    "45:6659": L("45:6659",
                 "A porta fechou…",
                 "{PLAYER} digitou",
                 "as duas senhas.",
                 "A porta abriu!"),
}
