# -*- coding: utf-8 -*-
"""Lote 09a: RADIO TOWER (2F, 3F, 4F, 5F)"""
from pt.estrutura import linhas as L

DIALOGO = {
    "43:570e": L("43:570e",  # 3
                 "Você pode ouvir",
                 "a radio em",
                 "qualquer lugar."),
    "43:5740": L("43:5740",  # 3
                 "Canções de ninar",
                 "na radio podem",
                 "fazer dormir."),
    "43:576d": L("43:576d",  # 3
                 "Por que eles",
                 "querem tomar conta",
                 "da RADIO TOWER?"),
    "43:57a0": L("43:57a0",  # 2
                 "JIGGLYPUFF:",
                 "Jiggly\u2026"),
    "43:57b5": L("43:57b5",  # 8
                 "Desculpe. Somente",
                 "pessoal autorizado",
                 "além daqui.",
                 "Não era assim",
                 "antes.",
                 "Algo esta errado",
                 "com o DIRETOR",
                 "\u2026"),
    "43:582e": L("43:582e",  # 5
                 "Sinta-se livre",
                 "para olhar.",
                 "O DIRETOR esta",
                 "bom de novo,",
                 "como era antes."),
    "43:5ade": L("43:5ade",  # 1
                 "2F VENDAS"),
    "43:5ae8": L("43:5ae8",  # 4
                 "TALK POKéMON",
                 "DO PROF.OAK",
                 "O Show Mais Quente",
                 "no Ar!"),
    "43:5b1b": L("43:5b1b",  # 2
                 "Em Qualquer Lugar",
                 "POKéMON Radio"),
    "43:5cbf": L("43:5cbf",  # 6
                 "Temos gravações",
                 "dos gritos de",
                 "todos os POKéMON",
                 "encontrados.",
                 "Devemos ter uns",
                 "200 tipos."),
    "43:5d20": L("43:5d20",  # 7
                 "Para treinadores,",
                 "POKéMON são",
                 "seus parceiros.",
                 "E terrível como a",
                 "TEAM ROCKET esta",
                 "tentando controlar",
                 "POKéMON."),
    "43:5d89": L("43:5d89",  # 7
                 "Trabalhamos 24h",
                 "por dia para",
                 "transmitir",
                 "programas legais.",
                 "Vou dar o meu",
                 "melhor para",
                 "trabalhar!"),
    "43:5df2": L("43:5df2",  # 8
                 "O chefe da TEAM",
                 "ROCKET trancou",
                 "ele mesmo lá.",
                 "Mas o DIRETOR",
                 "pode abrir.",
                 "Ele esta no",
                 "quinto andar.",
                 "Salve-o!"),
    "43:5e69": L("43:5e69",  # 2
                 "O DIRETOR",
                 "esta seguro?"),
    "43:5e80": L("43:5e80",  # 4
                 "Obrigado!",
                 "Você e meu herói!",
                 "Isto e um simbolo",
                 "de gratidão."),
    "43:5ebf": L("43:5ebf",  # 4
                 "E SUNNY DAY.",
                 "Fortalece",
                 "movimentos de fogo",
                 "por um tempo."),
    "43:5efa": L("43:5efa",  # 2
                 "Você foi",
                 "maravilhoso!"),
    "43:6060": L("43:6060",  # 1
                 "Estou feito!"),
    "43:6100": L("43:6100",  # 4
                 "Bwahahaha\u2026",
                 "Posso transmitir",
                 "um sinal forte",
                 "daqui em diante."),
    "43:6142": L("43:6142",  # 2
                 "E o slot da",
                 "CHAVE-CARTAO."),
    "43:615a": L("43:615a",  # 2
                 "{PLAYER} inseriu",
                 "a CHAVE-CARTAO."),
    "43:6174": L("43:6174",  # 1
                 "3F PESSOAL"),
    "43:6182": L("43:6182",  # 2
                 "MUSICA POKéMON",
                 "com o DJ BEN"),
    "43:62b0": L("43:62b0",  # 5
                 "Ouvi a radio",
                 "quando estava",
                 "nas RUÍNAS.",
                 "Ouvi uma",
                 "transmissão lá."),
    "43:6306": L("43:6306",  # 4
                 "MARY: Por que?",
                 "Por que tenho que",
                 "sofrer com isso?",
                 "MEOWTH me ajuda!"),
    "43:6349": L("43:6349",  # 4
                 "MARY: Oh! Você e",
                 "meu salvador!",
                 "Vai aceitar isso",
                 "como obrigada?"),
    "43:638d": L("43:638d",  # 4
                 "MARY: E perfeito",
                 "para POKéMON",
                 "que conhecem",
                 "ataques normais."),
    "43:63ca": L("43:63ca",  # 4
                 "MARY: Por favor,",
                 "sintonize no",
                 "meu programa",
                 "TALK POKéMON."),
    "43:6404": L("43:6404",  # 1
                 "MEOWTH: Meowth\u2026"),
    "43:6600": L("43:6600",  # 4
                 "Excelente.",
                 "Esta RADIO TOWER",
                 "ira realizar",
                 "nosso plano."),
    "43:669c": L("43:669c",  # 1
                 "4F PRODUCAO"),
    "43:66ab": L("43:66ab",  # 1
                 "4F ESTUDIO 2"),
    "43:686a": L("43:686a",  # 2
                 "V-Você! Você veio",
                 "me resgatar?"),
    "43:6889": L("43:6889",  # 14
                 "Era isso que você",
                 "esperava?",
                 "Errado!",
                 "Sou um impostor!",
                 "Fingi ser o",
                 "verdadeiro para",
                 "preparar",
                 "nossa tomada.",
                 "Quer saber onde",
                 "escondemos o",
                 "DIRETOR mesmo?",
                 "Claro, vou te",
                 "contar. Mas só",
                 "se me vencer!"),
    "43:6965": L("43:6965",  # 2
                 "Tudo bem. Vou te",
                 "contar."),
    "43:6988": L("43:6988",  # 9
                 "Escondemos o",
                 "DIRETOR real",
                 "no ARMAZEM",
                 "SUBTERRANEO.",
                 "E na ponta do",
                 "SUBTERRANEO.",
                 "Mas duvido",
                 "que você",
                 "chegue lá."),
    "43:6b23": L("43:6b23",  # 19
                 "Oh? Você conseguiu",
                 "chegar até aqui?",
                 "Você deve ser um",
                 "bom treinador.",
                 "Nossos planos são",
                 "tomar esta RADIO",
                 "ESTACAO e anunciar",
                 "nosso retorno.",
                 "Isso deve trazer",
                 "nosso chefe",
                 "GIOVANNI de volta",
                 "de seu treinamento",
                 "solo.",
                 "Vamos recuperar",
                 "nossa glória",
                 "anterior.",
                 "Não vou permitir",
                 "que você atrapalhe",
                 "nossos planos."),
    "43:6c45": L("43:6c45",  # 2
                 "Não! Perdoe-me,",
                 "GIOVANNI!"),
    "43:6c60": L("43:6c60",  # 10
                 "Como pode ser?",
                 "Nossos sonhos se",
                 "tornaram nada.",
                 "Não fui a altura",
                 "da tarefa afinal.",
                 "Como GIOVANNI fez",
                 "antes de mim,",
                 "vou dissolver a",
                 "TEAM ROCKET hoje.",
                 "Adeus."),
    "43:6d04": L("43:6d04",  # 9
                 "DIRETOR: {PLAYER},",
                 "obrigado!",
                 "Suas ações",
                 "corajosas",
                 "salvaram POKéMON",
                 "em todo o pais.",
                 "Sei que não e",
                 "muito, mas por",
                 "favor, aceite."),
    "43:6d7e": L("43:6d7e",  # 23
                 "Costumava haver",
                 "uma torre bem aqui",
                 "em GOLDENROD CITY",
                 "Mas era velha e",
                 "rangida.",
                 "Então a troca-",
                 "mos pela RADIO",
                 "TOWER. Na demoli-",
                 "cão, encontramos",
                 "isso no topo.",
                 "Ouvi que um",
                 "POKéMON gigante",
                 "costumava voar",
                 "sobre GOLDENROD.",
                 "Talvez tenha",
                 "caido de um",
                 "POKéMON.",
                 "Talvez como o que",
                 "aparece na",
                 "TIN TOWER em",
                 "ECRUTEAK CITY.",
                 "Bom, vou ao meu",
                 "ESCRITORIO."),
    "43:6ee3": L("43:6ee3",  # 23
                 "Costumava haver",
                 "uma torre bem aqui",
                 "em GOLDENROD CITY",
                 "Mas era velha e",
                 "rangida.",
                 "Então a troca-",
                 "mos pela RADIO",
                 "TOWER. Na demoli-",
                 "cão, encontramos",
                 "isso no topo.",
                 "Ouvi que um",
                 "POKéMON gigante",
                 "costumava voar",
                 "sobre GOLDENROD.",
                 "Talvez tenha",
                 "caido de um",
                 "POKéMON. Talvez",
                 "como o que",
                 "veio das WHIRL",
                 "ISLANDS perto de",
                 "CIANWOOD.",
                 "Bom, vou ao meu",
                 "ESCRITORIO."),
    "43:7049": L("43:7049",  # 11
                 "DIRETOR: Ola,",
                 "{PLAYER}!",
                 "Sabe, eu amo",
                 "POKéMON.",
                 "Construi esta",
                 "RADIO TOWER para",
                 "expressar meu amor",
                 "por POKéMON.",
                 "Seria bom se as",
                 "pessoas curtissem",
                 "nossos programas."),
    "43:70e3": L("43:70e3",  # 2
                 "BEN: Você ouve",
                 "nossa música?"),
    "43:7105": L("43:7105",  # 2
                 "5F ESCRITORIO",
                 "DO DIRETOR"),
    "43:711e": L("43:711e",  # 1
                 "5F ESTUDIO 1"),
}
