# -*- coding: utf-8 -*-
"""Lote 14a -- o telefone: a MÃE, o SISTEMA DE ARMAZENAMENTO e o PROF.ELM.

Banco 41, achado pela varredura.  Sao as ligacoes que chegam pela
POKéGEAR o jogo inteiro -- a mae perguntando onde voce esta e se quer
guardar dinheiro, o sistema avisando que a BOX encheu, o ELM ligando
sobre o EGG.

Muitas chaves do banco 41 sao cauda de outra: `41:4acc` e o final de
`41:4aba`, porque o script entra no meio do bloco.  Ficaram de fora --
traduzir a cauda nao muda nada na tela, ja que o texto vem inteiro do
ponteiro de cima.

Ficam no original: BILL, PROF.ELM, MR.POKéMON, EGG, BOX, POKéRUS,
VIOLET CITY.  "MOM" vira MÃE porque e como a personagem e chamada nas
falas ja publicadas do lote 1.
"""
from pt.estrutura import linhas as L

DIALOGO = {
    # ---------------- a MÃE: onde voce esta ----------------
    "41:4a99": L("41:4a99",
                 "Alô?",
                 "Ah, oi, {PLAYER}!",
                 "Trabalhando duro?"),
    "41:4aba": L("41:4aba",
                 "Ah, você está em",
                 "{STRBUF}…",
                 "Não é ali que",
                 "{STRBUF}",
                 "fica? Você foi",
                 "dar uma olhada?"),
    "41:4b04": L("41:4b04",
                 "Sério, você está",
                 "em {STRBUF}?",
                 "Nunca fui lá.",
                 "Que legal isso,",
                 "{PLAYER}."),
    "41:4b4a": L("41:4b4a",
                 "O quê? Você está",
                 "em {STRBUF}?",
                 "Venha ver sua MÃE",
                 "um dia desses!"),
    "41:4b7d": L("41:4b7d",
                 "Você está visitan-",
                 "do {STRBUF}?",
                 "Que tal vir para",
                 "casa um pouco?"),
    "41:4bb5": L("41:4bb5",
                 "Uau, você está em",
                 "{STRBUF}?",
                 "Boa sorte na sua",
                 "missão POKéMON!"),
    "41:4be9": L("41:4be9",
                 "Isso parece bem",
                 "difícil.",
                 "Mas, {PLAYER}, eu",
                 "sei que você é",
                 "determinado. Vai",
                 "ficar bem, né?"),

    # ---------------- a MÃE: o dinheiro ----------------
    "41:4c40": L("41:4c40",
                 "A propósito, você",
                 "tem ¥{STRBUF}.",
                 "Quer continuar",
                 "guardando?"),
    "41:4c83": L("41:4c83",
                 "É importante",
                 "guardar dinheiro."),
    "41:4ca6": L("41:4ca6",
                 "Ah, {PLAYER},",
                 "você não está",
                 "guardando nada.",
                 "Quer guardar?"),
    "41:4ce2": L("41:4ce2",
                 "A propósito, você",
                 "tem ¥{STRBUF}.",
                 "Quer voltar a",
                 "guardar?"),
    "41:4d22": L("41:4d22",
                 "Certo. Eu guardo",
                 "seu dinheiro."),
    "41:4d3c": L("41:4d3c",
                 "Certo. Paro de",
                 "guardar."),
    "41:4d5d": L("41:4d5d",
                 "{PLAYER}, continue",
                 "assim! Estou",
                 "torcendo, filho!"),

    # ---------------- a MÃE: o comeco da jornada ----------------
    "41:4d87": L("41:4d87",
                 "Alô?",
                 "Ah, oi, {PLAYER}!",
                 "O PROF.ELM não",
                 "estava esperando?"),
    "41:4dba": L("41:4dba",
                 "Alô?",
                 "Ah, oi, {PLAYER}!",
                 "Você está numa",
                 "missão do PROF.",
                 "ELM? Se comporte!"),
    "41:4dfc": L("41:4dfc",
                 "Alô?",
                 "Oi, {PLAYER}! Se",
                 "já terminou o",
                 "seu recado, volte",
                 "para casa, filho."),
    "41:4e3e": L("41:4e3e",
                 "Alô?",
                 "…… {PLAYER}?",
                 "O PROF.ELM me",
                 "disse que você foi",
                 "numa viagem longa",
                 "Queria que tivesse",
                 "me contado…",
                 "E o dinheiro?",
                 "Eu guardo?"),

    # ---------------- o sistema de armazenamento ----------------
    "41:4ec4": L("41:4ec4",
                 "Bom dia!",
                 "Aqui é o SERVIÇO",
                 "DE ADMINISTRAÇÃO",
                 "DO SISTEMA DE",
                 "ARMAZENAMENTO."),
    "41:4f0d": L("41:4f0d",
                 "Boa tarde!",
                 "Aqui é o SERVIÇO",
                 "DE ADMINISTRAÇÃO",
                 "DO SISTEMA DE",
                 "ARMAZENAMENTO."),
    "41:4f52": L("41:4f52",
                 "Boa noite!",
                 "Aqui é o SERVIÇO",
                 "DE ADMINISTRAÇÃO",
                 "DO SISTEMA DE",
                 "ARMAZENAMENTO."),
    "41:4f9b": L("41:4f9b",
                 "Quem fala?",
                 "{PLAYER}, é você?",
                 "Um segundinho…",
                 "……",
                 "……"),
    "41:4fc7": L("41:4fc7",
                 "Obrigado por",
                 "esperar!",
                 "{PLAYER}, sua BOX",
                 "tem espaço para",
                 "mais {STRBUF}!",
                 "Vá lá e encha",
                 "ela!"),
    "41:5024": L("41:5024",
                 "Obrigado por",
                 "esperar!",
                 "{PLAYER}, sua BOX",
                 "só tem lugar",
                 "para {STRBUF}.",
                 "Talvez seja hora",
                 "de trocar de BOX."),
    "41:508a": L("41:508a",
                 "Obrigado por",
                 "esperar!",
                 "{PLAYER}, sua BOX",
                 "está cheia!",
                 "Vai ter que trocar",
                 "de BOX se quiser",
                 "pegar mais",
                 "POKéMON."),
    "41:50ef": L("41:50ef",
                 "Oi, {PLAYER}?",
                 "Sou eu, o BILL!",
                 "Obrigado por usar",
                 "o STORAGE SYSTEM.",
                 "O último POKéMON",
                 "que você mandou",
                 "encheu sua BOX.",
                 "Vai ter que trocar",
                 "de BOX se quiser",
                 "pegar mais",
                 "POKéMON.",
                 "Até mais!"),

    # ---------------- o PROF.ELM ----------------
    "41:5199": L("41:5199",
                 "Alô, {PLAYER}?",
                 "Tente não exage-",
                 "rar.",
                 "Cure seus POKéMON",
                 "sempre que eles",
                 "se machucarem."),
    "41:51e6": L("41:51e6",
                 "Alô, {PLAYER}?",
                 "Encontrou o MR.",
                 "POKéMON? Ótimo!",
                 "Volte em paz!"),
    "41:5221": L("41:5221",
                 "{PLAYER}? Estou",
                 "muito chateado.",
                 "Roubaram um",
                 "POKéMON daqui.",
                 "Como alguém faz",
                 "uma coisa dessas?"),
    "41:5272": L("41:5272",
                 "Alô, {PLAYER}?",
                 "Estamos checando o",
                 "EGG. Ele parece",
                 "mesmo ser um",
                 "EGG de POKéMON."),
    "41:52b9": L("41:52b9",
                 "Alô, {PLAYER}?",
                 "Viu meu assisten-",
                 "te? Ele está no",
                 "CENTRO POKéMON de",
                 "VIOLET CITY."),
    "41:5305": L("41:5305",
                 "Alô, {PLAYER}?",
                 "Como está o EGG?",
                 "Mudou algo?",
                 "Se acontecer algo,",
                 "por favor ligue."),
    "41:5358": L("41:5358",
                 "Alô, {PLAYER}?",
                 "Como está o EGG?",
                 "O quê? Chocou?",
                 "Uau! Que tipo de",
                 "POKéMON é?",
                 "Venha me mostrar",
                 "agora!"),
    "41:53bc": L("41:53bc",
                 "Alô, {PLAYER}?",
                 "Acabei de fazer",
                 "uma descoberta.",
                 "O tempo que um",
                 "EGG leva para",
                 "chocar depende do",
                 "POKéMON."),
    "41:541f": L("41:541f",
                 "Alô, {PLAYER}?",
                 "Ainda é um",
                 "mistério que",
                 "golpes um POKéMON",
                 "chocado sabe.",
                 "Estamos investi-",
                 "gando isso agora."),
    "41:5484": L("41:5484",
                 "Alô, {PLAYER}?",
                 "Descobri uma",
                 "coisa estranha.",
                 "Parece que existe",
                 "uma coisa chamada",
                 "POKéRUS que in-",
                 "fecta POKéMON.",
                 "Sim, é como um",
                 "vírus, por isso",
                 "se chama POKéRUS.",
                 "Ele se multiplica",
                 "rápido e infecta",
                 "outros POKéMON.",
                 "Mas é só isso.",
                 "Não parece fazer",
                 "nada, e some",
                 "com o tempo",
                 "sozinho.",
                 "Acho que não é",
                 "nada para se",
                 "preocupar. Tchau!"),
}
