# -*- coding: utf-8 -*-
"""Lote 29 -- as 93 derivadas do banco 57: a bicicletaria de GOLDENROD,
a casa do BILL, a MOM do BILL, a loja da ovolo (S.S. AQUA), o trem para
SAFFRON e KANTO, o PRESIDENTE, o MAGNET TRAIN, a DEPT. STORE, o GAME
CORNER e a ILEX FOREST.

Ficam no original: BILL, EEVEE, WHITNEY, PROF.ELM, PROF.OAK, TELEPORTER,
TIME CAPSULE, RAIL PASS, X SPEED, X SPECIAL, PROTEIN, IRON, BLIZZARD,
SQUIRTBOTTLE, SWEET SCENT, METRONOME, CLEFAIRY, ABRA, MACHOKE, KADABRA,
HAUNTER, GRAVELER, Game Link, MYSTERY GIFT, Game Boy Color, LUCKY CHANNEL,
COLOSSEUM, COIN CASE, BICYCLE, UNDERGROUND, TM, PP, POKéMON, POKéDEX,
POKéGEAR, CENTRO POKéMON, SAFFRON, GOLDENROD, JOHTO, KANTO, ECRUTEAK.
"""
from pt.estrutura import linhas as L

DIALOGO = {

    # ---------------- banco 57 ----------------
    "57:4791": L("57:4791",
                 "…Suspiro… Me",
                 "mudei, mas não",
                 "vendo minhas",
                 "BICYCLE. Por quê?",
                 "Ah, sei! Você",
                 "poderia andar e",
                 "anunciar pra mim?"),
    "57:4802": L("57:4802",
                 "Sério? Ótimo!",
                 "Dê-me seu nome",
                 "e telefone e",
                 "lhe empresto",
                 "uma BICYCLE."),
    "57:4852": L("57:4852",
                 "{PLAYER} pegou",
                 "uma BICYCLE."),
    "57:4869": L("57:4869",
                 "Minhas BICYCLEs",
                 "são de primeira!",
                 "Você pode andar",
                 "em qualquer lugar"),
    "57:48a2": L("57:48a2",
                 "…Suspiro… Ah,",
                 "se as pessoas",
                 "fossem boas…"),
    "57:48f7": L("57:48f7",
                 "É uma BICYCLE",
                 "nova e brilhante!"),
    "57:49ad": L("57:49ad",
                 "Se tratar seu",
                 "POKéMON bem,",
                 "eles vão te amar",
                 "de volta.",
                 "Ah? Deixe ver",
                 "seu {STRBUF}…"),
    "57:4a06": L("57:4a06",
                 "Ele parece muito",
                 "feliz! Deve te",
                 "amar muito."),
    "57:4a36": L("57:4a36",
                 "Tenho a sensação",
                 "de que ele",
                 "confia em você."),
    "57:4a98": L("57:4a98",
                 "Ele é bem fofo."),
    "57:4aa9": L("57:4aa9",
                 "Trate ele melhor.",
                 "Ele ainda não",
                 "confia em você."),
    "57:4adb": L("57:4adb",
                 "Ele não parece",
                 "gostar de você.",
                 "Parece bravo."),
    "57:4b0e": L("57:4b0e",
                 "Vivo perdendo",
                 "batalhas e meus",
                 "POKéMON acabam",
                 "desmaiando…",
                 "Talvez por isso",
                 "meus POKéMON não",
                 "gostem de mim…"),
    "57:4b71": L("57:4b71",
                 "Quando uso item",
                 "no POKéMON, ele",
                 "fica todo feliz!"),
    "57:4c7e": L("57:4c7e",
                 "BILL: Oi, {PLAYER}!",
                 "Faça um favor e",
                 "fique com este",
                 "EEVEE.",
                 "Ele veio quando",
                 "eu ajustava",
                 "a TIME CAPSULE.",
                 "Alguém precisa",
                 "tomar conta,",
                 "mas eu não gosto",
                 "de sair.",
                 "Posso contar com",
                 "você, {PLAYER}?"),
    "57:4d49": L("57:4d49",
                 "BILL: Eu sabia!",
                 "Isso aí, herói!",
                 "Você é um cara",
                 "dos bons!",
                 "OK, conto com",
                 "você. Cuide",
                 "bem dele."),
    "57:4db5": L("57:4db5",
                 "{PLAYER} recebeu",
                 "um EEVEE!"),
    "57:4dc8": L("57:4dc8",
                 "BILL: O PROF.ELM",
                 "diz que o EEVEE",
                 "pode evoluir de",
                 "modos inéditos."),
    "57:4e09": L("57:4e09",
                 "Ei, espera. Você",
                 "não pode levar",
                 "mais POKéMON."),
    "57:4e34": L("57:4e34",
                 "Oh… E agora,",
                 "o que fazer?"),
    "57:4e49": L("57:4e49",
                 "BILL: Eu costumava",
                 "fazer testes com",
                 "um TELEPORTER.",
                 "Deveria dar",
                 "continuação."),
    "57:4e93": L("57:4e93",
                 "Ah, coleciona",
                 "POKéMON? Meu filho",
                 "BILL é um expert.",
                 "Ele teve que ir",
                 "ao CENTRO POKéMON",
                 "de ECRUTEAK",
                 "CITY."),
    "57:4efa": L("57:4efa",
                 "Fico tão feliz",
                 "em ver meu filho."),
    "57:4f1d": L("57:4f1d",
                 "Você é treinador?",
                 "Tenho um número",
                 "de telefone",
                 "útil pra você."),
    "57:4f58": L("57:4f58",
                 "{PLAYER} anotou",
                 "o número do BILL."),
    "57:4f72": L("57:4f72",
                 "Meu irmão criou",
                 "o sistema de",
                 "guarda de POKéMON",
                 "no PC.",
                 "Ia te dar o",
                 "número do BILL…"),
    "57:4fc5": L("57:4fc5",
                 "Você não pode mais",
                 "anotar números."),
    "57:4fe8": L("57:4fe8",
                 "Meu irmão mais",
                 "velho, BILL, fez",
                 "o sistema de",
                 "guarda de POKéMON"),
    "57:50d7": L("57:50d7",
                 "O trem não",
                 "chegou…",
                 "Já sei! Vou levar",
                 "os passageiros",
                 "nas costas!",
                 "Não vai dar."),
    "57:512e": L("57:512e",
                 "Vamos partir logo",
                 "para SAFFRON.",
                 "Vocês virão",
                 "a bordo?"),
    "57:5164": L("57:5164",
                 "Posso ver seu",
                 "RAIL PASS?",
                 "Certo. Venha por",
                 "aqui, senhor."),
    "57:51a0": L("57:51a0",
                 "Desculpe. Você",
                 "não tem RAIL PASS"),
    "57:51c3": L("57:51c3",
                 "Esperamos vê-lo",
                 "novamente!"),
    "57:51de": L("57:51de",
                 "Chegamos a",
                 "GOLDENROD!",
                 "Esperamos vê-lo",
                 "de novo."),
    "57:5217": L("57:5217",
                 "Sou o PRESIDENTE.",
                 "Meu sonho era",
                 "construir um trem",
                 "mais rápido que",
                 "qualquer POKéMON.",
                 "Ele realmente",
                 "aproxima JOHTO e",
                 "KANTO."),
    "57:5311": L("57:5311",
                 "Ah, você é melhor",
                 "que a WHITNEY.",
                 "Conhece aquela",
                 "árvore que anda?",
                 "Se molhá-la com",
                 "uma SQUIRTBOTTLE,",
                 "ela ataca.",
                 "Mas, como você",
                 "tem BADGE,",
                 "vai ficar bem."),
    "57:53b6": L("57:53b6",
                 "Lalala lalalala.",
                 "Muita água,",
                 "minha linda!"),
    "57:53e9": L("57:53e9",
                 "Quando molhei",
                 "aquela árvore",
                 "que anda na ROTA",
                 "36, ela pulou!",
                 "Só pode ser",
                 "um POKéMON.",
                 "Mas só alguém",
                 "como a WHITNEY,",
                 "nossa LÍDER de",
                 "GINÁSIO, a vence."),
    "57:5485": L("57:5485",
                 "Conhece a árvore",
                 "que anda?",
                 "Se você a regar,",
                 "ela pula de",
                 "surpresa!"),
    "57:5513": L("57:5513",
                 "O COLOSSEUM",
                 "nos andares do",
                 "CENTRO POKéMON,",
                 "é para batalhas",
                 "via link.",
                 "Os recordes de",
                 "luta na parede,",
                 "não posso perder."),
    "57:5597": L("57:5597",
                 "Quantos tipos de",
                 "POKéMON existem",
                 "no mundo?",
                 "Há três anos,",
                 "o PROF.OAK disse",
                 "que existiam 150",
                 "tipos",
                 "diferentes."),
    "57:5614": L("57:5614",
                 "Um POKéMON de",
                 "nível mais alto",
                 "nem sempre vence.",
                 "Ele pode até ter",
                 "desvantagem de",
                 "tipo.",
                 "Acho que não",
                 "existe um único",
                 "POKéMON que seja",
                 "o mais forte."),
    "57:56fe": L("57:56fe",
                 "Uma vez, numa",
                 "batalha, meu",
                 "POKéMON não",
                 "conseguia agir.",
                 "Os POWER POINTS,",
                 "ou PP, dos seus",
                 "golpes tinham",
                 "acabado."),
    "57:576f": L("57:576f",
                 "Às vezes, um",
                 "POKéMON saudável",
                 "não consegue usar",
                 "seus golpes.",
                 "Se isso ocorrer,",
                 "curar no CENTRO",
                 "POKéMON ou usar",
                 "um item."),
    "57:5cb7": L("57:5cb7",
                 "A POKéGEAR pode",
                 "guardar até dez",
                 "números.",
                 "É difícil",
                 "decidir quais",
                 "guardar."),
    "57:5d0d": L("57:5d0d",
                 "Ganhei meu ABRA",
                 "na CASA DE JOGOS.",
                 "Agora é meu",
                 "melhor parceiro."),
    "57:5d49": L("57:5d49",
                 "Esta LOJA me faz",
                 "ver que GOLDENROD",
                 "é uma cidade",
                 "grande.",
                 "A seleção daqui",
                 "não tem igual",
                 "em nenhum lugar."),
    "57:5dba": L("57:5dba",
                 "SUA COMPANHEIRA",
                 "DE VIAGEM",
                 "2º ANDAR: MERCADO",
                 "DO TREINADOR"),
    "57:5e5e": L("57:5e5e",
                 "Eu, eu, eu sou bem",
                 "impaciente!",
                 "Uso X SPEED na",
                 "batalha para",
                 "acelerar POKéMON."),
    "57:5ea7": L("57:5ea7",
                 "Ei! Em batalha,",
                 "você usa X",
                 "SPECIAL?",
                 "É demais. Ele",
                 "aumenta muito",
                 "os SPECIAL!"),
    "57:5f9d": L("57:5f9d",
                 "Ei. Amo POKéMON",
                 "fortes.",
                 "Dou PROTEIN a",
                 "eles para elevar",
                 "o ATTACK."),
    "57:5fe7": L("57:5fe7",
                 "IRON: a DEFESA do",
                 "POKéMON sobe."),
    "57:6009": L("57:6009",
                 "Alguns POKéMON",
                 "evoluem quando",
                 "são trocados por",
                 "cabo Game Link.",
                 "Conheço quatro:",
                 "MACHOKE, KADABRA,",
                 "HAUNTER e, hum,",
                 "GRAVELER.",
                 "Dizem que existem",
                 "outros também."),
    "57:60a2": L("57:60a2",
                 "Vamos Turbinar",
                 "Seu POKéMON!",
                 "4º ANDAR REMÉDIOS"),
    "57:61d8": L("57:61d8",
                 "Olá. Oh, seu",
                 "POKéMON…"),
    "57:61ef": L("57:61ef",
                 "Ele é muito afei-",
                 "çoado a você.",
                 "Este golpe deve",
                 "ser perfeito para",
                 "vocês dois."),
    "57:623b": L("57:623b",
                 "É adorável!",
                 "Ensine bons",
                 "golpes de TM."),
    "57:626d": L("57:626d",
                 "Parece mau. Que",
                 "tal esta TM para",
                 "ele?"),
    "57:6297": L("57:6297",
                 "Com certeza há",
                 "TM perfeita para",
                 "o seu",
                 "POKéMON."),
    "57:62d6": L("57:62d6",
                 "MYSTERY GIFT.",
                 "Com um pequeno",
                 "bip, você",
                 "ganha um presente"),
    "57:630e": L("57:630e",
                 "O MYSTERY GIFT",
                 "exige um",
                 "Game Boy Color."),
    "57:6342": L("57:6342",
                 "Aos domingos, uma",
                 "moça vem olhar",
                 "os POKéMON.",
                 "Ela até dá",
                 "TM de presente!"),
    "57:6388": L("57:6388",
                 "Não dá para",
                 "renomear um",
                 "POKéMON trocado.",
                 "O nome mostra o",
                 "carinho do",
                 "treinador antigo",
                 "por ele."),
    "57:63f9": L("57:63f9",
                 "Personalize seu",
                 "POKéMON",
                 "5º ANDAR: TM"),
    "57:6560": L("57:6560",
                 "Uma máquina de",
                 "vendas! O menu:"),
    "57:6584": L("57:6584",
                 "Click! Uma",
                 "lata de {STRBUF}",
                 "caiu!"),
    "57:65a7": L("57:65a7",
                 "Opa, dinheiro",
                 "insuficiente…"),
    "57:65c0": L("57:65c0",
                 "Não há mais espaço",
                 "para coisas…"),
    "57:65e0": L("57:65e0",
                 "Você ouve a",
                 "LUCKY CHANNEL?",
                 "Se quer vencer,",
                 "troque POKéMON",
                 "com o máximo de",
                 "gente para ter",
                 "números de ID",
                 "diferentes."),
    "57:665f": L("57:665f",
                 "Se estiver cansado",
                 "tente as bebidas",
                 "das máquinas.",
                 "Seu POKéMON vai",
                 "amar também."),
    "57:66af": L("57:66af",
                 "Descanse um pouco",
                 "das compras!",
                 "6º ANDAR: TERRAÇO"),
    "57:6ab5": L("57:6ab5",
                 "Bem-vindo!",
                 "Trocamos suas",
                 "moedas de jogo",
                 "por prêmios bons!"),
    "57:6af0": L("57:6af0",
                 "Qual prêmio você",
                 "quer?"),
    "57:6b0d": L("57:6b0d",
                 "{STRBUF}.",
                 "É isso mesmo?"),
    "57:6b22": L("57:6b22",
                 "Aqui está!"),
    "57:6b30": L("57:6b30",
                 "Precisa de mais",
                 "moedas ainda!"),
    "57:6b4d": L("57:6b4d",
                 "Desculpe. Você",
                 "não pode carregar"),
    "57:6b6e": L("57:6b6e",
                 "OK. Guarde suas",
                 "moedas e",
                 "volte sempre!"),
    "57:6b9a": L("57:6b9a",
                 "Oh? Você não tem",
                 "a COIN CASE."),
    "57:6bba": L("57:6bba",
                 "Sempre jogo nesta",
                 "máquina.",
                 "Acho que ela paga",
                 "mais que outras."),
    "57:6c03": L("57:6c03",
                 "Adoro esta nova",
                 "caça-níqueis.",
                 "É mais desafiadora",
                 "que as de",
                 "CELADON."),
    "57:6c59": L("57:6c59",
                 "A vida é um jogo.",
                 "Vou virar",
                 "cartas até cair!"),
    "57:6c90": L("57:6c90",
                 "Vira-cartas…",
                 "Prefiro aos",
                 "caça-níqueis",
                 "porque é mais",
                 "fácil de calcular",
                 "as chances.",
                 "Mas paga menos."),
    "57:6cfc": L("57:6cfc",
                 "Não paro até",
                 "conseguir vencer!"),
    "57:6d16": L("57:6d16",
                 "Ensinei BLIZZARD",
                 "ao meu POKéMON.",
                 "Foi difícil juntar",
                 "as moedas para",
                 "ele, mas valeu",
                 "a pena."),
    "57:6d72": L("57:6d72",
                 "Perdi nas",
                 "caça-níqueis,",
                 "gastei tudo",
                 "na vira-cartas…",
                 "Fiquei tão nervoso",
                 "que joguei fora",
                 "minha COIN CASE",
                 "no UNDERGROUND."),
    "57:6f2c": L("57:6f2c",
                 "A ILEX FOREST",
                 "é grande. Cuidado!",
                 "Não se perca."),
    "57:6f5c": L("57:6f5c",
                 "A FLORESTA é",
                 "cuidada pelo",
                 "seu protetor.",
                 "Nada de",
                 "traquinagens!"),
    "57:6ffe": L("57:6ffe",
                 "Ah, querido. Faz",
                 "uma POKéDEX?",
                 "Deve ser difícil",
                 "se os POKéMON",
                 "não aparecem.",
                 "Tente usar a TM."),
    "57:7057": L("57:7057",
                 "É SWEET SCENT.",
                 "Use onde há",
                 "POKéMON por",
                 "perto. Eles",
                 "serão atraídos."),
    "57:70b6": L("57:70b6",
                 "Viu o santuário",
                 "em honra ao",
                 "protetor?",
                 "Ele vigia a",
                 "FLORESTA através",
                 "dos tempos.",
                 "Acho que deve ser",
                 "um POKéMON do tipo",
                 "grama."),
    "57:71b8": L("57:71b8",
                 "O vovô estava",
                 "procurando você."),
    "57:c700": L("57:c700",
                 "…jeito",
                 "como o CLEFAIRY",
                 "balança o dedo",
                 "quando tenta usar",
                 "METRONOME.",
                 "É tão fofo!"),
}