# -*- coding: utf-8 -*-
"""Lote 18 -- banco 4e: o mar de Kanto, a CYCLING ROAD e os motoqueiros.

Ficam no original: SURF, HM, BICYCLE, CYCLING ROAD, GYM BADGES, JOHTO,
CELADON, FUCHSIA, CINNABAR, SEAFOAM ISLANDS.
"""
from pt.estrutura import linhas as L

DIALOGO = {
    # ---------------- treinadores de passagem ----------------
    "4e:4592": L("4e:4592", "Aah… Perco mais", "do que ganho…"),
    "4e:45b2": L("4e:45b2",
                 "Para treinadores,",
                 "é lei que a gente",
                 "batalhe sempre que",
                 "se encontra."),
    "4e:45f0": L("4e:45f0", "Ei, você aí!", "Quer batalhar?"),
    "4e:461b": L("4e:461b",
                 "Você é forte.",
                 "Dá para ver que",
                 "treinou bastante."),
    "4e:484e": L("4e:484e",
                 "Esse cara metido",
                 "estava no vulcão",
                 "de CINNABAR."),

    # ---------------- as nadadoras ----------------
    "4e:487b": L("4e:487b",
                 "Oi!",
                 "Eu ia justamente",
                 "passar protetor",
                 "solar."),
    "4e:48ab": L("4e:48ab",
                 "Estou preocupada",
                 "com queimadura…"),
    "4e:48c6": L("4e:48c6",
                 "Tenho que tomar",
                 "cuidado com as",
                 "manchas do sol."),
    "4e:48fc": L("4e:48fc",
                 "Cansei de pescar.",
                 "Vamos batalhar!"),
    "4e:4921": L("4e:4921", "Fracasso total…"),
    "4e:4931": L("4e:4931", "Vou voltar a", "pescar…"),
    "4e:4d68": L("4e:4d68",
                 "Nadar exercita",
                 "o corpo inteiro.",
                 "Faz muito bem",
                 "para você."),
    "4e:4da5": L("4e:4da5",
                 "Que coleção de",
                 "BADGES impressio-",
                 "nante. Vamos",
                 "batalhar!"),
    "4e:4dea": L("4e:4dea",
                 "SURF já não é o",
                 "único golpe de HM",
                 "que serve na água"),
    "4e:4e20": L("4e:4e20",
                 "Acho impossível",
                 "nadar todo o",
                 "caminho até",
                 "JOHTO."),
    "4e:4e60": L("4e:4e60",
                 "Além do mar, eu",
                 "também nado em",
                 "lagos e rios."),
    "4e:4fdf": L("4e:4fdf",
                 "À noite o mar",
                 "fica preto.",
                 "Parece que ele vai",
                 "te engolir."),

    # ---------------- o casal a caminho de FUCHSIA ----------------
    "4e:5025": L("4e:5025",
                 "Ofego, ofego…",
                 "Só… mais… um…",
                 "pouco… até…",
                 "FUCHSIA…"),
    "4e:5066": L("4e:5066",
                 "Eu… pedi para a",
                 "minha namorada",
                 "nadar até FUCHSIA"),
    "4e:509a": L("4e:509a",
                 "Tenho nojo de",
                 "gente banana!"),
    "4e:50b9": L("4e:50b9",
                 "Eu ganharia de",
                 "você na natação…"),
    "4e:50d8": L("4e:50d8",
                 "É uma nadada bem",
                 "curta entre",
                 "FUCHSIA e as",
                 "SEAFOAM ISLANDS…",
                 "Puxa, que homem",
                 "grande o meu",
                 "namorado! Banana!"),
    "4e:5144": L("4e:5144",
                 "Nadar?",
                 "Eu sou péssimo.",
                 "Só fico chapinhan-",
                 "do nesta água",
                 "rasa aqui."),
    "4e:5191": L("4e:5191", "Achei que eu ia", "ganhar."),
    "4e:51a9": L("4e:51a9",
                 "Posso ser ruim de",
                 "natação, mas eu",
                 "amo o mar."),

    # ---------------- a CYCLING ROAD ----------------
    "4e:56d3": L("4e:56d3",
                 "Se você procura",
                 "POKéMON, tem que",
                 "olhar no mato",
                 "alto."),
    "4e:571c": L("4e:571c",
                 "Como você é forte",
                 "deve ser divertido",
                 "batalhar."),
    "4e:574e": L("4e:574e",
                 "A CYCLING ROAD é",
                 "um atalho rápido",
                 "para CELADON."),
    "4e:5784": L("4e:5784",
                 "Se você não tem",
                 "uma BICYCLE, não",
                 "pode usar o",
                 "atalho."),
    "4e:58b2": L("4e:58b2",
                 "Não se ache,",
                 "moleque de JOHTO!"),
    "4e:58d3": L("4e:58d3",
                 "Uau. Que BICYCLE",
                 "maneira!"),
    "4e:58ef": L("4e:58ef",
                 "Mas você não é só",
                 "aparência…"),
    "4e:590d": L("4e:590d",
                 "Eu pareço maneiro",
                 "mas sou fraco, e",
                 "aí não sou nada.",
                 "Tenho que treinar",
                 "mais…"),
    "4e:5957": L("4e:5957",
                 "Ei! Quer fazer uma",
                 "batalha rápida?"),
    "4e:597a": L("4e:597a",
                 "Eita! Você tem um",
                 "torque incrível!"),
    "4e:599c": L("4e:599c",
                 "Andar sem as mãos",
                 "é considerado bom",
                 "na CYCLING ROAD."),
    "4e:59d3": L("4e:59d3",
                 "Somos as estrelas",
                 "sem medo da via!"),
    "4e:59f1": L("4e:59f1", "Arrrgh! Bati e", "capotei!"),
    "4e:5a0a": L("4e:5a0a",
                 "Direção imprudente",
                 "causa acidente!",
                 "Vá com calma!"),
}
